paket.dependencies
When I run paket install I had following error
`Paket failed with: Could not retrieve data from https://www.myget.org/F/roslyn-nightly/odata/Packages(Id='Microsoft.CodeAnalysis.CSharp',Version='1.2.0-beta-20151028-07') Message: One or more errors occurred.`
changing the roslyn packaing in the dependencies file to the new specific version nuget `Microsoft.CodeAnalysis.CSharp = 1.2.0-beta-20151106-02 prerelease` solved it
Not sure if this is the best way to do it..
=> Set specific version number for updated Roslyn nuget package

src/Marten.Testing/Linq/invoking_queryable_through_first_Tests.cs, src/Marten/Linq/DocumentQuery.cs, src/Marten/Linq/MartenQueryExecutor.cs
@jeremydmiller, A first stab at implementing #89 
I've made the first tests slightly harder to pass by checking the returned result has flag set but this may not be such a good move as we actually guarantee postgresql will return the results in insertion order (http://www.postgresql.org/docs/9.1/static/queries-order.html says results will come back in "unspecified order" if no sort is set). What do you think?
Last is a little trickier to push down. Either as you suggested in #87, we reverse the order but we can't do this if there's no user provided order. Or we can do the wrap the original query and skip the count of this subquery minus one but that's quite a big change to the query construction.
=> Optimize first

src/Marten.Testing/Linq/invoking_queryable_any_async_Tests.cs, src/Marten.Testing/Linq/invoking_queryable_count_async_Tests.cs, src/Marten.Testing/Linq/invoking_queryable_through_first_async_Tests.cs, src/Marten.Testing/Linq/invoking_queryable_through_last_async_Tests.cs, src/Marten.Testing/Linq/invoking_queryable_through_single_async_Tests.cs, src/Marten.Testing/Marten.Testing.csproj, src/Marten.Testing/SpecificationExtensions.cs, src/Marten/Linq/IMartenQueryExecutor.cs, src/Marten/Linq/IMartenQueryProvider.cs, src/Marten/Linq/MartenQueryExecutor.cs, src/Marten/Linq/MartenQueryProvider.cs, src/Marten/Util/QueryableExtensions.cs
Added async versions: Any, Count/LongCount, First/FirstOrDefault, Single/SingleOrDefault, Last/LastOrDefault.
Code of extensions was taken from EF7 [EntityFrameworkQueryableExtensions](https://github.com/aspnet/EntityFramework/blob/0b96c132f41442a10064156798d18d2526c3c0a7/src/EntityFramework.Core/EntityFrameworkQueryableExtensions.cs).
Is it a problem?
=> Add async methods

src/Marten.Testing/Fixtures/Target.cs, src/Marten.Testing/Marten.Testing.csproj, src/Marten.Testing/searchable_properties_Tests.cs, src/Marten/Schema/IndexDefinition.cs
@jeremydmiller this fixes the issue with multiple searchable properties with the Legacy schema update option.
Exception was being thrown when specifying multiple searchable properties:
> Result StackTrace:
at Npgsql.NpgsqlConnector.DoReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage, Boolean isPrependedMessage)
at Npgsql.NpgsqlConnector.ReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage)
at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
at Npgsql.NpgsqlCommand.ExecuteNonQueryInternal()
at Npgsql.NpgsqlCommand.ExecuteNonQuery()
at Marten.Services.CommandRunner.<>cDisplayClass6_0.<Execute>b0(NpgsqlConnection conn)
at Marten.Services.CommandRunner.ExecuteT
at Marten.Services.CommandRunner.Execute(String …
=> fixes issue with multiple searchable properties

src/Marten/DocumentSession.cs, src/Marten/Linq/MartenQueryExecutor.cs, src/Marten/Linq/MartenQueryProvider.cs, src/Marten/Linq/MartenQueryable.cs, src/Marten/QuerySession.cs, src/Marten/Services/CommandRunner.cs, src/Marten/Services/CommandRunnerExtensions.cs, src/Marten/Services/DirtyTrackingIdentityMap.cs, src/Marten/Services/IdentityMap.cs, src/Marten/Services/NulloIdentityMap.cs, src/Marten/Services/UnitOfWork.cs, src/Marten/Services/UpdateBatch.cs
* Reduces the amount of async statemachines created and therefore reduces the allocations and GC pressure
* Adds necessary `ConfigureAwait(false)
=> Reduced unnecessary `await` statements and added missing `ConfigureAwait(false)`

src/Marten.Testing/Marten.Testing.csproj, src/Marten.Testing/TrackingSession/document_session_update_existing_documents_in_collection_Tests.cs
Add's failing test for `DirtyTrackingIdentityMap` and `IdentityMap` for #117
=> Added failing test for collection change tracking

src/Marten/IMartenLogger.cs, src/Marten/Marten.csproj
This is in regards to https://github.com/JasperFx/marten/issues/148.
I'm proposing these two new, pluggable interfaces as a mechanism to basically listen for any kind of information at runtime. This would allow the request governor approach or performance metrics or just exceptions from the sql being executed.
*My* big wish from the diagnostics is being able to associate DB activity with semantic elements of the application like "what HTTP URL was this" or "what message was the service bus handling?"
=> Spike of what IMartenLogger might look like

src/Marten.Testing/Schema/configuring_searchable_fields_Tests.cs, src/Marten.Testing/TypeMappingsTests.cs, src/Marten/Util/TypeMappings.cs
Fixes issue #175 
Changed `DateTime` mapping to `timestamp without time zone` and removed manual override from the `Npgsql.TypeHandlerRegistry` which returns `Timestamp`
=> Change DateTime mapping to timestamp without time zone

src/Marten.Testing/Events/end_to_end_event_capture_and_fetching_the_stream_Tests.cs, src/Marten/Events/EventStore.cs, src/Marten/Events/IEventStore.cs
I needed the provide a known ID when calling StartStream. In some cases I generate the aggregate ID on the client.
=> Support StartStream with known ID

src/Marten.Testing/Services/DirtyTrackingIdentityMapTests.cs, src/Marten.Testing/Services/IdentityMapTests.cs, src/Marten.Testing/Using_DocumentSessionListener_Tests.cs, src/Marten/DocumentStore.cs, src/Marten/IDocumentSessionListener.cs, src/Marten/Services/DirtyTrackingIdentityMap.cs, src/Marten/Services/IdentityMap.cs
I added two methods to the IDocumentSessionListener to intercept when documents are loaded/stored.
void DocumentLoaded(object id, object document);
void DocumentAddedForStorage(object id, object document);
This interception is currently implemented in the default and DirtyChecking IdentityMap.
I was tempted to split the IDocumentSessionListener into a IDocumentSessionListener and IDocumentListener. The latter would contain the new methods. But I decided to go for the simplest implementation for now. Let me know what your thoughts are about this?
If you agree I can add this also to the documentation if you want.
=> Add document loaded/addedForStorage interception methods

src/Marten.Testing/Linq/query_with_aggregate_functions.cs, src/Marten.Testing/query_scalar_values_with_select_in_query_async.cs
Since the testing framework properly supports async tests we don't need to use `GetAwaiter().GetResult()`
=> Getting rid of GetAwaiter().GetResult() calls in tests by marking them async

src/Marten/IDocumentSessionListener.cs
This PR removes the `Task.Run` usage from `DocumentSessionListenerBase`. `DocumentSession` makes sure that the appropriate methods are called based on the sync or async path. No need to magically double dispatch and unnecessary task scheduling.
=> DocumentSessionListenerBase should not use Task.Run to dispatch sync methods

documentation/documentation/documents/async.md, documentation/documentation/documents/linq.md, documentation/documentation/documents/projections.md, src/Marten.Testing/Examples/LinqExamples.cs, src/Marten.Testing/Linq/invoking_query_with_select_Tests.cs, src/Marten.Testing/Linq/query_against_primitive_array_Tests.cs, src/Marten.Testing/Linq/query_for_sum_Tests.cs, src/Marten.Testing/Linq/query_with_aggregate_functions.cs
First batch for #278 
Added documentation for:
* Select() transforms (projections)
* Case insensitive searches by string
* string.Equals Linq searches.
* Contains() / Any() searches with IEnumerable, IList, List
* min/max/avg/sum operators in the Linq support
=> Documentation

documentation/documentation/documents/include.md, src/Marten.Testing/Services/Includes/end_to_end_query_with_include_Tests.cs
Hopefully I'll get 'overriding schema & doc names' done tomorrow.
=> added Include() documentation

src/Marten.Testing/Events/query_against_event_documents_Tests.cs, src/Marten.Testing/Schema/DocumentCleanerTests.cs, src/Marten/Schema/DocumentCleaner.cs
#333 
Also added tests in general for DeleteAllEventData()
=> DeleteAllEventData() with different schema name

src/Marten.Testing/Marten.Testing.csproj, src/Marten.Testing/bulk_loader_overwrite_sql_tests.cs, src/Marten.Testing/bulk_loading_Tests.cs, src/Marten/DocumentStore.cs, src/Marten/Schema/BulkLoading/BulkLoader.cs
Changed the SQL statement for updating the original table with the newly bulk inserted documents
Changed the order of execution for when using bulk insert in mode `OverwriteExisting`. First, all the duplicates are updated, after that the new documents are inserted .
Should fix #388
=> BulkInsert timeout bug

src/Marten.Testing/Events/Projections/inline_transformation_of_events.cs
The Each() extension method was being used with an async action.  Npgsql's "op already in progress message" was accurate.  Changed to a simple foreach and can no longer repro the exception.
=> Fixes test throwing InvalidOperationException: An operation is already in progress.

src/Marten.Testing/Schema/Hierarchies/end_to_end_document_hierarchy_usage_Tests.cs, src/Marten/Linq/WhereClauseVisitor.cs
If you'd rather this work with session.DeleteWhere<SuperUser>() or session.Delete<SuperUser>(), I can implement it; I thought though it'd be better to be more explicit about deleting all documents of a certain type...
=> added support to delete where true

src/Marten.Testing/Acceptance/computed_indexes.cs, src/Marten/MartenRegistry.cs, src/Marten/Schema/ComputedIndex.cs
This is my first cut at supporting some arguments on the `.Index` 
Notes:
- Cannot add unit test for Concurrent index as concurrent only exists for the creation of the index. It's not concurrent after the creation. 
- Named index's will be pre-fixed with `mt_` to ensure that we can pull them from the database as 'marten related indexes' and not adhoc indexes put into the system outside of marten.
- Where clauses take a string, they work but its a bit fiddly. 
I also made `Duplicate` arguments optional.
=> Support for configuration on .Index(...)

src/Marten/Schema/DocumentSchemaObjects.cs
Added default value to the `mt_version` column. 
`default(md5(random()::text || clock_timestamp()::text)::uuid)`
I setup the guid this way because it seems you need an extension to do it without, so to avoid Marten having a dependency on an extension I went with the recommended approach from http://stackoverflow.com/a/21327318/456813
I couldn't find any corresponding unit tests and wasn't sure how to add a test for this.
=> Added default value when adding the version column

src/Marten.Testing/Events/Projections/AggregatorTests.cs, src/Marten/Events/AggregationQueryHandler.cs, src/Marten/Events/Event.cs, src/Marten/Events/EventGraph.cs, src/Marten/Events/EventStore.cs, src/Marten/Events/IEventStoreConfiguration.cs, src/Marten/Events/Projections/AggregationProjection.cs, src/Marten/Events/Projections/Aggregator.cs, src/Marten/Events/Projections/IAggregator.cs, src/Marten/QuerySession.cs, src/Marten/Services/BatchQuerying/BatchedQuery.cs
This update makes the event Aggregator fully pluggable. This was not possible because the implementation was used instead of the interface in many places. 
I use it to support a different way to build aggregates. (See https://gist.github.com/tim-cools/694ba34dbb93b7a0cdf710886aa29275)
=> Support custom aggregator

src/Marten.Testing/Acceptance/computed_indexes.cs, src/Marten/Schema/ComputedIndex.cs, src/Marten/Schema/IndexDefinition.cs
Added brin to the index method list now that we support 9.5+
Set the index type if set to anything other than btree. 
I suspect we will have to a lot of re-working around index types require the index definitions to be different in certain scenarios. Hopefully people will use this as a starting point so we can get a list of indexes people are trying to create and use that to figure out how best to abstract it out.
=> Add index method to Computed Index

documentation/documentation/documents/advanced/patch_api.md, javascript/mt_patching.js, src/Marten.Testing/Acceptance/patching_api.cs, src/Marten.Testing/Patching/PatchExpressionTests.cs, src/Marten/Marten.csproj, src/Marten/Patching/IPatchExpression.cs, src/Marten/Patching/PatchExpression.cs, src/Marten/Patching/RemoveAction.cs, test/test_mt_patching.js
Equality on complex child collections compares all fields, could possibly inspect for identity field as an optimisation.
=> Add remove from collection patch

documentation/documentation/documents/basics/persisting.md, documentation/documentation/documents/identity/index.md
> When using a `Guid`/`CombGuid`, `Int`, or `Long` identifier, Marten will ensure the identity is set immediately after calling `IDocumentSession.Store` on the entity.
- Updated Identity page
- Updated Basics/Persisting page
Let me know if you'd like the wording changed.
=> Clarify when ID is set when persisting documents

src/Marten.Testing/Events/query_against_event_documents_Tests.cs, src/Marten/Events/EventStore.cs, src/Marten/Events/EventsQueryHandler.cs, src/Marten/Events/IEventStore.cs, src/Marten/Marten.csproj
This should allow users to retrieve **all** events regardless
of event type. They also have the option of using `before` and
`after` datetimes which allow for event windows. Finally, they
can still use versions to retrieve versioned events.
=> FetchAll added to EventStore

src/Marten.Testing/Events/query_against_event_documents_Tests.cs, src/Marten/Events/EventsQueryHandler.cs
Previous behavior used `before` parameter name with throwing an exception for the `after` parameter.
Also, remove trailing whitespace from related test.
=> Update EventsQueryHandler exception parameter naming

src/Marten.Testing/Linq/dictionary_is_translated.cs, src/Marten.Testing/Linq/query_for_json_format.cs, src/Marten.Testing/Target.cs, src/Marten/Linq/MartenExpressionParser.cs, src/Marten/Linq/Parsing/DictionaryExpressions.cs, src/Marten/Linq/WhereFragment.cs, src/Marten/Util/TypeMappings.cs
Addresses #459 
There are some dramatic changes in this.
Applying fixes for the `IDictionary<,>.ContainsKey('tkey)` and `ICollection<KVP<,>>.Contains(KVP<,>)` cases was easy enough because those fit into the existing method-call based plugin architecture. There was a wrinkle in that the operator that I want to use in postgres is `?`, which is already used by the `WhereFragment` expansion, so I also took the opportunity to make a version of WhereFragment that has a configurable separator.
The drastic thing was adding in a pluggable `IBinaryExpressionParser` interface.  This was required so that I could easily get at cases where we're indexing into a dictionary on the right or left sides to pull out the keys and values to construct the comparison dictionary.  As you'd expect a ton of things …
=> Address Dictionary query generation

src/Marten/Events/Projections/Async/EventPage.cs, src/Marten/Events/Projections/Async/Fetcher.cs
- Fetcher assigns EventTypeNames property
- Removed unnecessary awaits
- Fixed continuation bug for logger which would run when proxy is completed
`Task.Factory.StartNew `with an async lambda will return a proxy task of type `Task<Task>`. This means the continuation would run immediately since the proxy task is completed before the inner task is completed. The simplest solution in the case we have here is to use `Task.Run` since the long-running flag is more harmful than helpful with async lambdas. 
http://blog.i3arnon.com/2015/07/02/task-run-long-running/
I decided to hint the scheduler that the continuation can run synchronously (on the transition of the antecedent task to completed, reusing the worker thread) since I think for logging we don't need to reschedule a task. Thoughts?
=> Small fixes for Fetcher

src/Marten/Events/Projections/Async/Daemon.cs
By moving the sql statement closer to the command definition you capture in the closure only the `this` reference (which can be optimized) and therefore you opt-in for better delegate caching and less allocation (save additional display class generation)
=> Moving sql closer to usage to avoid closure capturing

src/Marten.Testing/Acceptance/patching_api.cs, src/Marten.Testing/Events/query_against_event_documents_Tests.cs, src/Marten/Events/EventsQueryHandler.cs
Tests can_fetch_all_events_after_now and can_fetch_all_events_before_now were repeatedly failing running in BST timezone.
The Column `mt_events.timestamp` is defined as `timestamp without time zone` and is always populated with insertion time taken from the UTC time zone. Also EventsQueryHandler enforces that the DateTime given for either `before` or `after` parameters must have `DateTimeKind` of UTC.
However, the parameters for the query were prepared as `NpgsqlDbType.TimestampTZ` which causes Postgres to adjust the given value appropriate to the server's time zone.
=> Fix event stream fetchall with before|after

documentation/documentation/events/projections/index.md, src/Marten.Testing/Events/Projections/WeaponNamesByQuest.cs
As promised, here's an example of `ViewProjection<T>` for aggregating across streams. cc @tim-cools
=> Adds an example of using ViewProjection<T>

src/Marten.Testing/MartenRegistryTests.cs, src/Marten.Testing/Schema/IndexDefinitionTests.cs, src/Marten.Testing/Schema/configuring_searchable_fields_Tests.cs, src/Marten/Schema/ComputedIndex.cs, src/Marten/Schema/IndexDefinition.cs
In case anyone was already working around this defect will not append prefix to prefixed names, e.g. will not generate mt_mt_my_index
=> Ensure Index Names are always prefixed

src/Marten/Schema/DbObjects.cs
`information_schema.tables` requires that any accessor has SELECT permissions to view its contents. `pg_stat_user_tables` does not. This problem surfaced when attempting to remove SELECT permissions from the `mt_hilo` table.
=> SELECT access no longer required on database tables.

src/Marten.Testing/Schema/add_origin_Tests.cs, src/Marten/Generation/OriginWriter.cs, src/Marten/Generation/TableDefinition.cs
Record Marten related metadata in PG object comments - first for tables created (so I can e.g. 
```
SELECT relname, description from pg_description
join pg_class on pg_description.objoid = pg_class.oid
where description like 'origin:Marten.IDocumentStore, Marten, Version=1.0.0.51046%'
```
=> Use PG object comments to record metadata (IDocumentStore FQN)

src/Marten.Testing/Linq/query_with_intersect.cs, src/Marten/Linq/CollectionAnyContainmentWhereFragment.cs
This PR adds basic intersection support to Arrays/Lists that serialize to a "array of strings" representation in JSON (this is a limitation/requirement of the `?|` jsonb-operator). As of now only `string` and `Guid` lists/arrays are supported, other types are not tested and yield a `NotSupportedException`.
This PR should provide functionality for a quite common use case for a document store: Suppose you have a document with a collection of "tags":
`public class Article {
public string[] Tags { get; set }
}`
and you want to query all documents that have one or more "tags" in common with your "interest": `var interests = new string[] { "finance", "astrology" };`
You can now do the following:
`theSession.Query<Article>()
.Where(x => x.Tags.Any(s => interests.Contains(s)))
`
This is …
=> Add basic intersection support via the ?| jsonb operator

src/Marten.Testing/AsyncDaemon/AsyncDaemonFixture.cs, src/Marten/Events/Projections/Async/Fetcher.cs, src/Marten/Schema/SQL/mt_stream.sql
I had problems running the AsyncDaemonFixture derived tests, eventually tracked it down to two issues.
First when comparing `timestamp timestamptz` on `mt_events` in the `Fetcher` the `transaction_timestamp` was being coerced to 'UTC' but the stored values were local (e.g. `now()`) which meant no events were being found to be due causing no projections to be built.
Second was that the code to load the project json files was not finding the correct directory, looks like it was based on the previous test runner setting working dir to bin\Debug. Most of the tests passed asserting that 0 == 0!
All tests now passing on my environment (UTC+1)
The schema checks look like they only check for the table existence so existing event stores will not be modified to use the new version of the table …
=> Fix stream time zone issue

src/Marten.Testing/StoreOptionsTests.cs, src/Marten/PostgresqlIdentifierInvalidException.cs, src/Marten/PostgresqlIdentifierTooLongException.cs, src/Marten/StoreOptions.cs
Length check changed to accept less than NameDataLength.
Added check for any spaces in strings, no identifiers are quoted in generated sql.
Added check for whitespace strings, for instance `IndexDefinition` and `ComputedIndex` both verify null or empty but do not verify an index name given as all whitespace (who does that!)
=> Identifier checks for null, empty, whitespace, embedded space

src/Marten.Testing/Schema/Identity/Sequences/CombGuidIdGenerationTests.cs, src/Marten/Schema/Identity/CombGuidIdGeneration.cs
Big endian should be a straight copy of the 48 bits of the timestamp we care about.
=> #579 - Fix for big endian.

src/Marten.Testing/Linq/query_with_inheritance.cs, src/Marten/Schema/Hierarchies/SubClassDocumentStorage.cs, src/Marten/Schema/SubClassMapping.cs
If an `IPapaSmurf` is queried, `SubClassDocumentStorage` would try to deserialize to objects of type `IPapaSmurf` instead of the actual types.
This bug was not triggered by the ST test case in the documentation because `.Count()` does not actually instantiate the classes.
The attached commits borrows the type resolving from `HierarchicalResolver` by delegating to `SubClassMapping`.  (I've seen the TODOs in `SubClassDocumentStorage.cs` but that's a larger architectural change that's currently beyond my abilities in the Marten codebase :) )
Note: A plethora of tests fails on my local machine mainly due to (appearently) broken PLV8 extension on my dev machine. I could therefore not reliably confirm that the change breaks no other tests.
=> Bug in subinterface query

src/Marten.Testing/Acceptance/last_modified_queries.cs, src/Marten.Testing/MartenRegistryTests.cs, src/Marten.Testing/Schema/configuring_last_modified_index_Tests.cs, src/Marten/Linq/LastModified/LastModifiedExtensions.cs, src/Marten/Linq/LastModified/ModifiedBeforeParser.cs, src/Marten/Linq/LastModified/ModifiedSinceParser.cs, src/Marten/Linq/MartenExpressionParser.cs, src/Marten/MartenRegistry.cs, src/Marten/Schema/DocumentMapping.cs, src/Marten/Schema/IndexedLastModifiedAttribute.cs
Enable the use of the built in `mt_last_modified` column without dropping to raw queries.
Also adds mapping/registry/attribute option to configure index on the storage column.
=> Last modified extensions

src/Marten.Testing/Linq/invoking_query_with_select_Tests.cs, src/Marten.Testing/Services/SelectTransformerTests.cs, src/Marten/Linq/SelectorParser.cs, src/Marten/Linq/TargetObject.cs
Adds support for type constructors with parameters in Select.
This obviously also requires support from your serializer, Newtonsoft.Json is ok but JIL for instance does not support, but at least the `json_build_object()` call is generated correctly irrespective of whether the user has specified field selectors as constructor arguments or property setters.
=> Support Parameterized Constructors in Select projections

src/Marten/Events/EventStreamAppender.cs, src/Marten/Services/SprocCall.cs, src/Marten/Services/UpdateBatch.cs
Events are appended using `ArraySegment<char>` from a pooled writer when `UseCharBufferPooling` is enabled.
This will work as soon as https://github.com/npgsql/npgsql/pull/1411 is released in [npgsql 3.2](https://github.com/npgsql/npgsql/milestone/24)
=> [WIP] Buffer pooling for appending events.

src/Marten.Testing/Services/CharArrayTextWriterTests.cs, src/Marten/DocumentStore.cs, src/Marten/Schema/Arguments/CurrentVersionArgument.cs, src/Marten/Schema/Arguments/DocJsonBodyArgument.cs, src/Marten/Schema/Arguments/DocTypeArgument.cs, src/Marten/Schema/Arguments/DotNetTypeArgument.cs, src/Marten/Schema/Arguments/UpsertArgument.cs, src/Marten/Schema/Arguments/VersionArgument.cs, src/Marten/Schema/BulkLoading/BulkLoader.cs, src/Marten/Schema/BulkLoading/IBulkLoader.cs, src/Marten/Services/CharArrayTextWriter.cs
Bulk inserts now use `ArraySegment<char>` from a pooled writer when `UseCharBufferPooling` is enabled.
This will work as soon as https://github.com/npgsql/npgsql/pull/1411 is released in [npgsql 3.2](https://github.com/npgsql/npgsql/milestone/24)
=> [WIP] Buffer pooling for bulk inserts

documentation/documentation/postgres/if_statements.md
Just a fix for a small issue with `LANGUAGE` sample not being correctly formatted in markdown.
=> Fix a LANGUAGE sample formatting

src/Marten.Testing/Services/CharArrayTextWriterTests.cs, src/Marten/Services/CharArrayTextWriter.cs
Solves #680 
This PR fixes a bug in resizing `CharArrayTextWriter`. Previously, when big enough `string` was written the size was not adjusted properly (no enlarged to the required size).
=> CharArrayTextWriter adjusts size properly

src/Marten.CommandLine/Commands/ApplyCommand.cs, src/Marten.CommandLine/Commands/AssertCommand.cs, src/Marten.CommandLine/Commands/Dump/DumpCommand.cs, src/Marten.CommandLine/Commands/Dump/DumpInput.cs, src/Marten.CommandLine/Commands/Patch/PatchCommand.cs, src/Marten.CommandLine/Commands/Patch/PatchInput.cs, src/Marten.CommandLine/Commands/Projection/ProjectionCommand.cs, src/Marten.CommandLine/Commands/Projection/ProjectionInput.cs, src/Marten.CommandLine/Commands/RunDaemon.cs, src/Marten.CommandLine/project.json
I've re-organized files layout to make it more readable, hope it's ok
this change introduces two new commands, 
* projection inline|async - which rebuilds either inline or async projections
* rundaemon which runs the async projection daemon
to be honest, I'm not fully convinced to using Daemon for rebuilding inline projections. It's very tempting because all the paging etc is already there, and therefore I've used it, at least for now.
On the other hand, I'm afraid of possible side effects, the tracking information being stored for inline projections - to name one. 
Maybe it'd be better to use Daemon (ProjectionTracks, in fact) in "no-tracking" mode, or even better - extract the paged fetching/applying out of the ProjectionTrack ?
=> GH-516 initial projection rebuild and async daemon running in Marten.CommandLine

src/Marten/Events/EventStore.cs
For #687 and #681, there are several methods in `EventStore` that doesnt verify that the eventstore tables exists before they use them. This should hopefully catch them all.
=> Ensure event storage exists for all public methods in eventstore.

src/Marten.Testing/Linq/query_with_select_many.cs, src/Marten/Linq/QueryHandlers/CountQueryHandler.cs
Count used in combination with an aggregate function, e.g. when used in conjunction with `SelectMany`, will throw when no rows matched or when all collections are null.
Implemented a guard in `CountQueryHandler<T>`.
=> Fix issue with count throwing when no result value

documentation/documentation/events/projections/index.md
Follows on from the question I asked last night in the Gitter room.  Turns out I missed the segment in the docs about customising aggregation using `IAggregatorLookup`.
This just adds an anchor reference to the AggregatorLookup section in the same page, shortly after describing projection.
=> docs: add note about projection customisation

documentation/documentation/documents/advanced/patch_api.md, javascript/mt_patching.js, src/Marten.Testing/Acceptance/patching_api.cs, src/Marten.Testing/Patching/PatchExpressionTests.cs, src/Marten/Patching/IPatchExpression.cs, src/Marten/Patching/PatchExpression.cs, test/test_mt_patching.js
Resolves issue #629 
Add two new methods and associated JS functions
AppendIfNotExists
InsertIfNotExists
The premise behind both methods is to only apply the patch if the
element within the collection does not already exist.
In order to check for complex types, JSON.stringify is used, which does
mean the order of elements is important. Assume this is OK for now.
=> Add AppendIfNotExists and InsertIfNotExists to patching API

src/Marten/project.json
Related to #722 
Fix warning :
Detected package downgrade: System.Data.Common from 4.3.0 to 4.1.0
Marten (>= 1.5.0) -> Npgsql (>= 3.2.2) -> System.Data.Common (>= 4.3.0)
Marten (>= 1.5.0) -> System.Data.Common (>= 4.1.0)
=> Fix : Detected package downgrade: System.Data.Common from 4.3.0 to 4.1.0

README.md
To limit your ad nauseam explanations of Rake and Ruby. Reference: https://github.com/JasperFx/marten/issues/522#issuecomment-302722308
=> Remove the word temporary from README tooling

src/Marten.Testing/Acceptance/using_natural_identity_keys.cs, src/Marten.Testing/document_types_must_have_an_id_member_Tests.cs, src/Marten/DocumentStore.cs, src/Marten/Schema/DocumentMapping.cs, src/Marten/StoreOptions.cs
Currently the IdMember is validated when the initial DocumentMapping is retrieved, but this means that the there has to be an existing IdMember before one can be added via the Fluent interface.   The idea behind the fix here is to delay validating the mappings until the DocumentStore is constructed.  I'm not sure if any other checks could or should be moved here. 
If there's any other part of configuration that would depend on IdMember not being null it would throw a null exception now, but nothing came up in the tests.  Conceptually, I was thinking that constructing the store is the gate after which everything should be configured.
=> delay document mapping validation until store construction - fixes #743

src/Marten.Testing/Bugs/Bug_772_index_wrapping_column_does_not_match_DDL.cs, src/Marten.Testing/ConnectionSource.cs, src/Marten/Schema/IndexDefinition.cs
See #772 
I wasn't able to universally match DDL from the database with DDL generated by code, but I was able to change the Match method on IndexDefinition to return a positive match if the Expression property is added in such a way as to minimize/eliminate reformatting by Postgres. This PR handles my use case, and I believe others, as long as Expression values are set appropriately.
I also corrected the error message in the testing ConnectionSource, since the environment variable in the exception message and the actual environment variable were different.
=> #772 Index with Expression Should Match DDL (1.5 patch)

appveyor.yml
- Changed version config entry to format "Build [version]" since it is not used anywhere else other than CI build label
- Removed assembly_info patching config since the rake script takes care of it
=> Cleanup unused Appveyor config items

documentation/documentation/events/appending.md, documentation/documentation/events/identity.md, documentation/documentation/events/index.md, documentation/documentation/events/order.txt, documentation/documentation/events/schema.md, documentation/documentation/events/streams.md, src/Marten.Testing/Events/event_store_with_string_identifiers_for_stream.cs, src/Marten/Events/EventStore.cs
Document new table columns in event store schema.
Fix typo in exception message.
Fix typo in docs.
=> Docs for event store stream identity.

documentation/getting_started.md, src/Marten.Testing/Schema/create_database_Tests.cs, src/Marten/Schema/DatabaseGenerator.cs, src/Marten/Schema/IDatabaseCreationExpressions.cs, src/Marten/Schema/ITenantDatabaseCreationExpressions.cs, src/Marten/StoreOptions.cs
If no maintenance db is specified, default to 'postgres' (PG connection is always made against a db), which is a reasonable default.
=> Docs on db creation.

src/Marten.Testing/Marten.Testing.csproj, src/Marten/Events/EventQueryHandler.cs, src/Marten/Events/EventStore.cs, src/Marten/Events/IEventStore.cs, src/Marten/Events/Projections/Async/EventPage.cs, src/Marten/Events/Projections/Async/Fetcher.cs, src/Marten/Events/Projections/ViewProjection.cs, src/Marten/IDocumentSession.cs, src/Marten/IQuerySession.cs, src/Marten/Linq/IMartenQueryable.cs, src/Marten/Linq/ISelector.cs, src/Marten/Linq/MartenQueryable.cs, src/Marten/Linq/Model/LinqQuery.cs, src/Marten/Linq/QueryHandlers/EnumerableQueryHandler.cs, src/Marten/Linq/QueryHandlers/ListQueryHandler.cs, src/Marten/Linq/QueryHandlers/UserSuppliedQueryHandler.cs, src/Marten/QuerySession.cs, src/Marten/QueryableExtensions.cs, src/Marten/Services/BatchQuerying/BatchedQuery.cs, src/Marten/Services/BatchQuerying/BatchedQueryable.cs, src/Marten/Services/BatchQuerying/IBatchedFetcher.cs, src/Marten/Services/BatchQuerying/IBatchedQuery.cs, src/Marten/Services/BatchQuerying/TransformedBatchQueryable.cs, src/Marten/Services/CommandRunnerExtensions.cs, src/Marten/Services/IManagedConnection.cs
Converts all `IList<T>` return types to `IReadOnlyList<T>` thereby dropping the inappropriate methods from the former's interface.
=> Convert public api to IReadOnlyList<T>

src/Marten.Testing/Linq/using_const_boolean_in_where_clause_Tests.cs, src/Marten/Linq/WhereClauseVisitor.cs
I don't really know what I'm doing :)
I did a quick analysis of the behavior and fixed what seemed to be the problem in my case. I'm not however sure I completely understand the original idea, so I can't tell if the previous implementation was a mistake or had some purpose to behave like it did.
I ran all the tests, some of them failed but they did failed on the latest origin sources as well, so I suppose these are not because of my change. More likely the lack of v8 language and some system encoding problems, I can't investigate it right now
=> fixed WhereClauseVisitor to handle constant booleans. Fixes #821

src/Marten.Testing/Session/query_session_Tests.cs, src/Marten/DocumentStore.cs
Ensure serializable query session is also read only.
Ensure query session respects command timeout & isolation from session options.
Unit tests to exercise expected behavior.
=> Fixing #831

src/Marten.Testing/Linq/query_with_multiple_where_clauses_and_soft_deletes_configured.cs
First test fails (with soft deletes configured). 
Second test passes (exact same code but without soft deletes configured).
=> failing test demonstrating GH-844

src/Marten.Testing/Bugs/Bug_337_certain_boolean_searches_are_not_using_searchable_field.cs, src/Marten.Testing/Bugs/Bug_849_not_node_not_correctly_evaluated.cs, src/Marten.Testing/Linq/IsNullNotNullArbitraryDepthTests.cs, src/Marten.Testing/Linq/SimpleNotEqualsParserTests.cs, src/Marten/Linq/Compiled/CompiledQueryMemberExpressionVisitor.cs, src/Marten/Linq/MartenExpressionParser.cs, src/Marten/Linq/NotVisitor.cs, src/Marten/Linq/Parsing/SimpleEqualsParser.cs, src/Marten/Linq/Parsing/SimpleNotEqualsParser.cs, src/Marten/Util/TypeMappings.cs
Changes:
* Parameterize NOT Equals (Value = False -> Value <> :arg, :arg = True). This aligns it with implementation of translation of equality & allows generalized implementation of !Equals.
* Align compiled query compilation with the change.
* Introduce !Equals for int, long, decimal, Guid, bool, DateTime, DateTimeOffset.
* Treat unknown PG types as jsonb. This allows null & not null checks at arbitrary depths (whereby current implementation fails on CAST).
* Fix bug #849 whereby ! == is incorrectly translated.
=> !Equals, null check depth improvements, fix #849

documentation/documentation/documents/querying/sql.md, src/Marten.Testing/Session/query_session_extension_Tests.cs, src/Marten.Testing/query_by_sql_where_clause_Tests.cs, src/Marten/QuerySessionExtensions.cs
* Fix missing query SQL async sample in docs.
* Fix #836 - adds extension methods to IQuerySession to provide non-generic Query overloads.
* Document said feature.
=> Fix missing sample in docs, Add non-generic Query extensions, Docs

src/Marten.Testing/Events/Projections/custom_async_transformation_of_events.cs, src/Marten/Events/Projections/ViewProjection.cs, src/Marten/Util/NoSynchronizationContextScope.cs
Currently ViewProjection even though it has `async Task IProjection.ApplyAsync(IDocumentSession session, EventPage page, CancellationToken token)` method it's not doing any async code there - it doesn't await for applyProjections so it's not possible to use async code in the persisting event projection method.
I know that there is AsyncDaemon, that helps with some of the async cases, but it's complext in usage and sometimes there is a need to use the code that has only async API (like in my commercial project, most of the code doesn't support synchronous access). Imho it would be good from the performance  and consistency perspective to allow to use async code in the `ProjectEvent` persist method.
In my PR, I changed the `Handler` definition to always return Task. For the non async code …
=> Add proper handling of async in ApplyAsync method for ViewProjection

src/Marten.Testing/Bugs/Bug_837_missing_func_mt_immutable_timestamp_when_initializing_with_new_Schema.cs, src/Marten/Schema/JsonLocatorField.cs, src/Marten/Storage/StorageFeatures.cs, src/Marten/Storage/SystemFunctions.cs
Bug fixes pertaining to GH-837 and GH-864
1. Revert incorrect fix done earlier pertaining to GH-837
2. Fix storage logic to tweak the timing of use for db schema name
- Moved the logic of adding mt_immutable_timestamp from SystemFunction constructor to StorageFeature.PostProcessConfiguration
- Moved few initialization code from StorageFeature constructor into PostProcessConfiguration
3. Added an additional test for default db schema for 837.
=> Bug fixes pertaining to GH-837 and GH-864

src/Marten.Testing/Bugs/Bug_432_querying_with_UTC_times_with_offset.cs, src/Marten.Testing/Linq/query_beginning_with_constant_Tests.cs, src/Marten.Testing/Linq/query_with_modulo_Tests.cs, src/Marten/Linq/MartenExpressionParser.cs
Found an issue with operand ordering.
For example if you had 
```csharp
x => x.ValidFrom < now && now < x.ValidTo
```
as your query clause the generated SQL would be
```sql
where (public.mt_immutable_timestamp(d.data ->> 'ValidFrom') < $1)
and (public.mt_immutable_timestamp(d.data ->> 'ValidTo') < $2)
```
which would yield entirely incorrect results.
Simply reversing the operands in the second clause yields the correct results.
```csharp
x => x.ValidFrom < now && x.ValidTo > now
```
```sql
where (public.mt_immutable_timestamp(d.data ->> 'ValidFrom') < $1)
and (public.mt_immutable_timestamp(d.data ->> 'ValidTo') > $2)
```
Corrected some tests that were relying on the behaviour.
=> Bug fix for query operand ordering

src/Marten.Testing/Linq/Compiled/compiled_query_Tests.cs, src/Marten/Linq/Compiled/CompiledQueryMemberExpressionVisitor.cs
In the marten [docs for compiled queries](http://jasperfx.github.io/marten/documentation/documents/querying/compiled_queries/) it states that properties and fields can be used in the query filter.  This currently works fine for properties but when a field is used this exception is raised:
```
Exception has occurred: CLR/System.InvalidCastException
An unhandled exception of type 'System.InvalidCastException' occurred in Marten.dll: 'Unable to cast object of type 'System.Reflection.RtFieldInfo' to type 'System.Reflection.PropertyInfo'.'
at Marten.Linq.Compiled.CompiledQueryMemberExpressionVisitor.VisitMember(MemberExpression node)
```
This is because the CompiledQueryMemberExpressionVisitor is expecting only properties. This PR adds support for fields as well as properties. I believe this …
=> Compiled Queries - Adds support for fields in query filters

src/Marten.Testing/Bugs/SubClassForeignKeyBugs.cs, src/Marten/Services/UnitOfWork.cs
Comment copied from #877:
I've spotted an issue when an entity has a ForeignKey setup to an entity that defines SubClasses.  It's equally possible I am doing something wrong!
e.g.
Given this setup...
```
public class Person
{
public int Id { get; set; }
}
public class Employee : Person
{
}
public class Address
{
public int Id { get; set; }
public int ParentId { get; set; }
}
// STORE OPTIONS
_.Schema.For<Person>()
.AddSubClass<Employee>();
_.Schema.For<Address>()
.ForeignKey<Person>(c => c.ParentId);
```
When executing this code....
```
using (var session = theStore.OpenSession())
{
// Creating an employee with an address - the employee object should be
// inserted *before* the address object.
var employee = new Employee {Id = 222};
session.Store(employee);
var address = new Address …
```
=> Test and possible fix for FK and sub-classes exception #877

src/Marten.Testing/Documents/InvalidDocument.cs, src/Marten.Testing/Storage/DocumentTableTester.cs, src/Marten/Storage/DocumentTable.cs
- Add logic to validate document to ensure identity field exists in the document table constructor before storage. This will throw an appropriate InvalidDocument exception rather than a cryptic ArgumentNullException
=> Add a step to validate document for identity field before storage

src/Marten/Services/TransactionState.cs
if a LambdaConnectionFactory passes in an open connection then there is no need to re-open
=> respect Open Connection

src/Marten.Testing/ConnectionSource.cs, src/Marten/Schema/DbObjects.cs, src/Marten/Schema/SchemaObjects.sql
When schema is created under a context other than a user, Marten
assertion fails.
- Change assertion querying from utilizing `pg_user` to instead `pg_roles`
Resolves Issue #796
=> Search Schema by Role not User (Marten 1.5)

src/Marten.Testing/Events/Projections/Async/MultidocumentProjectionTests.cs, src/Marten/Events/Projections/Async/ProjectionTrack.cs, src/Marten/Events/Projections/IDocumentProjection.cs, src/Marten/Events/Projections/IDocumentsProjection.cs, src/Marten/Events/Projections/IProjection.cs
This change makes it possible for the Async Daemon to handle projections which are managing several document types (read models). 
An example use case included in tests
=> Multi document type projection

documentation/splash.htm
Javascript => JavaScript, .Net => .NET, Nuget => NuGet, Postgresql => PostgreSQL.
=> Fix casing of various words

documentation/documentation/events/projections/index.md
Documentation says "not available duing the execution of inline projections". Instead use "asynchronous or inline projections". I assume is should be: "asynchronous or live projections"
=> Fix inconsistency in projection documentaiton

src/Marten/Events/Projections/AggregateFinder.cs, src/Marten/Events/Projections/AggregationStep.cs, src/Marten/Events/Projections/EventAggregationStep.cs, src/Marten/Events/Projections/StringIdentifiedAggregateFinder.cs, src/Marten/Linq/QueryHandlers/CompiledInclude/IIncludeCallbackResolver.cs, src/Marten/Marten.csproj, src/Marten/Schema/BulkLoading/BulkLoader.cs, src/Marten/Schema/Resolver.cs, src/Marten/Util/FastExpressionCompiler.cs, src/Marten/Util/LambdaBuilder.cs
Adds FastExpressionCompiler as source instead of taking it as a dependency.
I have used the exact same version of FastExpressionCompiler here as you are using in StructureMap. The reason for this is quite frankly that I cant figure out which revision of FastExpressionCompiler in its main repo is the "latest" one that still works properly together with Marten. If you or anyone else want to try to figure that out then feel free to do so, but I figured that StructureMap is so widely used that it's probably safe to use the same version. :)
=> Fix for #921 / Add internal FastExpressionCompiler.

src/Marten/Events/Projections/AggregateFinder.cs, src/Marten/Events/Projections/AggregationStep.cs, src/Marten/Events/Projections/EventAggregationStep.cs, src/Marten/Events/Projections/StringIdentifiedAggregateFinder.cs, src/Marten/Events/Projections/ViewProjection.cs, src/Marten/Linq/QueryHandlers/CompiledInclude/IIncludeCallbackResolver.cs, src/Marten/Marten.csproj, src/Marten/Schema/BulkLoading/BulkLoader.cs, src/Marten/Schema/Resolver.cs, src/Marten/Util/FastExpressionCompiler.cs, src/Marten/Util/LambdaBuilder.cs
This PR looks a bit funny because it's on top of the FastExpressionCompiler PR. The only additional changes in this PR compared to that one is in ViewProjection.cs
Currently ViewProjection does hard casting to DocumentSession. This PR fixes this so that it instead casts to IQuerySession which is nicer if you want to inject a fake IDocumentSession into a projection for testing purposes.
=> Remove hard dependency on DocumentSession from ViewProjection

documentation/documentation/events/projections/custom.md, src/Marten.Testing/Events/Projections/lazy_loaded_projection.cs, src/Marten/Events/Projections/LazyLoadedProjection.cs, src/Marten/Events/Projections/ProjectionCollection.cs
Currently it's impossible to inject classes to Projection. Although I understand that it's not be the indented usage, to use other classes in event handler, from pragmatic point it's sometimes needed (at least in my usage scenarios). Imho it would be nice to have possibility to add Projection that is not created immediately, but when the projection is being applied.
Added new method to [ProjectionCollection](https://github.com/JasperFx/marten/tree/master/src/Marten/Events/Projections/ProjectionCollection.cs) class:
```
public void Add<T>(Func<T> projectionFactory) where T : IProjection, new()
```
it allows to pass factory method for the projection. Having that it can be even reused to allow Dependency Injection eg. 
```
public static void Add<TProjection>(this ProjectionCollection …
```
=> Add possibility to inject classes to projection

src/Marten.Testing/Events/Projections/Async/MultidocumentProjectionTests.cs, src/Marten/Events/Projections/LazyLoadedProjection.cs
before this change, the async daemon is not able to clear the storage before replaying all events.
it looks for storage table for the projection itself, not taking into consideration that the projection might not be an aggregate one. 
note: the test included proves it to some point only. 
before the change (when the LazyLoadedProjection didn't implemented `IDocumentsProjection`), the test runned forever instead of failing.
There seem to be some other issue making the `Daemon.RebuildAll` Task to never complete (instead of fail) when there's an exception in `DocumentMapping.Validate`. But this is kind of an async hell so I didn't manage to dig into it. the only way you can tell there was a problem is by intercepting async daemon messages (there'll be a message with a validation exception)
=> make LazyLoadedProjection play nicer with async daemon

documentation/documentation/documents/configuration/unique.md, src/Marten.Testing/Acceptance/unique_indexes.cs, src/Marten.Testing/Examples/MartenRegistryExamples.cs, src/Marten.Testing/Schema/UniqueIndexTests.cs, src/Marten/MartenRegistry.cs, src/Marten/Schema/DocumentMapping.cs, src/Marten/Schema/UniqueIndexType.cs, src/Marten/UniqueIndexAttribute.cs
Currently there is no documentation for setting up unique indexes.
Added:
- Documentation for unique indexes
- Created samples of unique indexes definition
- Added `UniqueIndexType` enum to make Unique Index api more descriptive. After rethinking I didn't like `bool` parameter, that I initially introduced - it's too enigmatic... So having the chance to make it better before offical `2.8.0` release - I changed that.
[x] New feature (non-breaking change)
=> #1003 - Add documentation for unique indexes

src/Marten/Events/EventSelector.cs
Added better error handling for cases where an event type cannot be found to match what types are currently in the database.
Fixes #1007
=> Issue 1007 - Unclear Exception when EventType not recognized.

src/Marten.Testing/Marten.Testing.csproj, src/Marten/Linq/Parsing/StringContains.cs
This is the best we could come up with for a fix for this.  Reflection will have to try to get the overloads for `String.Contains` at runtime, and what it gets will vary depending on whether its running on 2.0 or 2.1.
=> Fix for netcore 2.1 Linq support

src/Marten/Events/EventMapping.cs
Few minor changes to EventMapping, to ensure better consistency and easier reasoning about the code:
* do not hold onto _options, which is the same as _parent.Options
* do not call _options.Events which is the same as _parent
* made Alias always represent EventTypeName
* remode DatabaseSchemaName, the setter was throwing at runtime and no usage found, clients who used that member can get same info through .Table.Schema instead
=> Few minor changes to EventMapping

src/Marten/DocumentStore.cs, src/Marten/IDocumentStore.cs, src/Marten/Storage/BulkInsertion.cs
1. BulkInsert method now accept not only arrays, but also lists and hashsets.
2. Reduce GC memory pressure on batch gathering
=> BulkInsertion optimization

build.sh
- Remove restore step targeting netstandard1.3
- Keep tests targeting netcoreapp2.0
This is also the fix for travis ci build failing for #1038.
=> Fix travis ci build file

src/Marten.Testing/Bugs/Bug_1019_event_type_not_found_bad_exception_message.cs, src/Marten/Events/EventGraph.cs
Note: bear with me, this is all done in github editor.
I'm facing issue trying to retrieve events that I defined in a F# script (evaluating/running the script again results in potentially different assembly name):
```fsharp
let store = DocumentStore.For(fun o ->
o.Connection(connectionString)
o.Events.set_StreamIdentity Marten.Events.StreamIdentity.AsString
)
```
When I run this code:
```fsharp
let stream = session.Events.FetchStream streamId
```
I'm getting this exception, which doesn't help troubleshooting the origin of the issue:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Baseline.ConcurrentCache`2.Fill(TKey key, Func`2 onMissing)
at …
```
=> more informative exception for unknown event types

src/Marten.Testing/Events/Projections/custom_transformation_of_events.cs, src/Marten/Events/Projections/ViewProjection.cs
Currently the `ProjectEvent` method on the `ViewProjection` will auto create new documents if the Id doesn't exist (coming from the provided Id selector) automatically. I have hit a use case where this is not desired and the desired result is only having the event applied as an update if the document already exists.
This PR adds a default parameter to the `ProjectEvent` method called `onlyUpdate`. By default it is set to false, so it will not break any existing code. If `updateOnly` is set to `true`, that event will only be applied if the document already exists.
Method Signature:
```
ProjectEvent<MembersJoined>(e => e.QuestId, Persist, updateOnly: true);
```
=> Adds UpdateOnly functionality to ProjectEvent on the ViewProjection

src/Marten.Testing/Bugs/Bug_1018_multi_key_unique_index_schema_update_assert_failure.cs, src/Marten/Schema/IndexDefinition.cs
- Fix bug GH-1018 to remove extra space between index keys from actual DDL statament for multi key indices
in Matches function which results in mismatch
=> Fix GH-1018

src/Marten.Testing/Bugs/Bug_1043_do_not_drop_unchanged_index.cs, src/Marten/Schema/ComputedIndex.cs, src/Marten/Schema/IndexDefinition.cs
- Fix for GH-1043 to ensure index names are in lower case to have
consistent behaviour while checking schema changes
=> Bug fix for GH-1043 to ensure user inputted index names are always lower case

documentation/content/theme.css, documentation/layout.htm
Hi 👋,
I ❤ the extensive docs but I find it hard to see and click the previous and next links at the bottom of the pages.
This PR adds some space below them; I picked 21px because that's the margin defined by the `<hr>` just above the `<nav>`.
=> Add space below previous and next links

src/Marten.CommandLine/Commands/Dump/DumpCommand.cs, src/Marten.CommandLine/Commands/Dump/DumpInput.cs, src/Marten.CommandLine/Commands/Patch/PatchCommand.cs, src/Marten.CommandLine/Commands/Patch/PatchInput.cs, src/Marten.CommandLine/MartenInput.cs, src/Marten.Testing/Schema/SchemaPatchTester.cs, src/Marten/Schema/IDocumentSchema.cs, src/Marten/Schema/SchemaPatch.cs, src/Marten/Storage/TenantSchema.cs
By default Marten always creates transactional script for patch and dump. When user choose to add indexes with `IsConcurrency=True`, create or drop index concurrently with a transaction block results in a script error as raised in #1042. 
This PR adds functionality to create transactional or non-transactional script using flag `[-t, --transactional-script]` passed to patch or dump. This way, user can choose to wrap a transaction or not.
With introduction of these changes, by default patch and dump will produce non-transactional script. Only with the flag passed, it produces transactional script. This changes the current default behaviour.
=> Add option to create transactional or non transactional script for patch and dump

src/Marten.Testing/Schema/DbObjectsTests.cs, src/Marten/Schema/DbObjects.cs, src/Marten/Storage/Table.cs
* Makes `IDbObjects.AllIndexes` implementation respect the documented behavior (get indices for the current tenant)
* Allows indice check not to fail in PG with `XX000: could not open relation with OID ..` when changes happen in unrelated schemas (e.g. schema is dropped so that an OID no longer exists when `pg_get_indexdef` executes)
* Concurrent test scenarios where schemas are treated as "disposable", e.g. only created for the duration of tests, won't sporadically fail in schema checks & patch generation
=> Only check table indices against the configured schema. This

README.md, documentation/splash.htm
Update nuget badge to use badgen.net which is faster and reliable to load than shields.io. Many a times, shields.io badge just does not load at all.
Also updated appveyor badge to use the appveyor url rather than shields.io
=> Update nuget badge to use badgen.net

documentation/documentation/events/appending.md, documentation/documentation/events/identity.md, documentation/documentation/events/index.md, documentation/documentation/events/projections/async_daemon.md, documentation/documentation/events/projections/index.md, documentation/documentation/events/projections/projectionbyeventtype.md, documentation/documentation/events/schema.md, documentation/documentation/events/streams.md, src/Marten.Testing/AsyncDaemon/async_daemon_end_to_end.cs, src/Marten.Testing/Events/Projections/QuestParty.cs
The documentation on events (and particularly projections) is a bit confusing, and lacks a key concept or two. I fixed typos all across the event documentation and focused heavily on the projections index page, to make it easier to differentiate aggregate types and details of each. This should help people who are new to Marten get started a lot more quickly.
Code changes are indentation or sample marking only.
=> Update event documentation

src/Marten/Marten.csproj
This would allow nuget package that is published to limit the version of npgsql, this way we can enforce the version during package installation of Marten without waiting for runtime errors to occur
Related to #1081
=> Restrict Npgsql version >=3.2.5 and <4.0

src/Marten.Testing/query_by_sql_where_clause_Tests.cs, src/Marten/Linq/QueryHandlers/UserSuppliedQueryHandler.cs
If Query/QueryAsync was started with a "where" clause but there was a space or new line before the "where", a duplicate "where" would be inserted because the start was not trimmed. Passing test included.
=> Fixes duplicate "where" bug in Query/QueryAsync with sql text

martenbuild.cs
Explicit restore has been redundant for some time now when using `dotnet build` and `dotnet run`.
=> rely on implicit restore

martenbuild.cs
Building is taken care of by the `compile` target, which is a dependency.
=> avoid redundant build

src/Marten.Testing/Util/update_batch_Tests.cs, src/Marten/Services/UpdateBatch.cs
The PR is off of master (3.0) but I _really_ would like this fixed for 2.10.  What would make that easier to do - should I make a PR off of that branch?  I'd rather not go through regression testing for npgsql 4 on my app at the moment if I don't have to.
=>  fixes #1109 async batch updates sent fifo

src/Marten/Util/TypeMappings.cs
- Eliminate usage of reflection in TypeMappings by using INpgsqlTypeMapper.Mappings - fixes #1049
- Update logic of PgTypes to use type mappings from INpgsqlTypeMapper.Mappings
Note: With the above fix, we don't need any change from Npgsql folks. @oskardudycz you can review and close the issue raised in Npgsql repo.
=> Eliminate usage of reflection in TypeMappings - fixes 1049

src/Marten.Testing/Services/ManagedConnectionTests.cs, src/Marten/DocumentStore.cs, src/Marten/IRetryPolicy.cs, src/Marten/Services/ManagedConnection.cs, src/Marten/Storage/DefaultTenancy.cs, src/Marten/Storage/Tenant.cs, src/Marten/StoreOptions.cs
- Add `IRetryPolicy` and `NulloRetryPolicy`
- Implemement RetryPolicy to configure the same via `StoreOptions` and wrap the Npgsql calls in `ManagedConnection` using retry policy - fixes #1119
- Update `ManagedConnection` unit tests to retrofit retry policy changes.
=> Implement RetryPolicy extension point feature to handle transient errors - fixes #1119

documentation/documentation/documents/identity/index.md
The former link was to a no longer existing Wikipedia page (and the one you got redirected to contains a vague hint to where to read about the algorithm itself).
Marten's CombGuidIdGeneration.cs contains all the info (references and the implementation)
=> Replaced "sequential Guid algorithm" link

src/Marten.Testing/Acceptance/full_text_index.cs, src/Marten/IQuerySession.cs, src/Marten/Marten.csproj, src/Marten/MartenRegistry.cs, src/Marten/QuerySession.cs, src/Marten/Schema/DocumentMapping.cs, src/Marten/Schema/FullTextIndex.cs
This adds an implementation of full text searching on top of the latest Marten code base.  Replacing #945 .
=> Reimplementing full text search on top of the latest code

src/Marten/Util/TypeMappings.cs
A space before a semi colon is a useless space, but it is considered a difference when comparing schemas and creating patches.
Added `.Replace(" ;", ";")` to remove spaces before semi-colons after squashing all multi spaces with `ReplaceMultiSpace`
=> Remove space before semicolon in CanonicizeSql

src/Marten.Testing/Bugs/Bug_1151_assert_database_matches_configuration_exception.cs, src/Marten.Testing/duplicate_fields_in_table_and_upsert_Tests.cs, src/Marten/Schema/IndexDefinition.cs
- Fix to remove duplicated double quotes for column names same as PostgreSQL keyword in actual sql statement in index definition matches logic
=> Fix GH-1151 AssertDatabaseMatchesConfiguration throws exception 

src/Marten.Testing/Bugs/Bug_1155_null_duplicate_fields.cs, src/Marten.Testing/Target.cs, src/Marten.Testing/Util/LambdaBuilderTester.cs, src/Marten/Util/LambdaBuilder.cs
Fixes #1155 scenarios where duplicate fields or their ancestors can be null.
When this is the case the default value will be stored to the duplicate field.
I've extended the expression generation logic to add null checks when getting values for duplicate fields and compiled queries. 
Excerpt from comments below:
```
// Builds expression to retrieve value including enum conversion and null checks:
// Simple property/field                 target => target.Property
// Enum conversion to int                target => Convert.ToInt32(target.EnumProperty)
// Enum conversion to string             target => Enum.GetName(type, target.EnumProperty)
// Nested property/field null checks     target => target.Inner != null ? target.Inner.Property : default()
```
I've added tests scenarios specific the …
=> Fix duplicate field null scenarios

.gitignore, appveyor.yml, src/Marten.CommandLine/Marten.CommandLine.csproj, src/Marten/Marten.csproj
- Add SourceLink related settings to Marten and Marten.Commandline
csproj files
- Replace deprecated `PackageLicenseUrl` with `PackageLicenseExpression` in
csproj files
- Update AppVeyor config to add .snupkg to artifacts folder
- Add .snupkg to .gitignore
=> Add SourceLink for Marten libs - fixes GH-1156

documentation/documentation/events/appending.md
Dear Marten Team,
I recently startet experimenting with Marten DB as an event store. I found a mistake in the appending.md file of the events documentation.
This is my first pull request on a public project, but I hope it is helpful. 
Best regards,
Felix
=> Fix small spelling mistake in Documentation

src/Marten.Testing/Events/Projections/custom_transformation_of_events.cs, src/Marten/Events/Projections/ViewProjection.cs
This prevents default type ids from creating new erroneous documents.
=> On the ViewProjection, if the Id selector returns the default of the projection type Id, then do not add that viewId as a new projection.

src/Marten.Testing/TypeMappingsTests.cs, src/Marten/Util/TypeMappings.cs
`Marten.Util.TypeMappings` pre-caches Type mappings in a static constructor, using the Npgsql registry. If client code depends on any custom mappings which are registered with Npgsql, they will not be picked up, since static constructors execute very early. (There may be a way to sneak a value into Npgsql before Marten gets initialized, but I was unable to find a way to make it happen.)
This change (or one like it) would allow those type mappings to be re-executed after any other custom mappings are added.
Thoughts?
=> Respect custom mappings in NPGSQL's GlobalTypeMapper

README.md
`README.md` contains a link for getting started with PLV8 on windows, but nothing for non-windows systems. I wrote an [automated Docker solution](https://github.com/eouw0o83hf/marten-local-db) to get testing up and running with one script call, and wanted to share it with other prospective contributors.
If it would be more useful to just add that container system to this repository, I'm glad to do that.
=> Update run dependency docs and add link to automated docker solution

src/Marten.Testing/SessionOptionsTests.cs, src/Marten/Linq/QueryPlan.cs, src/Marten/Services/CommandRunnerExtensions.cs, src/Marten/Services/ManagedConnection.cs, src/Marten/Services/SessionOptions.cs, src/Marten/Services/TransactionState.cs, src/Marten/Storage/DefaultTenancy.cs, src/Marten/Storage/ITenant.cs, src/Marten/Storage/Tenant.cs
* Default command timeout can be passed via Npgsql cstring & it is actually respected
* Default command timeout can be overriden with SessionOptions
* If not provided, commands default to Npgsql command timeout (currently 30 sec)
And obviously this commit would break some of the existing signatures. Other options would be to keep & pass around some internal state... Gets a bit nasty, since e.g. ConnectionFactory has lazy connectionString (and the only place where the cstring is contained) that can be resolved at a very late state on first command execution.
=> Would fix #1178:

src/Marten.Testing/UnitOfWork_PendingChanges_Functionality_Tests.cs, src/Marten/Services/IUnitOfWork.cs, src/Marten/Services/UnitOfWork.cs
Exposes the `IStorageOperations` that will be executed by `IUnitOfWork`, as discussed in issue #1209 
The related issue discusses better support for multi-tenancy. This change does not tackle that. This PR allows for modification of existing operations that gives me the hooks to do more automatic handling for multi-tenancy (I can automatically set `TenantOverride` for operations).
I can envision other potential usages like all-encompassing logging, or even performance tracking related usages to check how many operations are being executed and alerting.
=> Expose IStorageOperations on IUnitOfWork

src/Marten.Testing/Schema/creating_a_full_patch.cs, src/Marten/Events/AppendEventFunction.cs, src/Marten/Schema/SystemFunction.cs
Hi all, we came across a minor issue when generating a patch rollback script for a new marten database, where the drop function statements for a few of the system functions didn't have semicolons following them. The affecting functions are mt_immutable_timestamp, mt_immutable_timestamptz, and mt_append_event. This PR fixes them and adds a test for it.
The whitespace changes in AppendEventFunction.cs are replacing all tabs with spaces as the file was mixed. Let me know if you'd rather not have the whitespace changes included and i'll remove them.
As always let me know if anything else is required.
I found a couple other issues related to patch rollback scripts that i'll create issues for as they likely require a bit more discussion than this.
=> Add missing semicolons when dropping system functions

src/Marten.Testing/Storage/TableTester.cs, src/Marten.Testing/TypeMappingsTests.cs, src/Marten/Util/TypeMappings.cs
I was working on a project and encountered the error "Marten cannot derive updates for objects" when creating a document store for tables with a "serial" column and text array columns (varchar[], text[], etc). I think the issue is related to TypeMappings.cs and can be resolved with this PR.  
Path to repo to reproduce error: https://github.com/egiraffe/Marten-Serial
in the repo, everything runs correctly on create, but creating the store after the initial run fails.
=> added type mappings for serial and text/varchar arrays

.editorconfig, .gitattributes, src/Marten.sln
@jeremydmiller @mysticmind @jokokko if you're fine with this `.editorsettings` then I'll do code clean up and change warnings settings into errors.
See rules explanation: https://docs.microsoft.com/en-US/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017
=> Added Auto LF and .editorconfig settings for aligning formatting rules

src/Marten.Testing/Storage/SequenceCustomization.cs, src/Marten/Schema/DocumentCleaner.cs, src/Marten/Storage/Sequence.cs
Make `IDocumentCleaner.CompletelyRemoveAll` also drop _mt__ prefixed sequences (so it matches the method desc "Remove all Marten-related schema objects").
Additional _ctor_ in `Sequence` for binary compatibility.
=> Support sequences with custom start value.

src/Marten.Testing/Events/end_to_end_event_capture_and_fetching_the_stream_Tests.cs, src/Marten/Events/AppendEventFunction.cs, src/Marten/Events/EventGraph.cs, src/Marten/Schema/SQL/mt_stream.sql
Currently, if you have a concurrent calls from different processes appending events to the same stream id, it can lead to a mismatch in the `version` stored in the `mt_streams` table and the `version` stored in the `mt_events` table. This is due to the fact that the selection and updating of the event version on the `mt_streams` table is not placing any type of lock on the row after selecting out the version before updating. This creates a race condition in the `mt_append_event` function. Which then leads to a duplicate version key constraint error.
This change puts a `FOR UPDATE` lock on the event version `SELECT` from the `mt_streams` table. This puts a `ROW EXCLUSIVE` lock on the that given streams row, causing any other concurrent calls on the same stream id to wait on that lock, …
=> Fixes concurrency bug on mt_append_event function when processing the same stream.

martenbuild.cs, martenbuild.csproj
6.0.0 introduces [this feature](https://github.com/adamralph/simple-exec/pull/128), which means you no longer have to inspect the OS platform yourself.
=> update SimpleExec to 6.0.0-beta.1

src/Marten.CommandLine/Marten.CommandLine.csproj, src/Marten.NodaTime.Testing/Acceptance/noda_time_acceptance.cs, src/Marten.NodaTime/InstantJsonConverter.cs, src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten.NodaTime/NodaTimeExtensions.cs, src/Marten/Marten.csproj
Added InstantJsonConverter to properly deserialize Instants when db won't return data in TZ format.
The need come up with https://github.com/JasperFx/marten/issues/1276.
This is workaround for NodaTime issues https://github.com/nodatime/nodatime/issues/154 and https://github.com/nodatime/nodatime/pull/1237.
Revisit this when NodaTime 3.0.0 will be officialy released - then this class might be not needed anymore.
Upgraded Packages for `3.6.0` release.
=> Fixes #1276 - fixed nodaTime instant deserialization

azure-pipelines-benchmarks.yml, azure-pipelines.yml
Log messages on Azure Pipelines are showing character escapes due to ANSI code support issue - refer to https://github.com/microsoft/azure-pipelines-agent/issues/2140. 
Update Bullseye to use `--no-color` in the interim to resolve the issue at hand.
=> Fix to use Bullseye --no-color for Azure Pipelines

src/Marten.CommandLine/Marten.CommandLine.csproj, src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten/Marten.csproj
CI build logs are littered with a lot of XML docs warnings resulting in difficulty to inspect the logs. Suppressing the XML docs warnings in the interim until we have got it sorted.
=> Update csproj to suppress xml docs warnings

src/Marten.Testing/Linq/query_with_dates_Tests.cs
Fixes https://github.com/JasperFx/marten/issues/1266
=> Fixed flaky Marten.Testing.Linq.query_with_dates_Tests.can_select_DateTimeOffset_and_will_return_localtime test

package-lock.json, package.json
The prior version of lodash had security vulnerability so updated it to use version >=4.17.13 (Github notification highlighted this issue)
=> Update dev dependency lodash to use version >=4.17.13

src/Marten/DocumentSession.cs, src/Marten/Events/Projections/AggregateFinder.cs
Also don’t try to load an empty array of stream ids in the AggregateFinder.
These two changes provide a decent performance boost when there are no streams when saving, by eliminating erroneous DB queries and not looping inline projections, as explained below. 
Prior to this change `applyProjections` would loop every inline projection trying to apply an empty array of streams. If one of the projections used the `AggregateFinder` (like AggregateStreamsWith<>), then it would be querying the database to load an empty array of ids for every inline projection that uses it.
This issue was especially visible when rebuilding a projection in the Async Daemon
=> Short circuit applying empty streams to all Inline projections when saving if there are no streams

src/Marten.Testing/Schema/ApplyAllConfiguredChangesToDatabaseTests.cs, src/Marten/Schema/IDocumentSchema.cs, src/Marten/Storage/TenantSchema.cs
- Add functionality to run `ApplyAllConfiguredChangesToDatabase` independent of StoreOptions AutoCreate
- Fixes #1324
=> Add functionality to run `ApplyAllConfiguredChangesToDatabase` independent of StoreOptions AutoCreate

src/Marten.Testing/Linq/IsNullNotNullArbitraryDepthTests.cs, src/Marten.Testing/Linq/previewing_the_command_from_a_queryable_Tests.cs, src/Marten.Testing/Schema/DuplicatedFieldTests.cs, src/Marten.Testing/Schema/JsonLocatorFieldTests.cs, src/Marten.Testing/Util/CommandBuilderTests.cs, src/Marten/Linq/ChildCollectionWhereVisitor.cs, src/Marten/Linq/CollectionAnyContainmentWhereFragment.cs, src/Marten/Linq/WhereClauseVisitor.cs, src/Marten/Schema/DuplicatedField.cs, src/Marten/Schema/FieldCollection.cs, src/Marten/Schema/JsonLocatorField.cs, src/Marten/Util/CommandBuilder.cs, src/Marten/Util/TypeMappings.cs
This required changes the JsonLocatorField constructors so the generated locators were consistent regardless of field depth.
Before this change, an array would change casting behavior depending on depth: 
```
public class T
{
public String[] MyArray { get; set; }
public T Inner { get; set; }
}
```
`CAST(d.data ->> 'MyArray' as jsonb)`
vs
`CAST(d.data -> 'Inner' ->> 'MyArray' as varchar[])`
I'm still unclear why arrays as top level properties were always being cast to jsonb, but I left it that way.
=> Issue #1190 -  ensure the locator for a CollectionAnyContainment query matches the field's index

src/Marten.Testing/Events/Projections/custom_async_transformation_of_events.cs, src/Marten/Events/Projections/ViewProjection.cs
There is a bug in my last ViewProjection changes that would attempt to delete a view if it was `null`. This fixes that issue by checking if the view exists before calling delete.
=> ViewProjection - Only Delete view if it exists

src/Marten/Schema/Arguments/UpsertArgument.cs
While investigating the update to npgsql 4.1.0, I found that the ordering of the members on the NpgsqlBinaryImporter had changed so that the `Write<T>(T, NpgsqlDbType)` overload was no longer the first two-parameter overload.  After some investigation in the repl I found the intended overloads in a way that works across versions.
<details>
<summary>Repl code to verify the 'is the same method' assertion</summary>
```fsharp
// uncomment one of these
#r "/Users/chethusk/.nuget/packages/npgsql/4.1.0-preview2/lib/netcoreapp3.0/Npgsql.dll"
//or
//#r "/Users/chethusk/.nuget/packages/npgsql/4.0.9/lib/netstandard2.0/Npgsql.dll"
open Npgsql
open System.Reflection
let methods = typeof<NpgsqlBinaryImporter>.GetMethods()
// existing code in UpsertArgument.cs
let method = methods |> Array.tryFind (fun …
```
=> Make the search for upsert write method more precise

src/Marten/Services/TransactionState.cs
Since `Rollback` checks the current transaction for null, there is no need in conditional invocations.
=> Removed redundant null conditional method calls

src/Marten/Storage/IFeatureSchema.cs, src/Marten/Storage/Tenant.cs
- move name check inside the lock,
- only load the schema objects once to do this, 
- don't re-run checks on race conditions
=> Fixes #1372 -  thread safety of storage setup

src/Marten/Marten.csproj, src/Marten/Services/TransactionState.cs
Npgsql starting version 4.1 supports async versions of `Close` and `Dispose` methods.
=> Use async versions of dispose and close methods

src/Marten.Testing/Documents/User.cs, src/Marten.Testing/Linq/query_with_inner_query_with_global_CollectionStorage_WithArray.cs, src/Marten.Testing/Session/document_session_load_document.cs, src/Marten/Services/Json/JsonNetCollectionToArrayJsonConverter.cs
As in the description - see more details in #1386 
Besides providing the fix and adding test for the described case, I updated inner collection queries tests to be sure that this case won't be missed again.
=> Fixes #1386 - not being able to serialize IReadonlyCollection<int> while using CollectionStorage.AsArray

martenbuild.cs
#1399 
With this configuration, docs will be published automatically to Netlify from `gh-pages-netlify` branch. 
It's needed to have a separate branch, as Storyteller run with `ProjectWebsite` and  `--project marten` parameters will add `marten` prefix to all paths. 
To remove that prefix it's needed to run it with `Website` parameter but without `--project marten`.
I already published the initial state manually to Netlify.
It can be seen at: https://martendb.io/
=> Updated `publish-docs` to publish also to Netlify for Martendb.io domain

src/Marten.Testing/Patching/PatchExpressionTests.cs, src/Marten/Patching/PatchExpression.cs
- Fix patch expression to use right property name casing based on serializer settings
fixes GH-1385
=> Fix patch expression to use right property name casing

documentation/documentation/cli.md, documentation/documentation/documents/configuration/unique.md, documentation/documentation/postgres/naming.md, documentation/documentation/postgres/types.md, documentation/layout.htm, documentation/splash.htm
- Fix js files to use https served via CDN
- Remove url prefixe jasperfx.github.io/marten in links or images
- Fix url for image resources
- Fix broken link references added via `linkto:`
=> Fix mixed content and links in docs

src/Marten/Schema/DocumentCleaner.cs
`truncate` fails when the tables don't exist. This tweak prevents the problem, similar to how it is prevented elsewhere in DocumentCleaner.
=> Make DeleteAllEventData safe for empty database.

CONTRIBUTING.md, LICENSE, README.md, documentation/content/stylish-portfolio.css, documentation/content/theme.css, documentation/layout.htm, documentation/splash.htm, martenbuild.csproj, package-lock.json
1. Updated Licence to include required "Copyright (c) .NET Foundation and Contributors"
2. Updated README to contain:
-  License information, 
- Code of Conduct link,
- .NET Foundation information,
- Twitter Badge 
3. Updated project documentation with information about .NET Foundation support.
4. Added Contribution guidelines document.
=> .Net Foundation onboarding

README.md, azure-pipelines-benchmarks.yml, azure-pipelines.yml
1. Added Postgres 12 to build matrix.
2. Updated Postgres 11 image to use version 11.5
Fixes  #1433
See also: https://github.com/IonxSolutions/docker-images/pull/4
=> Added Postgres 12 to build matrix

src/Marten.Testing/Schema/Identity/Sequences/Bug_1404_Hilo_concurrent_update_failure.cs, src/Marten.Testing/TargetIntId.cs, src/Marten/Schema/Identity/Sequences/HiLoSequence.cs, src/Marten/Schema/Identity/Sequences/HiloSequenceAdvanceToNextHiAttemptsExceededException.cs, src/Marten/Schema/Identity/Sequences/HiloSettings.cs, src/Marten/Schema/SQL/mt_get_next_hi.sql
Fixes concurrency error with HiloSequence generator in high concurrency case.
1. Added test that consistently reproduces the problem
2. Updated `get_next_hi` sproc update condition to include check that the current hilo value hasn't changed since the last select. If it did, then return -1
3. Updated transaction isolation to read committed.  We do not need to run in serialization isolation now because of #2. 
4. Removed `try..catch` block surrounding sproc call. It's put in place before to address exceptions regarding concurrency issues in serialization isolation mode, hence no longer necessary.
Things for reviewer to look at
1. I'm not sure about is whether those who already have Marten running live would get the updated sproc (e.g. AutoCreate option is set to none).  How do we force …
=> Bug#1404 fixed Hilo concurrency error

documentation/documentation/events/projections/custom.md, documentation/documentation/events/projections/index.md, src/.editorconfig, src/Marten.Testing/Events/Projections/QuestMonsters.cs, src/Marten.Testing/Events/Projections/view_projection_for_view_with_base_class .cs, src/Marten.Testing/Events/ScenarioAggregateAndRepository.cs, src/Marten.Testing/Util/NewTests.cs, src/Marten/Events/AggregationQueryHandler.cs, src/Marten/Events/Event.cs, src/Marten/Events/EventGraph.cs, src/Marten/Events/EventStore.cs, src/Marten/Events/IEventStore.cs, src/Marten/Events/Projections/AggregateFinder.cs, src/Marten/Events/Projections/AggregationProjection.cs, src/Marten/Events/Projections/Aggregator.cs, src/Marten/Events/Projections/AggregatorApplyPrivate.cs, src/Marten/Events/Projections/AggregatorApplyPublicAndPrivate.cs, src/Marten/Events/Projections/AggregatorLookup.cs, src/Marten/Events/Projections/IAggregatorLookup.cs, src/Marten/Events/Projections/LazyLoadedProjection.cs, src/Marten/Events/Projections/ProjectionCollection.cs, src/Marten/Events/Projections/StringIdentifiedAggregateFinder.cs, src/Marten/Events/Projections/ViewProjection.cs, src/Marten/Services/BatchQuerying/BatchedQuery.cs, src/Marten/Services/BatchQuerying/IBatchedQuery.cs, src/Marten/Util/New.cs
Currently, Marten forces in many places `new ()` constructor. This is not a huge issue, but a bit painful and sometimes too big restriction. For most of the guides of how to construct proper aggregates (and classes in general), it stated that they should only expose what's needed. Usually, it's good to not expose the public default constructor but use the dedicated factory method.
Especially for the event-sourced aggregates, it's important, as the state should be rebuilt from the events. 
Introduced new object factory called (surprise!) [New](https://github.com/JasperFx/marten/pull/1447/files#diff-7d3a0e04c31307b447489d682c01847aR8). This solution is taken from https://stackoverflow.com/a/16162475/10966454.
See also more benchmarks and discussion about object creation from lambda (with …
=> Removed the requirement for having the default constructor in the aggregation process and projections

src/Marten.Testing/Linq/InvariantCultureIgnoreCase_filtering.cs, src/Marten/Linq/Parsing/StringComparisonParser.cs
We just ran into an issue where `StringComparison.InvariantCultureIgnoreCase` was not being applied to queries in our netcore 2.2 app. This should make query case invariance work as expected for netcore apps.
I was unable to divine the intend behind the `#if NET46` directive - I really wanted to just delete it entirely, but I'm sure it's allowing for some other edge case somewhere.
=> Allow case invariance for netcore apps

src/Marten/Events/EventStore.cs, src/Marten/Events/EventStream.cs, src/Marten/Events/StreamState.cs
I think this was mostly an oversight on my part to begin with
=> Event Store uses sequential guids for the stream ids. Closes GH-1432

documentation/documentation/documents/tenancy/basicoperations.md, src/Marten.Testing/Acceptance/disabling_default_tenant_usage.cs, src/Marten/DefaultTenantUsageDisabledException.cs, src/Marten/DocumentStore.cs, src/Marten/StoreOptions.cs
- Add feature to disable using default tenant to store multi tenanted docs
- Add docs
Fixes GH-1449
=> Add feature to disable using default tenant to store multi tenanted docs

src/Marten.Testing/Events/Projections/custom_transformation_of_events.cs, src/Marten/DocumentStore.cs, src/Marten/Events/EventGraph.cs, src/Marten/Events/Projections/ProjectionCollection.cs
Fixes #1302 
@sturatcliffe @ericgreenmix it seems that the issue was fixed in one of the previous releases. I copied the repro from the linked project https://github.com/sturatcliffe/MartenProjectViewIssue.
Could you confirm
**EDIT:**
After a nice catch from @mysticmind I was able to reproduce and fix the issue.
The problem was that for such case we had more than one inline projection defined for the specific projection type. In the AsyncDaemon we were always getting `FirstOrDefault` projection instead of a list of the projections for the selected view type.
Fixed that with adding overload for the ForView method that's returning Enumerable instead of single Projection. 
Note in V4 this method should be merged into the ForView methods so it returns the IEnumerable properly. Added overload …
=> #1302 - Fixed the ProjectView / DeleteEvent and rebuilding projections

documentation/documentation/events/index.md, src/Marten.Testing/Examples/event_store_quickstart.cs, src/Marten/Events/EventStore.cs, src/Marten/Events/IEventStore.cs
I have a use case where I'm starting new event streams without knowing the type at compile time. It's essential for me that the stream type info gets persisted. This change declares two new StartStream methods on the IEventStore interface which allows you to pass the the aggregate type as a parameter.
=> Add possibility to start typed event streams with non-generic StartStream

src/Marten.Testing/CoreFunctionality/SessionOptionsTests.cs, src/Marten/Services/ManagedConnection.cs
The session raised a NullReferenceException on usage after a SaveAsync call when constructed with Session options.
The problem can be found in the ManagedConnection when constructed with SessionOptions.
After a dispose of the TransactionState the ManagedConnection will try to rebuild it on further usage in the buildConnection method, The TransactionState constructor used relies on, that the factory has been set before.
This behaviour has been fixed by using the correct constructor and providing the fields needed.
The following test replicates the behaviour:
```C#
class TestObject
{
public Guid Id { get; set; }
public string Name { get; set; }
}
[Test]
public void Inject_Connection()
{
var connectionString = $"host=host;database=db;password=pw;username=un;";
var store = …
```
=> Call the correct TransactionState constructor

README.md
Added a badge generated by Shield.io that displays the nuget package download count.
Closes #1536.
=> Add badge with nuget download count

documentation/documentation/events/order.txt, documentation/documentation/events/versioning/index.md, src/Marten.Testing/Events/SchemaChange/NamespaceChange.cs
Added sample and documentation showing how event type namespace or name migration can be handled by Marten. 
More advanced scenarios or guidelines will come in follow up PRs.
=> Sample showing how Marten handles Event type namespace or name migration

documentation/documentation/documents/advanced/retrypolicy.md, src/Marten.Testing/Examples/RetryPolicyTests.cs, src/Marten.Testing/Services/DefaultRetryPolicyTests.cs, src/Marten/IRetryPolicy.cs
Per Gitter discussion, this is the [documentation sample retry policy](https://martendb.io/documentation/documents/advanced/retrypolicy/) with some tweaks.
* filter defaults to checking for `x is NpgsqlException npgsqlException && npgsqlException.IsTransient`
* renamed `NTimes` to just `Times`
* new parameter `sleep` that allows to return `TimeSpan` to sleep given current retry number, defaults to retry number as seconds
* made `IRetryPolicy` interface implementation explicit to hide members not relevant for public API
=> Introduce DefaultRetryPolicy

src/Marten.Testing/Examples/LinqExamples.cs, src/Marten.Testing/Linq/Compatibility/simple_order_by_clauses.cs, src/Marten/Linq/MartenQueryParser.cs, src/Marten/Linq/Model/LinqQuery.cs, src/Marten/Linq/Model/SelectManyQuery.cs, src/Marten/Linq/OrderByComparerClause.cs, src/Marten/Linq/OrderByComparerExpressionNode.cs, src/Marten/Linq/OrderByComparerOperator.cs, src/Marten/Linq/OrderByOperator.cs, src/Marten/Util/OrderingExtensions.cs
I asked about this on Gitter with little feedback, it seemed to be missing so I decided to try how one could implement order by semantics case-insensitively. Some remarks:
* To order normal column one would use `citext` type or in Postgres v12 there's new collation support, either of if these are not available on Marten context
* This solution uses `lower(field)` which should work for most use cases, with slight performance penalty
* Because Remotion.Linq doesn't support the comparer parameter, a new code path needs to be taken
* This is why you cannot combine "regular" OrderBy and OrderBy that has comparer
This was my first try against Remotion.Linq so not sure if the approach is ideal.
I did this against 3.12 as I would need this feature, if you find this reasonable addition. Otherwise …
=> Support case-insensitive order by for strings

src/Marten/Util/LambdaBuilder.cs
.NET 5 Preview 8 added a generic overload for `GetName`, thus breaking the previous reflection.
.NET Core 3.1:
.NET 5 Preview 8:
=> Fix enum reflection for .NET 5

src/Marten.Testing/Linq/query_negating_predicate_with_binary_operator_tests.cs
Add unit tests for 4.x - negating a predicate that contains binary operators
> Quick note, this issue is not there in 4.x branch and the new linq related implementation changes have sorted this out. I will add the unit tests to 4.x branch.
https://github.com/JasperFx/marten/issues/1568#issuecomment-719287785
=> Add unit tests for 4.x - negating a predicate that contains binary operators

documentation/documentation/documents/configuration/noda_time.md, src/Marten.NodaTime.Testing/Acceptance/noda_time_acceptance.cs, src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten/Marten.csproj
Changes: https://github.com/npgsql/npgsql/milestone/70?closed=1
Most importantly, this fixes the long-running problem of combining NodaTime with BCL DateTime types.
=> Update minimum npgsql to 4.1.5

src/Marten.Testing/Linq/Fields/DuplicatedFieldTests.cs, src/Marten/Linq/Fields/DuplicatedField.cs
This caused a nasty production bug for me when constructing a query against duplicated columns using optional args. For instance, given the document setup:
```
class ExampleDocument
{
Colors Color { get; set; }
string Name { get; set; }
}
```
I had a method which was something to the tune of:
```
IEnumerable<ExampleDocument> ListDocuments(Colors? color, string? name)
=>  _querySession
.Query<ExampleDocument>()
.Where(a => (color != null && a.Color == color)
&& (name == null || a.Name == name))
.ToList();
```
That caused a hard error because a `null` value for `color` was causing the duplicated field handler to error out, despite the fact that it would never be evaluated against the column itself due to the OR evaluation.
=> Allow null enum values to be parsed in duplicated field resolution

src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten.Schema.Testing/Storage/DocumentTableTester.cs, src/Marten.Testing/Services/DefaultRetryPolicyTests.cs, src/Marten.Testing/Services/ManagedConnectionTests.cs, src/Marten/Marten.csproj, src/Marten/Services/TransactionState.cs
- Update `Npgsql`, `Npgsql.Json.NET`, `Npgsql.NodaTime` to v5.0.0
- Fix and handle a Npgsql breaking change of `NpgsqlTransaction.IsCompleted` not
available in public API. Refer to https://github.com/npgsql/npgsql/blob/d5aee643792fad71b9220d06c16a3612ccc10e0d/src/Npgsql/NpgsqlTransaction.cs#L412 based on which the fix is added
- Update `Newtonsoft.Json` to  12.0.3 (12.0.2 is the minimum requirement for
`Npgsql.Json.NET 5.0.0`)
=> Update to use Npgsql 5.0.0

src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten.NodaTime/NodaTimeExtensions.cs, src/Marten/Events/EventQueryHandler.cs, src/Marten/Events/EventSelector.cs, src/Marten/Events/StreamStateByGuidHandler.cs, src/Marten/Events/StringIdentifiedEventSelector.cs, src/Marten/Marten.csproj, src/Marten/Storage/EntityMetadataQueryHandler.cs, src/Marten/Util/TypeMappings.cs
- Remove type mappers from NodaTime implementation (retrofit changes
from master/ PR https://github.com/JasperFx/marten/pull/1604)
- Update Npgsql, Npgsql.Json.NET, Npgsql.NodaTime min dependency to 4.1.6
=> Remove type mappers from nodatime implementation on 3.x

src/Marten/Linq/Parsing/DictionaryExpressions.cs
the code assumes that the argument is a ConstantExpression, so may as well use a cast. if this assumption is wrong, it is better to get a cast exception (with the associated type info) than a null reff
=> use direct cast to ConstantExpression in QueryFromICollectionContains

Directory.Build.props, src/Marten.CommandLine.Testing/Marten.CommandLine.Testing.csproj, src/Marten.CommandLine/Marten.CommandLine.csproj, src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj, src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten.Schema.Testing/Marten.Schema.Testing.csproj, src/Marten.Storyteller/Marten.Storyteller.csproj, src/Marten.Testing.OtherAssembly/Marten.Testing.OtherAssembly.csproj, src/Marten.Testing/Marten.Testing.csproj, src/Marten.sln, src/Marten/Marten.csproj, src/MartenBenchmarks/MartenBenchmarks.csproj, src/StorytellerRunner/StorytellerRunner.csproj
* use dir props to share common settings
* remove default csproj values. `IsPackable>false`, AssemblyName and PackageId default to the csproj file name,
* moved to c# 9. i am assuming u will eventually want to use some of those features
=> Consolidate csproj settings

src/Marten/Storage/Metadata/HeadersColumn.cs
I am assuming cancellation tokens should be passes in these scenarios. 
If not, it might be work adding a comment as to why (which i am happy to do)
=> pass cancellation tokens

src/Marten/Events/Projections/ViewProjection.cs
will prevent a null ref when UpdateOnly and handler=null
given handler is assumed to not be null when ProjectionEventType.UpdateOnly. then null check should be inside the 
type == ProjectionEventType.CreateAndUpdate || type == ProjectionEventType.UpdateOnly
also better perf by removing a redundant check if a different ProjectionEventType
=> check for ViewProjection.projectEvent.handler null when UpdateOnly

src/Marten/Events/Projections/Async/Fetcher.cs, src/Marten/Events/Projections/ViewProjection.cs, src/Marten/Events/V4Concept/CodeGeneration/EventDocumentStorageGenerator.cs, src/Marten/Linq/Fields/FieldCollection.cs, src/Marten/Schema/ForeignKeyDefinition.cs, src/Marten/Storage/Tenant.cs, src/Marten/StoreOptions.cs, src/Marten/Transforms/TransformFunction.cs
> Because there is only a single discard variable, and that variable may not even be allocated storage, discards can reduce memory allocations
https://docs.microsoft.com/en-us/dotnet/csharp/discards
=> use c# discards

src/Marten.Testing/Services/ManagedConnectionTests.cs, src/Marten/Services/TransactionState.cs
Fix to close connection on rollback only if it owns the connection
fixes #1620
=> Fix to close connection on rollback only if it owns the connection

src/Marten.Testing/Acceptance/unique_indexes.cs, src/Marten/Schema/DocumentMapping.cs
Fix to throw an exception for unique index without any properties
fixes #1581
=> Fix to throw an exception for unique index without any properties on 3.x

src/Marten.Testing/Bugs/Bug_1703_Equality_Not_Symmetric.cs, src/Marten.Testing/Bugs/equality_not_symmetric.cs, src/Marten/Linq/Parsing/Methods/SimpleEqualsParser.cs, src/Marten/Linq/Parsing/Methods/StringComparisonParser.cs
Fixes #1703, but for objects
As noted by @jeremydmiller, the previous fix (#1706) only  applied to strings. This change adds the same fix to the generic Equals method of System.Object. 
I've also moved the test class to better fit the naming scheme.
If there are other places where this issue occurs, I'd be happy to take a look.
=> Bugfix/symmetric equality (for objects)

documentation/documentation/events/projections/custom.md
I think the change to L38 is correct - there's a missing 'no' that suggests that if no document is found for an Id, then a new one is created. Also adjusted some grammar to make it a little easier to read.
=> Add missing 'no', fix some readability issues.

src/Marten.AsyncDaemon.Testing/DaemonServiceRegistrationTests.cs, src/Marten/MartenServiceCollectionExtensions.cs
This was missing and causing any daemon setting to throw on application startup when the hosted service attempted to resolve.
Due to the constructor on the projection daemon, building the instance via the store appears to be the simplest option.
=> Hook up projection daemon in marten extensions

src/Marten.Testing/Events/Projections/QuestMonsters.cs, src/Marten.Testing/Events/Projections/inline_aggregation_with_private_constructor.cs, src/Marten/Events/CodeGeneration/AggregateEventProcessingFrame.cs, src/Marten/Events/CodeGeneration/CreateMethodCollection.cs
The inline projection was generating the proper Create method, but this method was not used at all. It was working fine for the case with a public constructor, as it was used directly instead of the Create method. 
Fixed by using the create method.
=> Fixed Inline Projection for type with a private constructor

src/Marten.Testing/Events/event_projection_scenario_tests.cs, src/Marten/AdvancedOperations.cs, src/Marten/Events/Daemon/IProjectionDaemon.cs, src/Marten/Events/Daemon/ProjectionDaemon.cs, src/Marten/Events/IEventStore.cs, src/Marten/Events/Projections/ProjectionCollection.cs, src/Marten/Events/TestSupport/ProjectionScenario.Assertions.cs, src/Marten/Events/TestSupport/ProjectionScenario.EventOperations.cs, src/Marten/Events/TestSupport/ProjectionScenario.cs, src/Marten/Events/TestSupport/ProjectionScenarioException.cs, src/Marten/Events/TestSupport/ScenarioAction.cs, src/Marten/Events/TestSupport/ScenarioAssertion.cs, src/Marten/Events/TestSupport/ScenarioStep.cs, src/Marten/StoreOptions.cs
It admittedly doesn't do a lot, but it does help with clearing out existing data and coordinating the test with the async daemon process *if* there are async projections
=> Event Projection testing helper

src/Marten/Storage/Table.cs
The change causes marten not to miss indexes in Storage.Table metadata queries.
Before the change, Marten would not return indexes that are owned by a role that cannot log in, which causes Marten to try to generate a patch creating existing indexes. 
Having roles that cannot log in is a common scenario in Postgres world, that allows easy password rotation without downtimes.
=> Use pg_roles instead of pg_user in Storage.Table schema object indexes query

src/Marten.Testing/Bugs/codegen_issue_with_IEvent.cs, src/Marten/Events/Aggregation/AggregateProjection.CodeGen.cs, src/Marten/Events/CodeGeneration/AggregateEventProcessingFrame.cs
Discovered this today whilst attempting to update to alpha.9. `FullName` spits out spaghetti and the exception was missing an import. Not exclusive to records, but very likely to encounter the issue.
=> Fix codegen failure for aggregate types with no default constructor

src/Marten.Testing/Events/flexible_event_metadata.cs, src/Marten/Events/EventQueryMapping.cs
When I was trying out the new event metadata support, I came across a bug when querying events with `session.Events.QueryAllRawEvents()`.
When querying events with correlation or causation ids, no events were returned. The generated SQL filtered causation/correlation id from event data (`d.data ->> 'CorrelationId' = :p0`) instead of the correlation/causation id columns. This PR hopefully fixes this issue.
=> Fix event querying with correlation and causation ids

src/Marten.Testing/Bugs/Bug_1779_null_comparison_to_foreign_key_column_not_generating_is_null.cs, src/Marten/Linq/Fields/DuplicatedField.cs
Currently `DuplicatedField.CreateComparison` always generates `is null` sql for null value and ignores the operator. Added check for the operator and support for using != to create `is not null`.
=> Fix null value handling in DuplicatedField.CreateComparison

docs/vite.config.js, package-lock.json, package.json
The latest version of Vite released a few hours ago has a breaking change in its file serving due to a security issue, thereby breaking Vitepress.
=> Fix local docs serve

src/Marten.Testing/Bugs/Batch_query_load_fails_with_multi_tenant_document.cs, src/Marten/Internal/Storage/IDocumentStorage.cs
When loading multi tenanted documents with batch query, following exception is thrown. Using v4 rc2.
```Marten.Testing.Bugs.Batch_query_load_fails_with_multi_tenant_document.load_with_batch_query_should_work_for_multi_tenanted_document
Marten.Exceptions.MartenCommandException: Marten Command Failure:$
Marten.Exceptions.MartenCommandException
Marten Command Failure:$
select d.id, d.data from bugs.mt_doc_user as d where id = :p0 and d.tenant_id = :tenantid;$
$
42601: syntax error at or near ":"
at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
at Baseline.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(NpgsqlCommand command, Exception exception) in …
```
=> Fix for loading multi tenant documents with batch query

src/Marten.Testing.OtherAssembly/Bug1851/GenericOuter.cs, src/Marten.Testing.OtherAssembly/Bug1851/StoredObjectInOtherAssembly.cs, src/Marten.Testing.OtherAssembly/Marten.Testing.OtherAssembly.csproj, src/Marten.Testing/Bugs/Bug_1851_need_to_recursively_reference_assemblies_in_generic_type_parameters_of_compiled_queries.cs, src/Marten/Internal/CompiledQueries/CompiledQuerySourceBuilder.cs
This fixes bug #1851. Unit test enclosed.
Care was taken to make the walking process use a stack instead of recursion to avoid stack overflows.
=> Fix bug #1851 - recursively walk referenced assemblies.

src/Marten.AsyncDaemon.Testing/DaemonServiceRegistrationTests.cs, src/Marten/Events/Daemon/AsyncProjectionHostedService.cs
I have seen the daemon trying to stop when using Marten as document store, using 4.0.0-rc.2
This PR covers a first attempt to try to stop the error message (I know this is not a real issue since is just the log so the code will continue just fine until the end of my app)
I added the debug just for the sake of testing, but open to change this.
=> Don't call Stop on daemon if projections are disabled

src/Marten.Storyteller/Fixtures/EventStore/InlineAggregationFixture.cs
Before this commit:
❌ run_specification(path: "Event Store/Projections/Inline_Aggregation_by_Stream.md") would fail with the following error:
> System.Exception: Rights: 2, Wrongs: 0, Exceptions: 2, SyntaxErrors: 0
And this is what was displayed in the html result file:
> Cell Error in 'Members'
```
No converter found for type System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
```
After this commit:
✅ All StorytellerRunner.Runner.run_specification theories pass
Note: this looks like a limitation of Storyteller.
=> Fix run_specification for Inline_Aggregation_by_Stream.md

src/Marten/Events/CodeGeneration/MartenIgnoreAttribute.cs
Can't use this handy attribute when it's marked `internal`.
=> Make MartenIgnore public

src/Marten.Testing/Bugs/Bug_1845_async_daemon_skips_events_on_stopall.cs, src/Marten/Events/Projections/Async/ErrorHandling/DaemonErrorHandler.cs
As demonstrated in the issue https://github.com/JasperFx/marten/issues/1845 Async Daemon was skipping events on StopAll exception handling strategy. Fixed it by rethrowing the exception, that sets the ActionBlock faulted, resulting in the ActionBlock dropping all pending events.
=> 1845 async projection skips events on stop

src/Marten/MartenServiceCollectionExtensions.cs
Allows navigation back to the `IServiceCollection`, to allow fluent configuration:
```c#
Host.CreateDefaultBuilder()
.ConfigureServices(services => services
.AddMarten().Services
.AddOptions<MyOptions>());
```
=> Expose Services property from MartenConfigurationExpression

docs/guide/documents/querying/compiled-queries.md, docs/guide/documents/querying/linq/index.md, src/Marten/Events/IEventStore.cs, src/Marten/Events/IQueryEventStore.cs, src/Marten/Events/QueryEventStore.cs, src/Marten/IDocumentSession.cs, src/Marten/IQuerySession.cs, src/Marten/Internal/Sessions/DocumentSessionBase.cs, src/Marten/Internal/Sessions/QuerySession.cs
I achieved that by adding the `IQueryEventStore` interface and `QueryEventStore` implementation.
I'm not entirely proud with the [CreateEventStore](https://github.com/JasperFx/marten/pull/1904/files#diff-629665ba21293b01ff2d61f05c14faeb4da6cc434d3baaa436520fd9ca8ab9beR41) virtual method, but I haven't found a better (less invasive) option, as creating `EventStore` requires passing to-be-created session with `this`. Another alternative would be to have a public setter for the session, but that's even more ugly...
@jeremydmiller, if you have better suggestions, I'm open to updating PR.
=> Added readonly event store methods to IQuerySession

src/Marten.Testing/Logging/DefaultMartenLoggerTests.cs, src/Marten/DefaultMartenLogger.cs
Fix for GH-1888 to prevent DefaultMartenLogger throwing exception when parameter nam and/or value includes {
=> Fix for GH-1888 to prevent DefaultMartenLogger throwing exception 

docs/configuration/prebuilding.md, docs/documents/full-text.md, src/CommandLineRunner/Program.cs, src/CommandLineRunner/TestCommand.cs, src/Marten.AsyncDaemon.Testing/TestingSupport/Trip.cs, src/Marten/Events/Aggregation/AggregateProjection.CodeGen.cs, src/Marten/Events/CodeGeneration/ApplyMethodCollection.cs, src/Marten/Events/CodeGeneration/CreateMethodCollection.cs, src/Marten/Events/CodeGeneration/MethodCollection.cs, src/Marten/Events/CodeGeneration/ShouldDeleteMethodCollection.cs, src/Marten/Events/Projections/EventProjection.cs, src/Marten/Events/Projections/ProjectionOptions.cs, src/Marten/MartenServiceCollectionExtensions.cs, src/Marten/Schema/IDocumentMapping.cs, src/Marten/Schema/SubClassMapping.cs, src/Marten/Storage/StorageFeatures.cs
It's involved, see #1961. Key takeaway was to be careful in how we registered document mappings for projections. Needed to be lazy instead of eager. Also a problem w/ the order of generating types, documents need to go first before events.
=> Fix for GH-1961

build.cmd, build.ps1, build.sh, docs/events/versioning.md, src/Marten.Testing/Events/SchemaChange/NamespaceChange.cs, src/Marten/Events/EventGraph.cs, src/Marten/Events/IEventStoreOptions.cs
Besides that enabled build script run if someone has .NET 6 installed (like me 😅 ).
=> Brought back Event Type Mapping by adding a dedicated MapEventType method to IEventStoreOptions

src/.editorconfig, src/Marten/Events/Aggregation/AsyncLiveAggregatorBase.cs, src/Marten/Events/Daemon/ActionParameters.cs, src/Marten/Events/Daemon/ProjectionDaemon.cs, src/Marten/Services/SystemTextJsonSerializer.cs, src/Marten/Util/SOHSkippingStream.cs, src/Marten/Util/SharedBuffer.cs, src/Marten/Util/StreamExtensions.cs
Another bunch of threading issues fixes. 
A couple of changes should be reviewed carefully:
* `SystemTextJsonSerializer` uses `ArrayPool<byte>.Shared` to buffer data from streams hence it's a  performance penalty for sync versions of 'FromJson()' methods. 
* ~~Inverted sync/async calls for `AsyncLiveAggregatorBase` is a breaking change, so any inheritor will have to override and implement sync `Build()` method~~.  I've figured out the purpose of `AsyncLiveAggregatorBase`. It was absolutely wrong idea. There is no good and safe way to call async code from sync hence I replaced sync method with `throw new NoSupportedException()`. 
I suppose it still deserve merging as it's improves reliability.
=> Fix CA2012 warnings

src/Marten.Testing/Linq/invoking_queryable_through_single_Tests.cs, src/Marten.Testing/Linq/invoking_queryable_through_single_async_Tests.cs, src/Marten/Linq/Parsing/LinqHandlerBuilder.cs
Following query will throw exception if there is more than one document with number 2:
```csharp
session.Query<Target>().Where(x => x.Number == 2).Take(1).Single();
```
When LINQ query with .Single() is parsed, the limit for SQL query is always set to two. I think that the Take(1) should be honored and not be overriden. This PR changes the query parsing to set the limit only if it is not set previously.
=> Do not ignore .Take() when using .Single() in LINQ query

src/Marten.Testing/Linq/previewing_the_command_from_a_queryable_Tests.cs, src/Marten/Linq/SqlGeneration/AnySelectClause.cs, src/Marten/Linq/SqlGeneration/SelectorStatement.cs
Current `Any()` implementation compiles to a query `select (count(*) > 0) as result from public.mt_doc_target as d`. It forces postgres to count all related rows which is obviously redundant work. Fastest query I could imaging would be `select exists as result from (select 1 from public.mt_doc_target as d) as temp`. I haven't figured out an easy way to implement this directly within Marten codebase. Luckily I found a workaround that works: `select 1=1 as result from public.mt_doc_target as d LIMIT 1` and gives almost same execution plan as `exists` based query (see below).
I also deduplicated  `previewing_the_command_from_a_queryable_Tests` and `previewing_the_command_from_a_queryable_in_a_different_schema_Tests` with some string interpolation magic.
These are the execution plans to shows …
=> Any query optimization (avoid counting all rows)

src/Marten.Testing.OtherAssembly/Bug1984/GenericEntity.cs, src/Marten.Testing.ThirdAssembly/Bug1984/Data.cs, src/Marten.Testing.ThirdAssembly/Marten.Testing.ThirdAssembly.csproj, src/Marten.Testing/Bugs/Bug_1984_need_to_recursively_reference_assemblies_in_lamar_code_generation.cs, src/Marten.Testing/Marten.Testing.csproj, src/Marten.sln, src/Marten/Internal/CodeGeneration/DocumentPersistenceBuilder.cs, src/Marten/Internal/CompiledQueries/CompiledQuerySourceBuilder.cs, src/Marten/Internal/WalkReferencedAssemblies.cs
See #1984 for bug description.
A similar bug was fixed in #1851, I've used the same assembly walking strategy to fix this bug.
=> Fix #1984: recursively reference all assemblies for document persistence

src/Marten.AsyncDaemon.Testing/Marten.AsyncDaemon.Testing.csproj, src/Marten.AsyncDaemon.Testing/TestingSupport/DaemonContext.cs, src/Marten.CommandLine/Commands/Projection/ProjectionCommand.cs, src/Marten.Testing/Acceptance/document_inserts.cs, src/Marten.Testing/Bugs/Bug_1891_compiled_query_problem.cs, src/Marten.Testing/Events/Aggregation/aggregate_stream_samples.cs, src/Marten/Events/Aggregation/AggregateProjection.CodeGen.cs, src/Marten/Events/Aggregation/AggregationRuntime.cs, src/Marten/Events/Aggregation/TenantSliceRange.cs, src/Marten/Events/Daemon/HighWater/HighWaterAgent.cs, src/Marten/Events/Daemon/IProjectionDaemon.cs, src/Marten/Events/Daemon/ProjectionDaemon.cs, src/Marten/Events/Daemon/ShardStatusWatcher.cs, src/Marten/Events/Daemon/TenantedEventRange.cs, src/Marten/Linq/Parsing/Methods/StringContains.cs, src/Marten/Schema/DocumentCleaner.cs, src/Marten/Services/BatchQuerying/BatchQueryItem.cs, src/Marten/Services/ManagedConnectionExtensions.cs, src/Marten/Storage/BulkInsertion.cs
A few items I noticed whilst debugging the daemon:
- Fixed compiler directives that were set to .NET 5-only
- Moved to `Parallel.ForEachAsync` for .NET 6 consumers, replacing the `Task.WhenAll` pattern.
- Dispose the token registration within `waitForAllShardsToComplete`
- Ensure all `TaskCompletionSource`'s are created with `RunContinuationsAsynchronously`
- Adjust highwater timer callback so it isn't doing sync-over-async
=> .NET 6/Async Pass

docs/events/projections/view-projections.md
No code changes necessary IMO. The use case was extremely unlikely, and I think a warning in the documentation is good enough here.
=> Warning in docs about limitations of custom grouping. Closes GH-1988

src/Marten.Testing/Events/Bugs/Bug_1995_empty_batch_update_failure.cs, src/Marten/Events/Daemon/ProjectionUpdateBatch.cs
When the async daemon processed a batch of SQL command that comes exactly to the `UpdateBatchSize`, there is an empty page in the collection that ends up throwing a `CommandText is not initialized` error. This checks to make sure there is changes, and if not, exits early
=> Fix #1995 - Early Exit ApplyChanges when Page has No Changes

docs/configuration/json.md, src/Marten.Testing/Events/Projections/QuestMonsters.cs, src/Marten.Testing/Events/Projections/inline_aggregation_with_base_view_class.cs, src/Marten.Testing/Events/Projections/inline_aggregation_with_private_constructor.cs, src/Marten.Testing/Examples/ConfiguringDocumentStore.cs, src/Marten/ISerializer.cs, src/Marten/Services/Json/JsonNetCollectionToArrayJsonConverter.cs, src/Marten/Services/Json/JsonNetContractResolver.cs, src/Marten/Services/Json/JsonNetObjectContractProvider.cs, src/Marten/Services/JsonNetSerializer.cs
- Added `JsonNetObjectContractProvider` to enable private non default constructor resolution for Newtonsoft Json.NET
- Added `NonPublicMembersStorage.NonPublicConstructor` option and updated `JsonNetContractResolver` accordingly
- Added tests and updated docs
=> Added JsonNetObjectContractProvider to enable private non default constructor resolution for Newtonsoft Json.NET

src/Marten.Testing/Linq/Bug_id_field_does_not_hit_id_column.cs, src/Marten/Linq/Parsing/SimpleBinaryComparisonExpressionParser.cs, src/Marten/Linq/Parsing/SimpleEqualsParser.cs
This PR addresses a performance issue where querying over the identity field does not hit the identity column.
BEFORE:
select _ from _ as d where (d.data @> :arg0)
where arg0 = '{"Id":"00ee1302-7109-42e0-bd87-926123931c34"}'
AFTER
select _ from _ as d where (d.id = :arg0)
where arg0 = '00ee1302-7109-42e0-bd87-926123931c34'
=> Treat the Identity Field as a Duplicated Field

src/Marten.AsyncDaemon.Testing/view_projection_end_to_end.cs, src/Marten/Events/Aggregation/AggregateProjection.CodeGen.cs
Fixes #2031 
The test from the original fix has been modified to ensure that the daemon applies the events from the other streams in separate slices rather than all together. The test was flawed as it loaded all 3 events into a slice. The `IsNew` logic looks at the first event to determine that it's a new projection and then applies all 3 events on the same document resulting in no loss of data. When they are applied in separate slices, the data loss does occur as they are no longer all applied on the same document.
=> Ensure ViewProjection uses CrossStreamAggregationRuntime

src/Marten/Events/Daemon/HighWater/HighWaterAgent.cs
This might happen if the agent is stopped straight after starting it, e.g. in a unit test. This is similar to how Dispose protects against the same.
To trigger this I'm using the HotColdCoordinator with Marten 4.3.1
```
[16:45:24 ERR] Error trying to stop the HighWaterAgent
System.NullReferenceException: Object reference not set to an instance of an object.
at Marten.Events.Daemon.HighWater.HighWaterAgent.Stop()
```
=> Protect against null ref in HighWaterAgent.Stop

src/Marten/Events/Daemon/HighWater/HighWaterDetector.cs, src/Marten/Events/Daemon/HighWater/SafeSequenceFinder.cs
Rather than doing a full table scan on the `mt_events` table to filter down to rows past a given timestamp, updates query to take advantage of index by also filtering out rows before the latest safe sequence id
=> Optimizes Safe Sequence Finder using Current Safe Sequence Id

src/Marten.Testing/Linq/query_with_order_by.cs, src/Marten/Linq/Operators/OrderByComparerClause.cs, src/Marten/Linq/Operators/OrderByComparerExpressionNode.cs, src/Marten/Linq/Parsing/LinqHandlerBuilder.cs, src/Marten/Linq/Parsing/MartenQueryParser.cs, src/Marten/Linq/SqlGeneration/Statement.cs
This PR adds linq support for OrderBy methods which takes IComparer<T>. For now, only string properties are supported when using invariant or ordinal string comparers. If "IgnoreCase" string comparer is used, then lower()-call is added to generated SQL.
This PR relies heavily on work done by @lahma in #1542.
=> Add support for case-insensitive order by for strings

src/Marten.Testing/Bugs/Bug_XXXX_select_transform_dictionary.cs, src/Marten/Linq/Parsing/SelectTransformBuilder.cs
If you have query with select that selects dictionary from entity, the query fails because the JSON returned from database cannot be deserialized. Following exception is thrown
```
Newtonsoft.Json.JsonSerializationException
Error converting value "{"Key": "Value", "Key2": "Value2"}" to type 'System.Collections.Generic.Dictionary`2[System.String,System.String]'. Path 'Values', line 1, position 71.
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, …
```
=> Select transform with dictionary fails

build/build.cs, build/build.csproj
SimpleExec 10.0.0 [no longer requires](https://github.com/adamralph/simple-exec/pull/438) separate `windowsName` and `windowsArgs` for executing `.cmd` files which are in `PATH` without specifying the file extension. The resolution of the file paths is done internally in SimpleExec.
I'm raising this PR as a beta test of the feature, in a real world build that relies on it. I hope you don't mind.
=> update SimpleExec from 6.2.0 to 10.0.0-beta.1

build/build.csproj
In beta 2, running `dotnet` on Windows is echoed as just `dotnet` instead of the full path (as in 9.1.0). Similar for any other `.exe` resolved through path.
=> update SimpleExec from 10.0.0-beta.1 to 10.0.0-beta.2

src/CoreTests/Bugs/Bug_2135_open_session_should_use_provided_connection_string.cs, src/CoreTests/MartenServiceCollectionExtensionsTests.cs, src/Marten/MartenServiceCollectionExtensions.cs, src/Marten/Services/MartenActivator.cs, src/Marten/StoreOptions.cs
This PR adds support for asserting database configuration on startup. This feature is implemented the same way as applying all database changes on startup.
If `AssertDatabaseMatchesConfigurationOnStartup` is called for `MartenConfigurationExpression`, during startup `AssertDatabaseMatchesConfigurationAsync` is called for all known databases. As possible configuration mismatch will throw exception this also prevents the application from starting if any database does not match configuration.
=> Add support for asserting database configuration on startup

src/EventSourcingTests/Bugs/Bug_2143_append_exclusive_then_append_throws_when_saving_changes.cs
This PR contains a failing unit test demonstrating that calling AppendExclusive with no events and then calling Append fails with `Marten.Exceptions.EventStreamUnexpectedMaxEventIdException`
=> Failing unit test for bug #2143

src/DocumentDbTests/Bugs/Bug_673_multiple_version_assertions.cs, src/Marten/Events/EventStore.Append.cs
Before the fix the new test will fail with `Unexpected starting version number for event stream 'xxxx', expected 3 but was 2`.
This happened because it wasn't aware of previous calls to `Append`.
Same fix is previous applied for guid identify in https://github.com/JasperFx/marten/commit/b860265961b414b3840bae8bdea0445015febe42
=> Fix concurrency error when calling append several times for string identity

src/Marten/MartenServiceCollectionExtensions.cs
In `SetApplicationProject`, if a `hintPath` was specified it was accidentally discarded - this tiny PR fixes that.
=> fix: set hint path

src/Marten.CommandLine/Marten.CommandLine.csproj, src/Marten/Marten.csproj
Slightly better command line options w/ the new Oakton IStatefulResource model, can play in the new generalized Oakton activator for all stateful resources
=> Upgrade to Weasel 5.3

src/Marten/Events/Daemon/HotColdCoordinator.cs
When `startAllProjections` fails for whatever reason (properly mostly transient db errors) the hot cold coordinator is in a limbo state where some shards could be started and others not. The lock got attained in the first place but the hot cold coordinator still tries to get a lock, but never will.
The proposed solution is to stop the daemon, release the lock and let the hot cold coordinator try to start it again. 
https://github.com/JasperFx/marten/blob/3e6099a6c595bd98573bb57c3e97ba39902330d1/src/Marten/Events/Daemon/HotColdCoordinator.cs#L84-L94
=> Stop daemon and release db lock when exception occur on shard start

src/CoreTests/Logging/DefaultMartenLoggerTests.cs, src/Marten/DefaultMartenLogger.cs
When enabling debug logs the sql parameters was quite spammy
=> Combine sql and parameter(s) to one log statement

docs/.vitepress/theme/custom.css, docs/documents/plv8.md, docs/documents/querying/linq/child-collections.md, docs/documents/querying/linq/include.md, docs/documents/querying/linq/operators.md, docs/events/projections/custom.md
Fixed some headings to resolve navigation issues, and fixed indentation like so:
Becomes
=> Fixed minor styling issues in documentation

src/DocumentDbTests/Bugs/Bug_2223_list_contains_any_generates_invalid_sql.cs, src/Marten/Linq/SqlGeneration/IdSelectorStatement.cs
If query has "contains any" where clause and include Marten generates invalid SQL.
Following query results in error from PostgreSQL:
```csharp
var otherIdsQuery = new[]
{
Guid.NewGuid(),
Guid.NewGuid()
};
var otherTestEntityLookup = new Dictionary<Guid, OtherTestEntity>();
var entities = await session.Query<TestEntity>()
.Include(x => x.OtherIds, otherTestEntityLookup)
.Where(x => x.OtherIds.Any(id => otherIdsQuery.Contains(id)))
.ToListAsync();
```
PostgreSQL error details:
```
Severity: ERROR
SqlState: 42703
MessageText: column "ctid" does not exist
Hint: There is a column named "ctid" in table "d", but it cannot be referenced from this part of the query.
```
I fixed the issue by simply adding table alias into SQL generated by WhereCtIdInSubQuery. Not sure if this might cause problems …
=> Query with "contains any" and include generates invalid SQL

src/Marten/Services/SessionOptions.cs
When Marten handles connection and session, OpenSession does open connection and begin transaction only when Serializable isolation level is used. Async version of OpenSession opens connection and begins transaction always. This PR changes the async version of OpenSession to work the same way as sync version.
=> Do not open transaction by default when using OpenSessionAsync

docs/diagnostics.md, docs/events/archiving.md, src/EventSourcingTests/archiving_events.cs, src/Marten/Events/EventGraph.Processing.cs, src/Marten/Exceptions/InvalidStreamOperationException.cs
`IEventStore.ArchiveStream(<streamIdentifier>)` can be used to archive a stream. One that operation is committed, the stream, along with all its events are marked as archived in the database. However, any subsequent append operations for the stream will append events to the stream as un-archived. That leaves the stream in an inconsistent state, where the stream itself is archived, but with both associated archived and un-archived events.
This enhancement ensures that appending events to an already archived stream is not allowed to prevent this issue.
=> Prevent append operation on archived streams

src/DocumentDbTests/Deleting/deleting_multiple_documents.cs, src/Marten/IDocumentOperations.cs, src/Marten/Internal/Sessions/DocumentSessionBase.Deletes.cs, src/Marten/Internal/Sessions/DocumentSessionBase.cs
Fixes #2271
The goal of this change is to implement a counterpart for the `StoreObjects(IEnumerable<object> documents)` function with a `DeleteObjects(IEnumerable<object> documents)` function.
=> Added the ability to delete a mix of documents

src/Marten/Events/AggregateToExtensions.cs
Changed the type from `IMartenQueryable` to `IQueryable` allowing calls to `AggregateTo` when chained Linq methods are used.
=> Changed AggregateTo extensions receiver type

docs/events/projections/async-daemon.md, src/CommandLineRunner/AsyncDaemonBootstrappingSamples.cs, src/Marten/Events/Daemon/IProjectionDaemon.cs, src/Marten/Events/Daemon/ProjectionDaemon.cs
Internally there is a per-shard timeout of 5 minutes when calling RebuildProjection. This change makes that timeout configurable.
I'm a little unsure about the inclusion of the cancellation token, it feels weird to have two cancellation conditions.
=> Add timeout option to `IProjectionDaemon.RebuildProjection`

src/EventSourcingTests/Aggregation/fetching_inline_aggregates_for_writing.cs, src/Marten/Internal/Storage/IDocumentStorage.cs, src/Marten/Linq/QueryHandlers/LoadByIdArrayHandler.cs, src/Marten/Linq/QueryHandlers/LoadByIdHandler.cs
If aggregate is multi tenanted `EventStore.FetchForWriting` does not return the aggregate for existing stream.
The issue is that LoadByIdHandler adds tenant id parameter with empty value. This value is replaced with actual tenant id in BuildCommand methods. However the FetchInlinedPlan does not use BuildCommand methods and the tenant id is never set for the query fetching the aggregate.
I changed the LoadByIdHandler so that it sets the tenant id value also when adding the parameter. I couldn't come up with reason why this would not work. If there is a reason for not setting the tenant id in LoadByIdHandler, it can be set in FetchInlinedPlan before executing the command.
=> Fetch stream for writing does not return aggregate when it is multi tenanted

src/DocumentDbTests/Bugs/Bug_PR_2277_upsert_deleted_with_unique_key.cs, src/Marten/Internal/UnitOfWork.cs
I found an issue when we have a transaction with more then one document and there are deletion and upsert queries with unique constraint.
**Steps to reproduce:**
- Add document to the table with duplicate field and unique value
- Create a new session 
- Delete document and insert new one with the same unique value
- Do some operation on any other document
- Save the changes
**Result:**
Marten.Exceptions.DocumentAlreadyExistsException is thrown
StorageOperationWithDeletionsComparer sorts the queries in wrong way as deletion documents are on the bottom of list and delete queries are executed after upsert. It causes the error "Marten.Exceptions.DocumentAlreadyExistsException: Document already exists". In case when we have only one document modified sorting is skipped.
=> Fix StorageOperationWithDeletionsComparer

src/DocumentDbTests/Bugs/Bug_2224_Include_needs_to_respect_Take_and_Skip_in_main_body.cs, src/Marten/Linq/Fields/ArrayField.cs, src/Marten/Linq/Includes/IIncludePlan.cs, src/Marten/Linq/Includes/InTempTableWhereFragment.cs, src/Marten/Linq/Includes/IncludeIdentitySelectorStatement.cs, src/Marten/Linq/Includes/IncludePlan.cs, src/Marten/Linq/SqlGeneration/DocumentStatement.cs
Because the temp table was unnesting array collections, the limit was being incorrectly applied to the related documents. This PR attempts to solve that problem by pulling the raw array as a column in the temp table, and deferring the unnesting to the `where` clause. 
@jeremydmiller If you have any feedback on this, I'm all ears, but it does appear to fix the test as written for #2258 and preserve all other tested functionality. The thing I'm the least happy with was the change to the `InTempTableWhereFragment` needing to do this:
```sql
where id in (select unnest(id1) from (select id1 from mt_temptable1 limit 10) as mt_temptable1)
```
It works, and I couldn't think of a better way to apply the limit only to the root document, not to the related documents. But it feels gross all the same.
=> Fix #2258 - Include Loads all Related Documents when Using Limit/Offset

src/DocumentDbTests/MultiTenancy/conjoined_multi_tenancy.cs, src/Marten/Linq/SqlGeneration/WhereFragmentExtensions.cs
When a Where clause in a LINQ statement contains AnyTenant() call and multiple other predicates the generated SQL will add the default tenancy WHERE clause.
This is due to `WhereFragmentExtensions.SpecifiesTenant` using the `Flatten` method that does not recursively flatten a `CompoundWhereFragment` fragment.
I was not sure whether that `Flatten` method should be changed so instead changed the extension method to, without using LINQ to avoid unnecessary allocations, look for a `ITenantWhereFragment` fragment
=> Linq fix for AnyTenant call with a compound Where clause

src/EventSourcingTests/Bugs/Bug_2289_tombstone_events_violate_seq_id_uniqueness.cs, src/Marten/Events/StreamAction.cs
I am open to a better way to handle this. It seemed the cleanest to me to move the setting of the event data before checking the expected versions, that way the tombstone events have all the data they need to be able to set the tenant and sequence.
=> Fix for #2289 - Sets the event data before checking the expected version

src/DocumentDbTests/Bugs/Bug_2211_select_transform_inner_object.cs, src/Marten/Linq/Parsing/SelectTransformBuilder.cs
Fix for https://github.com/JasperFx/marten/issues/2211
Not sure how appropriate the fix is, the issue does seem to be very similar to the one mentioned here https://github.com/JasperFx/marten/pull/2057 - nested class properties are not being deserialized as objects, but as strings and then fail to deserialize back to objects.
=> Fix inner classes not being deserialized when doing Select projections

src/EventSourcingTests/Bugs/Bug_2296_tenant_session_in_grouper.cs, src/EventSourcingTests/Bugs/Bug_tenanted_query_session_in_projection_grouper.cs, src/Marten/Internal/Sessions/DocumentSessionBase.cs, src/Marten/Internal/Sessions/NestedTenantQuerySession.cs, src/Marten/Internal/Sessions/NestedTenantSession.cs, src/Marten/Internal/Sessions/QuerySession.cs
Suspect this is an inconsistency with setting the tenant id. Inspecting inside the grouper I can see that `session.TenantId` is the expected tenant but `session.Events._tenant.TenantId` is `*DEFAULT*`.
Included a fix - Pass the tenant from `NestedTenantSession` and `NestedTenantQuerySession` into the base `QuerySession`. I don't like how this now means there is an optional argument to the query session constructor though.
=> Bug: MultiTenant Session in IAggregateGrouper does not fetch streams

src/Marten/Events/Daemon/ShardAgent.cs
I see the below exception pop up in our logs from time-to-time after a successful rebuild, after the shard has already stopped.
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Marten.Events.Daemon.ShardAgent.ExecuteBatch(ProjectionUpdateBatch batch)
at Marten.Events.Daemon.ShardAgent.<>c__DisplayClass44_0.<<processRange>b__2>d.MoveNext()
--- End of stack trace from previous location ---
at Marten.Events.Daemon.ProjectionDaemon.TryAction(ActionParameters parameters)
```
I assume it's either the tracker or command block already being set to null by this point.
=> Fix null ref source in shard agent

src/Marten/Marten.csproj
The motivation for upgrading this package is to fix an issue with creating database patches for some versions of Postgres.
I submitted a fix for that issue a few weeks ago, but given that the source code in Weasel has been extracted out of this project,
the issue still exists in Marten.
See https://github.com/JasperFx/weasel/pull/67 for more details. 
Upgrading `Weasel.Postgresql` to `5.7.1`, which contains the fix, addresses the issue.
=> Reference Weasel.Postgresql 5.7.1

docs/diagnostics.md, src/Marten.AsyncDaemon.Testing/TestingSupport/TripStream.cs, src/Marten.AsyncDaemon.Testing/basic_async_daemon_tests.cs, src/Marten.AsyncDaemon.Testing/event_fetcher_tests.cs, src/Marten.AsyncDaemon.Testing/rebuilds_with_serialization_or_poison_pill_events.cs, src/Marten/Events/Aggregation/TenantSliceGroup.cs, src/Marten/Events/Daemon/EventFetcher.cs, src/Marten/Events/Daemon/IShardAgent.cs, src/Marten/Events/Daemon/ProjectionDaemon.cs, src/Marten/Events/Daemon/RebuildingEventFetcher.cs, src/Marten/Events/Daemon/ShardAgent.cs, src/Marten/Events/EventDocumentStorage.cs, src/Marten/Exceptions/EventDeserializationFailureException.cs
Work in progress. This is to make the rebuild projection process able to skip over serialization or poison pill events, while providing options for "fast fail"
=> Resilient projection rebuilds

build/build.cs, docs/events/versioning.md, src/EventSourcingTests/SchemaChange/MultipleSchemaVersions.cs, src/EventSourcingTests/SchemaChange/Upcasters.cs, src/Marten.Testing/Harness/OneOffConfigurationsContext.cs, src/Marten/Events/CodeGeneration/CreateMethodCollection.cs, src/Marten/Events/CodeGeneration/DefaultAggregateConstruction.cs, src/Marten/Events/EventGraph.cs, src/Marten/Events/EventMapping.cs, src/Marten/Events/IEventStoreOptions.cs, src/Marten/Services/Json/Transformations/EventUpcaster.cs
PR fixed the mapping for upcasting function to allow multiple schema version handling.
Before that change, it was:
- old event type name => new CLR type,
- new CLR type => old event type name
Now it'll be:
- old event type name => new CLR type,
- new event type name => new CLR type,
- new CLR type => new event type name
That enables multiple schema version handling.
I also added a set of syntactic sugar for multiple schema version registration. It enables automated convention with the version suffix.
=> Fixed mapping of the upcasting functions to allow multiple schema versions handling

src/CoreTests/using_optimized_artifact_workflow.cs, src/Marten/MartenServiceCollectionExtensions.cs
From [Microsoft Docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostenvironmentenvextensions.isenvironment?view=dotnet-plat-ext-6.0):
> Environment names are generally specific to an application. Libraries designed for use in many different applications should avoid coupling behavior to specific environment names.
fixes #2367
=> Avoid using IHostEnvironment.IsDevelopment in OptimizeArtifactWorkflow

src/DocumentDbTests/Reading/Linq/query_with_source_reference_comparision_tests.cs, src/Marten/Linq/Filters/IgnoredWhereClauseFragment.cs, src/Marten/Linq/Parsing/WhereClauseParser.cs, src/Marten/Linq/SqlGeneration/DocumentStatement.cs
The inspiration for this enhancement to the LINQ provider comes from my attempt to integrate Marten with the HotChocolate GraphQl library (https://chillicream.com/docs/hotchocolate/). That library comes with some useful out the box features like filtering (https://chillicream.com/docs/hotchocolate/fetching-data/filtering).
For that feature to work, I simply need a data source from which I can retrieve some `IQueryable<T>`.
Let's say I have the following object:
```
public class Book
{
public Guid Id { get; set; }
public string Content { get; set; }
public bool IsPopular { get; set; }
public int Rating { get; set; }
}
```
And that I want to execute the following query:
```
{
books (where: {rating: {gt: 50}}) {
id
content
isPopular
rating
}
}
```
HotChocolate will generate a LINQ expression …
=> Ignore where clause expressions such as `where([x] != null)` and `where([x] == null)`

src/DocumentDbTests/Reading/Linq/LinqExtensionsTests.cs, src/DocumentDbTests/Reading/Linq/query_with_IsSubsetOf_Tests.cs, src/DocumentDbTests/Reading/Linq/query_with_is_one_of_Tests.cs, src/Marten.Testing/Documents/Target.cs, src/Marten/Linq/Parsing/Methods/IsOneOf.cs, src/Marten/Linq/Parsing/Methods/IsSubsetOf.cs, src/Marten/Linq/Parsing/Methods/IsSupersetOf.cs, src/Marten/LinqExtensions.cs
@borgez, this is intentional; use `IsSubsetOf` instead. Because of how `params []` in C# work, it was possible to call `In` and `IsOneOf` for List or other generic collections. This is unintended usage. I restricted the `In` and `IsOneOf` LINQ operators to regular fields and added missing tests. 
Unfortunately, the compiler will still allow it, but we'll get at least more meaningful error information.
Fixes #2357.
=> Restricted In Linq operator to regular fields

src/DocumentDbTests/Indexes/duplicated_field.cs, src/Marten/Internal/CodeGeneration/BulkLoader.cs, src/Marten/Schema/Arguments/UpsertArgument.cs
It seems that we only supported `Guid` and `Enum`, ignoring the rest of the value types.
Fixes  #1668
=> Fixed bulk insert of documents with nullable value types (e.g. int?)

src/CoreTests/ability_to_use_an_existing_connection_and_transaction.cs, src/Marten/Internal/Sessions/AmbientTransactionLifetime.cs
Adding `BeginTransaction()` for sync `Apply` method. `BeginTransactionAsync(token)` is already present in the async apply.
Before the change a sync query operation would result in the error `System.InvalidOperationException: 'Connection property has not been initialized.'` when using `SessionOptions.ForCurrentTransaction`.
=> Create connection and enlist transaction for async operations

docs/migration-guide.md, docs/troubleshoot.md
The PLV8Enabled option no longer exists as of https://github.com/JasperFx/marten/issues/1812, so the mention in the FAQ is confusing.
Add a note to the migration guide to direct people to the separate nuget package.
=> Add migration note about PLV8 removal

src/IssueService/Controllers/IssueController.cs, src/Marten.AspNetCore.Testing/web_service_streaming_tests.cs, src/Marten.AspNetCore/QueryableExtensions.cs
The optional argument wasn't used before. This change sets the response statuscode to the given value.
Or should this argument be dropped? It's not available on the other methods, but that would be a breaking change.
=> QueryableExtensions.WriteSingle use optional argument onFoundStatus

src/Marten/Events/Projections/ProjectionOptions.cs
These methods are `void`, so won't return something thus the comment is misplaced.
=> Fixed xml doc comments for ProjectionOptions

docs/documents/execute-custom-sql.md, src/CoreTests/executing_arbitrary_sql_as_part_of_transaction.cs
This PR adds a note about parameter casting to [Execute custom SQL in session](https://martendb.io/documents/execute-custom-sql.html).
Closes https://github.com/JasperFx/marten/issues/2422
See https://github.com/JasperFx/marten/issues/2422#issuecomment-1345342217
=> Added note to docs about parameter casting

src/Marten/Marten.csproj
Basically same thing as last time: https://github.com/JasperFx/marten/pull/2217
I understand you might be reluctant to publish this on such an old branch, but i thought i would give it a shot anyway.
As also stated last time, we have a lot of microservices and it is no easy task to migrate from v3 to v5. We have been migrating alot of our services since last time, but it is no small undertaking for us to convert every single one, we simply need more time.
=> Fix a compatibility issue with .NET 7 and Marten 3.x

src/EventSourcingTests/EventStreamUnexpectedMaxEventIdExceptionTransformTest.cs, src/Marten/Exceptions/EventStreamUnexpectedMaxEventIdException.cs, src/Marten/Services/EventStreamUnexpectedMaxEventIdExceptionTransform.cs
A previous update to Npgsql (my best guess 😇) broke the exception transformer for optimistic concurrency errors on events.
As also noted [here](https://github.com/JasperFx/marten/pull/1500), test for this transform is a bit tricky but I haven't had any issues with these tests local but a couple of spins in the pipeline should show any improprieties 🤞
=> Fix transformation for unique contraint on events

src/Marten.CommandLine/Commands/Projection/ProjectionCommand.cs
Fixes https://github.com/JasperFx/marten/issues/2450
=> Fixed ProjectionCommand dispose / using bug

src/Marten/Events/Daemon/HotColdCoordinator.cs
If an error occurs during polling for ownership, the daemon will just idle. This change will ensure the coordinator keeps polling for ownership on errors.
The errors we see is transient errors like `System.IO.EndOfStreamException: Attempted to read past the end of the stream.` , but I think it makes sense to keep polling on all kind of errors.
=> Hot cold coordinator: Don't stop polling on errors.

src/Marten/Internal/Operations/StorageOperation.cs
Hello everyone,
I have not digged to deep into the issue but i observe an error when rebuilding the projection. I ran into the issue where i got an exception from postprocessUpdateAsync while trying to execute
`await reader.IsDBNullAsync(0, token).ConfigureAwait(false)`
after
`!await reader.ReadAsync(token).ConfigureAwait(false)`
since there is no data so IsDBNullAsync throw an exception. When compared to the non async method postprocessUpdate all is written in one line with conditional or operator ||. For me it looks like it should behave the same. What do you think?
best regards
=> Fix side effect on postprocessUpdateAsync

src/Marten/Events/Daemon/ProjectionDaemon.cs
Hello everyone,
when calling RebuildProjection<TView> shardTimeout is not passed in the subroutine in the case of
`typeof(TView).CanBeCastTo(typeof(ProjectionBase)) && typeof(TView).HasDefaultConstructor()`
and defaults always to 5.Minutes().
best regards
=> Fix RebuildProjection<TView> shardTimeout param passing

src/Marten.PLv8.Testing/Patching/Bug_1173_patch_typenamehandling_bug.cs, src/Marten.PLv8.Testing/Patching/Bug_2460_parallel_patching.cs, src/Marten.PLv8.Testing/Patching/PatchExpressionTests.cs, src/Marten.PLv8/Transforms/TransformSchema.cs, src/Marten.Testing/Harness/OneOffConfigurationsContext.cs
The Patching API database schema feature didn't use the concurrent dictionary but a regular one. That was causing issues if multiple requests were trying to access it at once. Added `ImHashMap` to have thread-safe access and additional locking not to have redundant loading of a patch function js file. Added necessary tests.
Fixes #2460 
_**Note:** Best to review with [whitespace changes hidden](https://github.com/JasperFx/marten/pull/2462/files?diff=split&w=1) as I did some small reformatting._
=> Fix multithreading issues in Patching API

src/DocumentDbTests/Bugs/Bug_2327_using_identity_extension_on_class_with_invalid_type_id_field.cs, src/Marten/Schema/DocumentMapping.cs
While working on #2391, I found this bug that may cause some strange behaviors. When setting DocumentMapping.IdMember to an invalid type ArgumentOutOfRangeException was thrown, but IdMember was charged to this invalid type anyway.
=> Fix DocumentMapping.IdMember setter

src/Marten.NodaTime.Testing/Acceptance/noda_time_acceptance.cs, src/Marten.NodaTime.Testing/Bug_2307_JObject_in_dictionary_duplicated_field.cs, src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj, src/Marten.NodaTime.Testing/TestData/TargetWithDates.cs, src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten.NodaTime/NodaTimeExtensions.cs
Creating an index on a nullable nodatime type fails when generating types with the following:
```
System.InvalidOperationException
Compilation failures!
CS0234: The type or namespace name 'LocalDate' does not exist in the namespace 'Marten.NodaTime' (are you missing an assembly reference?)
CS1503: Argument 1: cannot convert from 'NodaTime.LocalDate?' to 'Marten.NodaTime.LocalDate?'
```
The problem started in 5.11 after this commit https://github.com/JasperFx/marten/commit/61483008e1ab04c14f9e9baafae93c43cd4767da
Problematic Diff in generated document `GetNullable<NodaTime.LocalDate>`:
**Before 5.11**
```
public override void LoadRow(Npgsql.NpgsqlBinaryImporter writer, Dinero.Voucher.Aggregates.VoucherAggregate document, Marten.Storage.Tenant tenant, Marten.ISerializer serializer)
{ …
```
=> Add index for nullable `LocalDate`

Analysis.Build.props, src/AspNetCoreWithMarten/AspNetCoreWithMarten.csproj, src/CoreTests/CoreTests.csproj, src/DocumentDbTests/DocumentDbTests.csproj, src/EventPublisher/EventPublisher.csproj, src/EventSourcingTests/EventSourcingTests.csproj, src/IssueService/IssueService.csproj, src/Marten.AspNetCore.Testing/Marten.AspNetCore.Testing.csproj, src/Marten.AsyncDaemon.Testing/Marten.AsyncDaemon.Testing.csproj, src/Marten.CommandLine.Tests/Marten.CommandLine.Tests.csproj, src/Marten.CommandLine/Marten.CommandLine.csproj, src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj, src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten.PLv8.Testing/Marten.PLv8.Testing.csproj, src/Marten.Testing/Marten.Testing.csproj, src/Marten/Marten.csproj, src/MartenBenchmarks/MartenBenchmarks.csproj, src/samples/MinimalAPI/MinimalAPI.csproj
Admin Shutdown (`57P01`) error mean that database is not available (e.g. it's restarting). Npgsql from version 6 supports connection pool reset behind the scenes for this scenario (see https://github.com/npgsql/npgsql/issues/2896). I added the wrapper in Weasel (see: https://github.com/JasperFx/weasel/pull/79) to return `false` for this case and allow retry mechanisms (that we already have in Marten) for database creation.
That should (hopefully) fix failing tests in CI.
Bumped also dependencies to the latest versions.
@jeremydmiller fyi.
=> Bumped Weasel version to enable Advisory Locks retries when got Admin Shutdown (57P01) Postgres error was thrown

azure-pipelines.yml, src/EventSourcingTests/EventStreamUnexpectedMaxEventIdExceptionTransformTest.cs, src/Marten.PLv8.Testing/Patching/Bug_2460_parallel_patching.cs
- Improved CI configuration to support tests added in #2462.
- Run schema migrations upfront in the Patching tests.
- Fixes #2480 - Increased parallelisation in `throw_transformed_exception_with_details_available` and adjusted error message test.
=> Fixed flakiness related CI tests parallelisation issues

src/DocumentDbTests/Bugs/optimistic_concurrency_with_update_method.cs, src/Marten/Internal/Sessions/DocumentSessionBase.cs
I've added support of concurrency check when `Update` method of `DocumentSessionBase` is used. It is based on implementation used for `Store` method.
=> Concurrency check for Update in DocumentSessionBase

src/DocumentDbTests/Reading/BatchedQuerying/batched_querying_acceptance_Tests.cs, src/Marten/Linq/QueryHandlers/UserSuppliedQueryHandler.cs
The issue is that if you pass in a raw `WHERE` clause or `ORDER BY` clause that contains a condition with a nested `SELECT` statement, `UserSuppliedQueryHandler` thinks that it already contains the document `SELECT` statement since it was using a `Contains` check rather than a `StartsWith` check. This PR changes the check from a `Contains` to a `StartsWith`.
=> Fix issue with UserSuppliedQueryHandler when criteria contains 'SELECT' clause

docs/configuration/storeoptions.md, docs/documents/sessions.md, docs/scenarios/aggregates-events-repositories.md, src/CoreTests/Bugs/Bug_2135_open_session_should_use_provided_connection_string.cs, src/CoreTests/DatabaseMultiTenancy/using_per_database_multitenancy.cs, src/CoreTests/DatabaseMultiTenancy/using_static_database_multitenancy.cs, src/CoreTests/ability_to_use_an_existing_connection_and_transaction.cs, src/EventSourcingTests/ScenarioAggregateAndRepository.cs, src/Marten.AsyncDaemon.Testing/multi_stream_aggregation_end_to_end.cs, src/Marten.Testing/Examples/OpeningASessionAsync.cs, src/Marten/DocumentStore.cs, src/Marten/Events/Daemon/ProjectionDaemon.cs, src/Marten/IDocumentStore.cs
This will be more self-explanatory about intentions and won't get Rider and other IDEs to suggest async versions. Removed Obsolete attribute from methods with StoreOptions
=> Renamed asynchronous session creation to include explicit Serializable name

docs/configuration/storeoptions.md, docs/documents/multi-tenancy.md, docs/events/configuration.md, docs/events/projections/index.md, docs/events/projections/multi-stream-projections.md, src/CoreTests/Sessions/TenantedSessionFactoryTests.cs, src/DocumentDbTests/Configuration/document_policies.cs, src/EventSourcingTests/Aggregation/AggregationTestingSupport.cs, src/EventSourcingTests/Aggregation/aggregation_projection_validation_rules.cs, src/EventSourcingTests/Json/SystemTextJsonRecordSerializationTests.cs, src/EventSourcingTests/Projections/MultiTenants/ConjoinedTenancyProjectionsTests.cs, src/Marten.AsyncDaemon.Testing/TestingSupport/TripProjectionWithCustomName.cs, src/Marten/DocumentStore.cs, src/Marten/Events/Aggregation/AggregationRuntime.cs, src/Marten/Events/Aggregation/EventSlice.cs, src/Marten/Events/Aggregation/GeneratedAggregateProjectionBase.Validation.cs, src/Marten/Events/EventGraph.cs, src/Marten/Events/IEventStoreOptions.cs, src/Marten/MartenRegistry.cs, src/Marten/Sessions/TenantedSessionFactory.cs
1. Enabled the possibility of applying projections with different Conjoined Tenancy scopes for projections.
2. Enabled global projection for events with a conjoined tenancy style.
3. Added possibility to specify that document can be single tenanted (`SingleTenanted` option) when the global convention is to have multi-tenanted.
| SESSION     | SLICE       | STORAGE   | RESULT          |
|-------------|-------------|-----------|-----------------|
| DEFAULT     | DEFAULT     | SINGLE    | THE SAME        |
| DEFAULT     | DEFAULT     | CONJOINED | THE SAME        |
| DEFAULT     | NON-DEFAULT | SINGLE    | THE SAME        |
| DEFAULT     | NON-DEFAULT | CONJOINED | NEW NON-DEFAULT |
| NON-DEFAULT | DEFAULT     | SINGLE    | NEW DEFAULT     |
| NON-DEFAULT | DEFAULT     | CONJOINED | THE SAME …
=> Enabled the possibility of applying projections with different Conjoined Tenancy scopes for projections.

Analysis.Build.props, src/CoreTests/CoreTests.csproj, src/DocumentDbTests/DocumentDbTests.csproj, src/EventPublisher/EventPublisher.csproj, src/EventSourcingTests/EventSourcingTests.csproj, src/Marten.AspNetCore.Testing/Marten.AspNetCore.Testing.csproj, src/Marten.CommandLine/Marten.CommandLine.csproj, src/Marten.NodaTime/NodaTimeExtensions.cs, src/Marten.PLv8.Testing/Marten.PLv8.Testing.csproj, src/Marten.Testing/Marten.Testing.csproj, src/Marten/Marten.csproj, src/Marten/Storage/StorageFeatures.cs
Per @Hawxy at [Discord conversation](https://discord.com/channels/1074998995086225460/1088112401418825799/1088119007258882218), `NpgsqlTypeMapping` is causing the issue when starting multiple Marten instances in parallel:
````
Object reference not set to an instance of an object.
at Weasel.Postgresql.PostgresqlProvider.<>c__DisplayClass15_0.<GetTypeMapping>b__0(NpgsqlTypeMapping mapping)
at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
at Weasel.Postgresql.PostgresqlProvider.GetTypeMapping(Type type)
at Weasel.Postgresql.PostgresqlProvider.ResolveDatabaseType(Type type)
at Weasel.Postgresql.PostgresqlProvider.GetDatabaseType(Type memberType, …
```
=> Bumped Weasel version to fix concurrency issue during Marten startup related to NpgsqlTypeMapping

docs/configuration/hostbuilder.md, docs/events/projections/aggregate-projections.md, docs/events/projections/live-aggregates.md, src/EventSourcingTests/Bugs/Bug_2528_projections_should_handle_each_event_once.cs, src/Marten/Events/Aggregation/GeneratedAggregateProjectionBase.CodeGen.cs, src/Marten/Events/Aggregation/GeneratedAggregateProjectionBase.cs, src/Marten/Events/CodeGeneration/CallApplyAggregateFrame.cs, src/Marten/Events/CodeGeneration/CallCreateAggregateFrame.cs, src/Marten/Events/CodeGeneration/CreateDefaultMethod.cs, src/Marten/Events/CodeGeneration/CreateMethodCollection.cs
Fixes #2528
Expected outcome: Each event passed into a projection is handled a maximum of once, either with a `Create` or an `Apply` method.
Old behaviour: If the first event in a stream has matching `Create` and `Apply` methods, both would be called.
New behaviour: If a `Create` method matches, that event is then skipped when iterating over apply event methods.
Example of issue:
```c#
public record IncrementEvent{}
public record CounterProjection(Guid Id, int Counter)
{
public static CounterProjection Create(IncrementEvent @event, IEvent metadata)
{
return new CounterProjection(metadata.StreamId, 1);
}
public CounterProjection Apply(IncrementEvent @event, CounterProjection current)
{
return current with {Counter = current.Counter + 1};
}
}
[Fact]
public async Task …
```
=> Ensure events with both `Create` and `Apply` are only ever handled once

docs/configuration/storeoptions.md, docs/documents/identity.md, docs/documents/storage.md, src/CoreTests/CoreTests.csproj, src/DocumentDbTests/Bugs/Bug_1563_user_friendly_warning_about_public_type.cs, src/DocumentDbTests/Bugs/hashset_contains.cs, src/DocumentDbTests/Configuration/DocumentMappingTests.cs, src/DocumentDbTests/DocumentDbTests.csproj, src/DocumentDbTests/Writing/Identity/Sequences/CombGuidIdGenerationTests.cs, src/DocumentDbTests/Writing/Identity/Sequences/DocumentIdStrategyTests.cs, src/EventPublisher/EventPublisher.csproj, src/EventSourcingTests/Bugs/Bug_2296_tenant_session_in_grouper.cs, src/EventSourcingTests/EventSourcingTests.csproj, src/Marten.AsyncDaemon.Testing/TestingSupport/TestLogger.cs, src/Marten.CommandLine.Tests/Marten.CommandLine.Tests.csproj, src/Marten.CommandLine.Tests/ProjectionControllerTests.cs, src/Marten.CommandLine/Commands/Projection/ConsoleView.cs, src/Marten.CommandLine/Marten.CommandLine.csproj, src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten.PLv8.Testing/Marten.PLv8.Testing.csproj, src/Marten.Testing.OtherAssembly/ShortGuid.cs, src/Marten.Testing/Marten.Testing.csproj, src/Marten/Events/Aggregation/SingleStreamProjection.cs, src/Marten/Events/EventMapping.cs, src/Marten/Events/Projections/ProjectionWrapper.cs, src/Marten/Events/TestSupport/ProjectionScenario.Assertions.cs, src/Marten/Exceptions/DocumentIdTypeMismatchException.cs, src/Marten/Internal/CompiledQueries/CompiledQuerySourceBuilder.cs, src/Marten/Marten.csproj, src/Marten/Schema/DocumentMapping.cs
Using a list works fine so a tad bizarre. This is a bit of rough edge for us as we try to use Hashsets in more places.
```
System.InvalidOperationException
Nullable object must have a value.
at System.Nullable`1.get_Value()
at Weasel.Postgresql.SqlGeneration.CommandParameter..ctor(Object value)
at Weasel.Postgresql.SqlGeneration.WhereFragment.<>c.<.ctor>b__0_0(Object x)
at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
at Weasel.Postgresql.SqlGeneration.WhereFragment..ctor(String sql, Object[] parameters)
at Marten.Linq.Parsing.Methods.IsInGenericEnumerable.Parse(IFieldMapping mapping, IReadOnlyStoreOptions options, MethodCallExpression expression) in C:\Source\marten\src\Marten\Linq\Parsing\Methods\IsInGenericEnumerable.cs:line 24
at …
```
=> Add failure scenario for hashset contains

src/CoreTests/Bugs/Bug_2603_similar_named_props.cs, src/CoreTests/Bugs/Bug_9003_similar_named_props.cs, src/DocumentDbTests/Indexes/duplicated_field.cs, src/Marten/Linq/Fields/FieldCollection.cs, src/Marten/Schema/DocumentMapping.cs
When parsing expressions, marten will cache expression paths for future reuse. Unfortunately the caching key is not specific enough. For example, the following nested properties on document x:
* `x.Foo.Bar.Baz`
* `x.FooBar.Baz`
* `x.Foo.BarBaz`
* `x.FooBarBaz`
Will all be cached with a key of `FooBarBaz`. This can lead to incorrect query generation (see included tests).
The solution is to update the cache key to separate all properties with a `.`.
=> Fix: Similarly named where clauses get incorrectly reused

src/CoreTests/Bugs/Bug_2602_include_with_conjoined_tenancy.cs, src/CoreTests/Bugs/Bug_9002_includes_with_conjoined_tenancy_should_work - Copy.cs, src/Marten/Linq/Includes/IIncludePlan.cs, src/Marten/Linq/Includes/IncludeIdentitySelectorStatement.cs, src/Marten/Linq/Includes/IncludePlan.cs
To reproduce:
Run any of the [include examples from the marten documentation](https://martendb.io/documents/querying/linq/include.html) using a connection with multitenancy/conjoined tenancy enabled. 
Caused by the session not being passed down into the `IncludePlan` so the tenant value cannot be fetched.
Fixes #2583
=> Fix: Runtime error when parsing a query with `Include()` in a multitenant database

src/DocumentDbTests/Reading/Linq/dictionary_is_translated.cs, src/Marten.Testing/Documents/Target.cs, src/Marten/Linq/Parsing/DictionaryExpressions.cs
Also permits any subclass of  `IDictionary`, as existing support was limited to the `IDictionary<string, x>` interface.
I loosened the type requirements for `.Contains` as well, but the current implementation only works if an interface is passed due to Remotion treating it as a different type of expression.
=> Add Dictionary ContainsKey support for value types

src/Marten.AsyncDaemon.Testing/DocumentTrackingByIdentity/CustomProjection_follow_up_operations.cs, src/Marten.AsyncDaemon.Testing/DocumentTrackingByIdentity/EventProjectionWithCreate_follow_up_operations.cs, src/Marten.AsyncDaemon.Testing/DocumentTrackingByIdentity/EventProjection_follow_up_operations.cs, src/Marten/Events/Daemon/ProjectionDocumentSession.cs, src/Marten/Internal/Sessions/DocumentSessionBase.cs, src/Marten/Internal/Sessions/QuerySession.cs
`ProjectionDocumentSession` didn't handle `DocumentTracking` session options and always returned a lightweight session. Updated the code to return the correct tracking mode depending on the `EnableDocumentTrackingByIdentity` setting.
@jameswoodley, @Hawxy FYI
@ugugun, @alexander-paynova I think it might also be the fix issue we discussed around nulls in async projection handling.
=> Enable async projections to respect `EnableDocumentTrackingByIdentity` in regular mode, not only during the rebuild

docs/documents/querying/linq/sql.md, docs/documents/querying/sql.md, src/DocumentDbTests/Reading/query_by_sql.cs, src/Marten.Testing/Documents/User.cs, src/Marten/Linq/QueryHandlers/UserSuppliedQueryHandler.cs
Permit querying any [npgsql mapped type](https://www.npgsql.org/doc/types/basic.html) within custom SQL.
=> Fixed querying for primitive types in custom SQL

src/EventSourcingTests/Projections/CodeGeneration/ProjectionCodeGenerationTests.cs, src/Marten/Events/Aggregation/GeneratedAggregateProjectionBase.Validation.cs, src/Marten/Events/Projections/ProjectionOptions.cs, src/Marten/Schema/DocumentMapping.cs, src/Marten/Storage/MartenDatabase.DocumentCleaner.cs, src/Marten/Storage/StorageFeatures.cs
Changed LiveStreamAggregation implementation to set the `SkipSchemaGeneration` property for `DocumentMapping` instead of entirely removing it from storage.
Updated implementation for schema generation to skip such mappings.
It's more hotfix, than a real revamp, but without introducing breaking changes, it'll be harder to change it.
Fixes #2645
Relates to #2610
=> Added test for LiveStreamAggregation code file generation

docs/introduction.md
I took inspiration from the Nest.js docs, which are praised by the community https://nextjs.org/docs:
Rewrote to show people first what we do, then how we do it and how they can benefit.
Outlined the most important features so people won't miss them.
Removed:
- link to obsolete videos,
- information about NRT, as it should be a standard now and is not adding much value for the reader of the introduction (too many tech details).
=> Rewrote introduction docs to make it more accessible and user friendly

docs/documents/querying/linq/async-enumerable.md, src/CoreTests/Exceptions/MartenCommandExceptionTests.cs, src/CoreTests/SessionOptionsTests.cs, src/Marten.sln, src/Marten/Exceptions/InvalidConnectionStringException.cs, src/Marten/Exceptions/MartenCommandException.cs, src/Marten/Exceptions/MartenExceptionTransformer.cs
That may happen when the connection string is invalid or is not matching the database configuration (e.g. wrong password).
Added `InvalidConnectionStringException` - a dedicated exception type for when the connection string is invalid. Npgsql is throwing a bit of confusing `ArgumentException`, so I think that it'll be more accessible to add more context.
Fixes #2670
=> Fixed Marten Exceptions transformations when NpgslCommand is null

docs/.vitepress/config.ts, docs/cSpell.json, docs/events/projections/healthchecks.md, src/Marten.AsyncDaemon.Testing/AsyncDaemonHealthCheckExtensionsTests.cs, src/Marten.AsyncDaemon.Testing/AsyncDaemonHealthCheckExtensionsTestsHelpers.cs, src/Marten/Events/Daemon/AsyncDaemonHealthCheckExtensions.cs, src/Marten/Marten.csproj
Added health check for the daemon
Note: Something went wrong when merging the latest oringin-changes to the fork so the original PR got deleted. :(
=> Added AsyncDaemonHealthCheck

src/Marten.AsyncDaemon.Testing/TestingSupport/DaemonContext.cs, src/Marten.AsyncDaemon.Testing/rebuilds_with_serialization_or_poison_pill_events.cs, src/Marten/Events/Daemon/ProjectionDaemon.cs, src/Marten/Events/Daemon/ProjectionUpdateBatch.cs, src/Marten/Events/Daemon/ShardAgent.cs, src/Marten/Internal/Storage/LightweightDocumentStorage.cs, src/Marten/Services/SessionOptions.cs, src/Marten/StoreOptions.cs
Fixes #2686.
**Set `DeadLetterEvent` as single tenanted for conjoined tenancy.** A dead letter event represents an event skipped for the particular projection. It references that event at a specific global event store sequence. Thus, it has to be global and does not have a tenant. If we rebuild the projection, all read models will be rebuilt using events from all tenants.
Added test ensuring that conjoined tenancy is handled correctly.
**Enhanced ProjectionUpdateBatch disposal.** There could be a race condition when the session was released, but the processing Queue wasn't completed, which caused the session to be null. Added nullable annotations to make that explicit and fixes accordingly (by checking the cancellation token and implementing disposal consistently).
@BrettGFleischer …
=> Set `DeadLetterEvent` as single tenanted for conjoined tenancy

src/Marten/Events/Aggregation/TenantSliceGroup.cs
In projections, if the Id is null, it should not invoke the apply method.  Currently it completely fails the application.
=> Check for null identifier on add event.

src/EventSourcingTests/Projections/inline_aggregation_with_custom_projection_configuration.cs, src/Marten/Events/Projections/ProjectionOptions.cs
As discussed with @oskardudycz on discord, here is a little change that allows to customize the snapshot projection.
This helps for cases where one wants to use `.Snapshot<T>(..)` but likes to customize the default `SingleStreamProjection<T>`.
=> Allow customization of the snapshot projection

docs/events/projections/ioc.md, src/EventSourcingTests/Projections/inline_aggregation_with_custom_projection_configuration.cs, src/EventSourcingTests/Projections/projections_with_IoC_services.cs
The issue was in the race condition, as Async Daemon in tests was started both through the hosted service and then manually to wait for the projection shard.
Added also dedicated DaemonLockId value for async projection with IoC integration tests. It seems like it may be clashing with other async daemons running on the same database when using the default lock id.
=> Adjusted Async projection test with IoC injection to remove flakiness

Analysis.Build.props, Directory.Build.props, src/CoreTests/CoreTests.csproj, src/DocumentDbTests/DocumentDbTests.csproj, src/EventPublisher/EventPublisher.csproj, src/EventSourcingTests/EventSourcingTests.csproj, src/Marten.AspNetCore.Testing/Marten.AspNetCore.Testing.csproj, src/Marten.AspNetCore/Marten.AspNetCore.csproj, src/Marten.AsyncDaemon.Testing/Marten.AsyncDaemon.Testing.csproj, src/Marten.CommandLine.Tests/Marten.CommandLine.Tests.csproj, src/Marten.CommandLine/Marten.CommandLine.csproj, src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj, src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten.PLv8.Testing/Marten.PLv8.Testing.csproj, src/Marten.PLv8/Marten.PLv8.csproj, src/Marten.Testing/Marten.Testing.csproj, src/Marten/Events/EventGraph.GeneratesCode.cs, src/Marten/Internal/CodeGeneration/DocumentProviderBuilder.cs, src/Marten/Internal/CompiledQueries/CompiledQueryCodeFile.cs, src/Marten/Internal/SecondaryStoreConfig.cs, src/Marten/Marten.csproj, src/Marten/Util/CodeGenExtensions.cs, src/MartenBenchmarks/MartenBenchmarks.csproj
Updated also dependencies to latest versions.
=> Bumped to 6.3.0

docs/documents/identity.md
Fixed some typos and added some punctuation where necessary.
=> Update Document Identity (identity.md)

src/EventSourcingTests/Projections/MultiTenants/ConjoinedTenancyProjectionsTests.cs, src/Marten/Events/Aggregation/CustomProjection.cs
This is a follow up to PR #2497 applying the method `UseTenancyBasedOnSliceAndStorage` also when using `Custom Aggregation Projections`, instead of only to `Single Stream Projections`.
This fixes the issue described in https://github.com/JasperFx/marten/issues/2363#issuecomment-1753734588.
There are some additional issues described in this other comment https://github.com/JasperFx/marten/issues/2363#issuecomment-1621043060. 
I think those should be fixed now too. The aggregate document is now always loaded using the correct tenant session (see [Single Stream Aggregations here](https://github.com/JasperFx/marten/blob/974a1cf1960bb13a176847ecd55c5cd1bc723545/src/Marten/Events/Aggregation/AggregationRuntime.cs#L70) and [Custom Aggregation Projections in this PR right …
=> Fix wrong session-tenacity used in Custom Aggregation Projections

.github/workflows/docs-prs.yml, .github/workflows/docs.yml, docs/.vitepress/config.ts, docs/events/projections/index.md
Updated the entry in the TOC to match the title of the page.
=> Doc update: `Custom Projection` -> `Custom Aggregations` to avoid duplicate entry

.github/workflows/docs-prs.yml, .github/workflows/docs.yml, docs/events/metadata.md, docs/events/projections/aggregate-projections.md, docs/events/projections/event-projections.md, docs/events/projections/index.md, docs/events/querying.md, src/Marten/Events/Projections/Examples.cs
In the docs there's `Event<T>` but since https://github.com/JasperFx/marten/commit/cb0d92b05d8e13550ee5b3f95493c9d84c9af119 that type is `internal`. Thus changed the occurences to `IEvent<T>`.
Commit 647a25b9b1d53cb43e49c4d45ddbb24575d1daf5 is cherry-picked from https://github.com/JasperFx/marten/pull/2774 to (hopefully) avoid conflicts.
=> Replaced (internal) `Event<T>` with `IEvent<T>` in docs

src/IssueService/Controllers/JsonController.cs, src/Marten.AspNetCore.Testing/web_service_streaming_tests.cs, src/Marten.AspNetCore/QueryableExtensions.cs
A typical use case occurs when you wish to write a custom query to summarize information and directly pass the response to the HttpResponse, without the need to map and serialize it through a DTO class.
=> Support to write json with raw SQL to HttpContext

src/DocumentDbTests/Bugs/querying_child_collections_impact_each_other.cs
Queries that work on their own, don't work if one runs before the other.
The docs are a little bit hazy on this example, should this work at all? 
or like nested in Any() both sides have to be arrays?
```
var guids = new List<Guid> { guid1, new Guid() }; 
var result = await query.Query<Two>()
.Where(x => guids.Contains(x.Id))
.ToListAsync();
result.Count.ShouldBe(1);
```
if Contains shouldn't be used like this I think it's important to throw an exception early, this was quite the head scratcher. 
There is a current work around using `IsOneOf` or `In` so no rush.
=> querying child collections impacts each other

src/DocumentDbTests/Bugs/Bug_2433_include_with_take.cs
I've created failing test for issue #2433, where included related documents are not loaded correctly. It seems that it happens only in case when data are not ordered so unit test contains both options - with and without ordering.
=> Add failing test for #2433

src/DocumentDbTests/Bugs/Bug_2660_deletes_in_complex_order.cs, src/Marten/Events/Daemon/ProjectionUpdateBatch.cs, src/Marten/Internal/Operations/StorageOperation.cs, src/Marten/Internal/Sessions/DocumentSessionBase.Deletes.cs, src/Marten/Internal/UnitOfWork.cs, src/Marten/Services/ISessionWorkTracker.cs
making IDocumentSession.Delete() operations purge pending operations …involving that same document. Closes GH-2660
=> Improved Document Deletions

src/Marten/IMartenLogger.cs
Not sure if this is something you may be interested in.  It's a minor change to the `ConsoleLogger` to output actual parameter values for arrays, rather than just something like `p0: System.Collections.Generic.List`1[System.Guid]`.  Instead output is:
```
p0: [0]: 018bcff3-2301-49b6-9558-324553be0cb6; [1]: 018bf295-a374-447e-bed1-767e98aa48aa; [2]: 118bf295-a374-447e-bed1-767e98aa48aa; [3]: 218bf295-a374-447e-bed1-767e98aa48aa; [4]: 318bf295-a374-447e-bed1-767e98aa48aa;  + 1 more
```
Arbitrarily only displays the first 5 values to avoid clogging up logs too much.
Made my life debugging a test slightly easier, but not sure if it is of general use.
=> Modified ConsoleLogger to output array parameter values

docs/diagnostics.md, docs/documents/querying/linq/child-collections.md, docs/documents/querying/linq/strings.md, src/LinqTests/Acceptance/string_filtering.cs, src/LinqTests/ChildCollections/query_against_child_collections.cs, src/Marten.Testing/Documents/Target.cs, src/Marten.Testing/Documents/User.cs, src/Marten/Linq/Parsing/Methods/Strings/StringIsNullOrEmpty.cs, src/Marten/Linq/Parsing/Methods/Strings/StringIsNullOrWhiteSpace.cs, src/Marten/Linq/Parsing/Methods/Strings/StringStartsWith.cs, src/Marten/LinqParsing.cs
- Added new `ISqlFragment`   for `IsNullOrEmpty` and ``IsNullOrWhiteSpace`
- Added new `IMethodCallParser` implementations accordingly,
- Added tests and extended current test suite with more pemutations
Fixes #2815
@Hawxy FYI
_Note: I recommend to check it with whitespace hidden: https://github.com/JasperFx/marten/pull/2823/files?diff=split&w=1_
=> Added support for IsNullOrEmpty and IsNullOrWhiteSpace string operators in Linq queries

src/EventSourcingTests/Projections/EventProjections/EventProjectionOrderingTests.cs, src/Marten/Events/Projections/AsyncEventProjectionBase.cs, src/Marten/Events/Projections/SyncEventProjectionBase.cs
Based on the [Discord discussion](https://discord.com/channels/1074998995086225460/1074999076896112661/1130518719857164328) with @migajek, we discovered that Event Projection it running everything by the stream, which may cause issues around the global ordering of event processing.
This PR is changing that behaviour as it may be misleading and causing unpredicted issues. 
Fixes #2657
=> Fixed EventProjection to respect global ordering

src/DocumentDbTests/Reading/query_by_sql.cs, src/Marten/Linq/QueryHandlers/UserSuppliedQueryHandler.cs
- Add functionality to support custom sql query using `with select` format
- Fixes GH-2753
=> Add functionality to support custom sql query using `with select` format

docs/events/storage.md
As I see from https://github.com/JasperFx/marten/issues/1641 then `mt_append_event` is gone, so it should go from the docs too.
---
Just for my understanding: that function got removed to have correct handling of concurrent appends?
=> Update storage.md to remove `mt_append_event`

src/EventSourcingTests/Bugs/Bug_2883_ievent_not_working_as_identity_source_in_multistream_projections.cs, src/Marten/Events/Aggregation/EventSlicer.cs, src/Marten/Events/Projections/SingleStreamEventGrouper.cs
Allows using IEvent<TEvent> as a type parameter for Identity in MultiStreamProjections.
Closes #2883
=> feat: Allow Identity to use IEvent<TEvent>

docs/documents/querying/linq/paging.md, documentation/documentation/documents/querying/paging.md, src/Marten/Linq/QueryHandlers/LinqConstants.cs
When retrieving query statistics the use of count(*) instead of count(1) is faster for Postgres.
https://www.postgresql.org/message-id/flat/df354b76-a645-73fc-9645-4508e5291d71%40gmx.net
=> fix: Use count(*) instead of count(1) for performance reasons

src/Marten/Patching/IPatchExpression.cs, src/Marten/Patching/PatchExpression.cs, src/Marten/Patching/PatchOperation.cs, src/Marten/Patching/PatchingExtensions.cs, src/Marten/Schema/SQL/mt_jsonb_patch.sql, src/PatchingTests/Patching/patching_api.cs
Refer to GH-699 for details. You can perform patch operations as below:
```csharp
theSession.Patch<Target>(target.Id)
.Set(x => x.Number, 10)
.Increment(x => x.Inner.Number, 10);
```
=> Add functionality to chain patch operations on multiple fields

docs/events/projections/healthchecks.md, src/Marten.AspNetCore/Daemon/AsyncDaemonHealthCheckExtensions.cs, src/Marten.AsyncDaemon.Testing/AsyncDaemonHealthCheckExtensionsTests.cs
First implementation version to discuss for:
https://github.com/JasperFx/marten/issues/2945
This PR also fixes bug in the previous implementation: Unhelathy state when no events stored and HighWaterMark not present.
disclaimer:
I may use `FakeTimeProvider` from `Microsoft.Extensions.TimeProvider.Testing` for tests, but:
```
Install failed (project: Marten.AsyncDaemon.Testing, package: Microsoft.Extensions.TimeProvider.Testing v8.1.0) Package restore failed. Rolling back package changes for 'Marten.AsyncDaemon.Testing'. Detected package version outside of dependency constraint: Lamar 12.1.0 requires Microsoft.Extensions.DependencyInjection.Abstractions (>= 6.0.0 && 8.0.0) but version Microsoft.Extensions.DependencyInjection. ... e this issue. Marten.AsyncDaemon.Testing -> …
```
=> feat(#2945): AsyncDaemonHealthCheck - add `maxSameLagTime` option

docs/getting-started.md
The previous command used paket add nuget ...
nuget is the default and can be omitted.
The Paket CLI also gives a warning: "Please use the new syntax: 'nuget' is the default argument and should be omitted."
=> docs(getting-started.md): use new paket-cli syntax

src/Marten/Events/AsyncProjectionTestingExtensions.cs
`Task.Factory.StartNew()` will not await the `WaitForNonStaleProjectionDataAsync()` inside.
So the extension method on the `IDocumentStore` will return "completed" before the actual task on the DB is done.
=> Fix non awaited tasks in WaitForNonStaleProjectionDataAsync()

docs/configuration/retries.md, src/Marten.Testing/Examples/ErrorHandling.cs, src/Marten/StoreOptions.cs, src/Marten/Util/ResilientPipelineBuilderExtensions.cs
=> Allow to extend Resiliency Policies via `.ExtendPolly()`

src/EventSourcingTests/Bugs/Bug_9999_fetch_for_writing_async_projection_with_no_additional_events_should_return_projection.cs, src/Marten/Events/Aggregation/GeneratedAggregateProjectionBase.CodeGen.cs
When applying events to update an async projection snapshot, existing behavior returns null instead of the snapshot if there are no events to apply.
From codegen:
```csharp
public override GroupProjection Build(IReadOnlyList<IEvent> events, IQuerySession session, GroupProjection snapshot)
{
if (!events.Any()) return null;  // This is the problem, there are no additional events to apply, should return snapshot
GroupProjection groupProjection = null; // this also appears to be a no-op
// ...
return snapshot;
}
```
Testing this has been a headache - I am clearly missing something when it comes to properly testing generated code. In theory the included test matches my applications code but does not reproduce the issue. Additionally the following other bugs are identified:
- Calling …
=> fix: FetchForWritng() async projection returns null if there are no additional events to apply

src/Marten/Events/Daemon/Coordination/AdvisoryLock.cs
Noticed this never recovered after I forced a node failover today. `Broken` is unimplemented and doesn't do anything.
=> Fix faulty connection handling in advisory lock

docs/.vitepress/config.mts, docs/documents/querying/advanced-sql.md, docs/documents/querying/index.md, src/DocumentDbTests/Reading/advanced_sql_query.cs, src/Marten/IQuerySession.cs, src/Marten/Internal/Sessions/QuerySession.Querying.cs, src/Marten/Linq/QueryHandlers/AdvancedSqlQueryHandler.cs, src/Marten/Services/SystemTextJsonSerializer.cs, src/Marten/Storage/Metadata/RevisionColumn.cs, src/Marten/Storage/Metadata/VersionColumn.cs
AdvancedSqlQueryAsync<T, ...>(sql, ...) allows to perform more complex SQL queries than would be possible with Query<T>(sql). It allows to query documents, scalars and deserializable JSON objects or any combination of these returned as a tuple.
This also allows to query for related documents. Metadata mapping, dirty tracking etc. for documents is fully supported. The full SQL must be provided (no "magic" SQL building) so the user is responsible to provide all the columns needed by Marten in the correct order.
Currently result tuples with up to 3 elements are possible (a single result type will not be returned as a tuple). This could be easily extend, but then I would move all the overloads into a partial class. For the same reason I have not created an extra overload for the async methods …
=> Advanced SQL query

src/Marten/Marten.csproj
It seems Marten was already using the v8 stuff from Polly.Core, but still depending on Polly (legacy): https://www.pollydocs.org/migration-v8.html
I changed the dependency and bumped to latest: https://github.com/App-vNext/Polly/releases
=> Switch to Polly.Core & Bump version

src/Marten/Services/Json/Transformations/SystemTextJson/JsonTransformations.cs
`JsonDocument` uses pooled memory that's supposed to be returned after usage.
=> Fix missing disposal in STJ upcasters

src/Marten/Events/Aggregation/GeneratedAggregateProjectionBase.CodeGen.cs, src/Marten/Events/Projections/GeneratedProjection.cs
We encountered a issue where our service would throw a `NullReferenceException` during startup, necessitating a reboot for recovery. This problem arises particularly when multiple operations execute in parallel at startup, such as `Events.AggregateStreamAsync<T>` and `Events.Append(...) + SaveChanges`. This situation triggers the compilation/build of generated types through different execution paths but not in a synchronized manner.
Through debugging, we observed that the setters for our aggregate in the generated document were not set when the error occurred. This led us to scrutinize the compile/build code, particularly the assembleTypes method, where the essential processing happens. We identified a specific flaw where the lock code checks the `_liveGeneratedType` property, but the …
=> Refactor type readiness check to avoid `NullReferenceException`

docs/documents/querying/advanced-sql.md, src/CoreTests/DocumentSchemaResolverTests.cs, src/DocumentDbTests/Reading/advanced_sql_query.cs, src/Marten/IDocumentSchemaResolver.cs, src/Marten/IReadOnlyStoreOptions.cs, src/Marten/StoreOptions.cs
Closes #3125 
As per the above issue, the usage is as follows:
```csharp
IQuerySession session;
var schema = session.DocumentStore.Options.Schema;
var a = schema.DatabaseSchemaName;  // "public"
var b = schema.EventsSchemaName;    // "public" // can be different
var c = schema.For<User>();            // "public.mt_doc_user"
var d = schema.For<UserProjection>();  // "public.mt_doc_userprojection"
var e = schema.ForStreams();           // "public.mt_streams"
var f = schema.ForEvents();            // "public.mt_events"
var g = schema.ForEventProgression();  // "public.mt_event_progression"
var h = schema.For<User>(qualified: false);            // "mt_doc_user"
var i = schema.For<UserProjection>(qualified: false);  // "mt_doc_userprojection"
var j = schema.ForStreams(qualified: false); …
```
=> Ability to fetch db names for documents/aggregates from marten options.

docs/.vitepress/config.mts, docs/events/streaming/index.md, docs/events/streaming/sink.md, docs/events/streaming/source.md, docs/events/subscriptions.md, src/Marten.AsyncDaemon.Testing/AsyncOptionsTests.cs, src/Marten.AsyncDaemon.Testing/Subscriptions/subscriptions_end_to_end.cs, src/Marten/Events/Daemon/AsyncOptions.cs, src/Marten/Events/Daemon/ISubscriptionAgent.cs, src/Marten/Events/Daemon/Internals/SubscriptionAgent.cs, src/Marten/Events/Daemon/ProjectionDaemon.Rebuilding.cs, src/Marten/Events/Daemon/ProjectionDaemon.cs, src/Marten/Storage/IMartenDatabase.cs, src/Marten/Storage/StandinDatabase.cs
Way more power around setting subscription starts
Logic for determining the starting position of subscriptions
Refactoring on AsyncOptions before additional position rules
Put the starting position logic for subscriptions in AsyncOptions
=> Being able to specify where an event subscription starts

src/Marten/Marten.csproj
Continuation of our previous yearly requests: https://github.com/JasperFx/marten/pull/2431
We have still not fufilled our goal of converting every microservice away from Marten 3.x 🙁  
We are however progressing nicely, but have also met some setback due to this bug: https://github.com/JasperFx/marten/pull/3121 (which btw was fixed by an employee at our company, so we do contribute back 🥳).
.NET 7 is going end-of-support pretty soon, so we want to migrate away as soon as possible. Because of this we sincerely hope to get some more time to do the upgrades through this PR. We are pretty confident that we are able to convert everything before .NET 8 goes end-of-support, so hopefully this will be our last request 😄 🤞
=> Add .NET 8 compatibility with Marten 3.x

src/DocumentDbTests/Bugs/Bug_3173_fulltextindex_should_map_properties.cs, src/Marten/Schema/DocumentMapping.cs, src/Marten/Schema/Indexing/FullText/FullTextIndexDefinitionFactory.cs
Closes #3173 
A couple of small typos that seemed to happen when moving the index code into Weasel
=> fix fulltext index definitions

src/Marten/Linq/MartenLinqQueryable.cs
* add fix to use type in enumerate
I wasn't sure what to add unit-test-wise, and most of the tests failed for me locally, so I didn't add any.
Resolves #3182
=> Fix / 3182 - Non generic enumerate exception

docs/configuration/hostbuilder.md, docs/schema/migrations.md, src/CoreTests/MartenServiceCollectionExtensionsTests.cs, src/Marten/Internal/Sessions/AutoClosingLifetime.cs, src/Marten/Storage/IMartenDatabase.cs, src/Marten/Storage/MartenDatabase.Execution.cs, src/Marten/Storage/StandinDatabase.cs, src/Marten/StoreOptions.cs, src/MultiHostTests/00_init.sql, src/MultiHostTests/MultiHostConfigurationContext.cs, src/MultiHostTests/MultiHostTests.cs, src/MultiHostTests/MultiHostTests.csproj, src/MultiHostTests/docker-compose.yaml
Requires https://github.com/JasperFx/weasel/pull/126
This is a draft for the time being to see if the design is suitable. I've tried to achieve this with the least amount of code changes possible. Docs yet to be written.
Some considerations:
- `NpgsqlMultiHostDataSource` registers itself in the DI container as a normal data source, so marten won't explicitly know it's a multi host source until it tries to fetch a connection from it. If marten has no defaults for multi host usage then the data source will return _any_ connection type and potentially cause unexpected errors as it tries to write against a read replica. For this reason, I've baked in some sane fallbacks for marten & weasel. 
- If a `NpgsqlMultiHostDataSource` is present we won't target the replica by default, it's up to the …
=> Support NpgsqlMultiHostDataSource

src/Marten/StoreOptions.cs, src/MultiTenancyTests/MultiTenancyTests.csproj, src/MultiTenancyTests/using_master_table_multi_tenancy_with_datasource.cs
I've changed the check for master table multi-tenancy options to allow passing the `DataSource` property without passing `ConnectionString`.
=> Allow using only DataSource in master table multi tenant options

docs/configuration/storeoptions.md, docs/schema/index.md, docs/schema/migrations.md, src/CoreTests/StoreOptionsTests.cs, src/Marten/Services/SystemTextJsonSerializer.cs, src/Marten/StoreOptions.cs
=> Allow initial System.Text.Json.JsonSerializerOptions to be a copy

src/DaemonTests/multistream_data_teardown_on_rebuild.cs, src/Marten/Events/Daemon/AsyncOptions.cs, src/Marten/Events/Daemon/ProjectionDaemon.Rebuilding.cs
It's a repro for this discussion on Discord.
=> TeardownDataOnRebuild = false prevents deleting existing projections

src/LinqTests/Operators/async_enumerable.cs, src/Marten/Linq/MartenLinqQueryProvider.cs, src/Marten/Linq/MartenLinqQueryable.cs
TotalResult will not be available before enumeration of the result started. But I think, this might still be useful for providing progress information when iterating over a large result set.
This is the easiest / least "intrusive" implementation I could come up with.
=> Make ToAsyncEnumerable() set the QueryStatistics.TotalResult

src/Marten/Events/Daemon/ProjectionDaemon.Rebuilding.cs
Couldn't catch/assert the exception in a automated test but I did some local testing using the project mentioned in Discord.
=> Fix: TeardownDataOnRebuild = false must not throw unique constraint exception on multiple rebuilds

docs/documents/querying/advanced-sql.md, src/DocumentDbTests/Reading/advanced_sql_query.cs, src/Marten/IAdvancedSql.cs, src/Marten/IQuerySession.cs, src/Marten/Internal/Sessions/QuerySession.AdvancedSql.cs, src/Marten/Internal/Sessions/QuerySession.Querying.cs, src/Marten/Internal/Sessions/QuerySession.cs, src/Marten/Linq/QueryHandlers/AdvancedSqlQueryHandler.cs
There's now a new interface on IAdvancedSql that wraps all advanced sql query methods and adds new methods to stream the results via IAsyncEnumrable.
The old AdvancedSql*-methods are marked as obsolete and delegate to the new methods.
The new AdavancedSql methods are implemented as explicit interface implementations on the QuerySession class as a separate partial class. The alternative would be to make IQuerySession.Advanced return a separate implementation of IAdvancedSql. Let me know, if you prefer this and I will change the PR.
=> Add AdvancedSql.StreamAsync<>()

docs/configuration/multitenancy.md, docs/configuration/storeoptions.md, docs/documents/multi-tenancy.md, docs/events/projections/custom.md, docs/events/projections/multi-stream-projections.md, docs/schema/cleaning.md, src/DocumentDbTests/DocumentDbTests.csproj, src/DocumentDbTests/SessionMechanics/reset_all_data_usage_ihost.cs, src/Marten.Testing/Examples/DocumentCleanerExamples.cs
Adds samples for the `IHost` cleanup / reset methods added in 7.16.0 (13d901d216dca4bf3d92fd1e122bded2c704b996).
Also updates the cleanup docs to include Event cleanup and shows async versions instead of obsolete synchronous versions.
=> Docs: add IHost cleanup / reset samples

src/Marten/Events/Daemon/Coordination/ProjectionCoordinator.cs
This avoids the problem with exceptions thrown if StopAsync is called more than once.
Closes GH-3237
=> Moved dispose of old CancellationTokenSource in ProjectionCoordinator to right before creation

src/DaemonTests/Subscriptions/subscriptions_end_to_end.cs, src/EventSourcingTests/Projections/projections_with_IoC_services.cs, src/Marten/MartenServiceCollectionExtensions.cs
IServiceCollection.AddMarten supports adding IoC-aware projections and subscriptions through AddProjectionWithServices  and AddSubscriptionWithServices .
IServiceCollection.AddMartenStore lacks this feature.
This PR aims to bring the same functionality to IServiceCollection.AddMartenStore
=> Add AddProjectionWithServices and AddSubscriptionWithServices to .AddMartenStore

src/DocumentDbTests/Bugs/SelfForeignKeyBugs.cs, src/Marten/Internal/UnitOfWork.cs
This allows operations with same priority, to keep their relative order.
In my case, it keeps the order intact between Upsert-operations for Folders.
The test I added successfully reproduced the issue, and works now after the small change to `UnitOfWork.Sort`.
=> Improve UnitOfWork.Sort to use a stable sorting algorithm

src/CoreTests/Bugs/Bug_3274_include_pagedlist_with_mapped_tenantid.cs
Created a unit test to verify the bug where pagedlist is unable to create a query for type with tenantId mapped to document  when using .Include
=> Include PagedList with mapped TenantId

src/DocumentDbTests/Writing/bulk_loading.cs, src/Marten/Internal/CodeGeneration/BulkLoader.cs, src/Marten/Internal/CodeGeneration/BulkLoaderBuilder.cs
This fixes 2 issues:
- A massive performance issue where not joining or updating on tenant id meant that no index could be used
- The bug where if the same Id exists in multiple tenants then an update would happen instead of an insert.
Also has a small tweak to calling binay import to use the async method where appropriate.
=> fix: Tenanted bulk loading should consider tenant id as part of document identity

src/Marten/Events/Aggregation/AggregationRuntime.cs, src/Marten/Events/Aggregation/ByStreamId.cs, src/Marten/Events/Aggregation/ByStreamKey.cs, src/Marten/Events/Aggregation/CustomProjection.cs, src/Marten/Events/Aggregation/EventSlice.cs
Found as part of https://github.com/JasperFx/marten/issues/3307, if you start 1000 streams and have 1 inline projection, then there will be 1000 calls to fetch the current inline projection, one for each stream. By testing if the slicer is for single streams and the sliced events represent the start of a stream, we can eliminate these calls.
=> Avoid wasted db round trips by not loading single stream projections for new streams

src/Marten/Events/Daemon/Internals/EventLoader.cs, src/Marten/Events/Daemon/Internals/EventPage.cs, src/Marten/Events/Daemon/Internals/SubscriptionAgent.cs, src/Marten/Events/Daemon/ProjectionDaemon.cs
I ran into this today when I updated a minor version of nodatime and had half my entities disappear. Turns out an exception was being thrown during deserialization and it was causing the ceiling calculation to skip everything after the exception. Not fun.
=> Fix event load exceptions causing rebuilds to finish early

src/Marten/AdvancedOperations.cs, src/Marten/Events/Daemon/AsyncOptions.cs, src/Marten/Storage/StorageFeatures.cs, src/Marten/StoreOptions.Registration.cs, src/Marten/StoreOptions.cs
`IList` is a bit of a miserable type as it's missing `.AddRange`. One of least useful interfaces to expose and I try to avoid it.
=> Change IList -> List in Public API

src/DocumentDbTests/Writing/bulk_loading.cs, src/Marten/Internal/CodeGeneration/BulkLoaderBuilder.cs
Using "LIKE" and "INCLUDING DEFAULTS" is required to e.g. set mt_deleted to the default falue FALSE, otherwise it will be set to NULL.
=> Create temp table for bulk loading with "LIKE" clause

src/DaemonTests/AsyncDaemonHealthCheckExtensionsTests.cs, src/Marten.AspNetCore/Daemon/AsyncDaemonHealthCheckExtensions.cs
Not a good permanent solution, but fixes this for now
=> Health checks multi tenancy workaround

src/Marten/Events/Projections/ProjectionOptions.cs
We need the non-generic version to be used to disable schema generation for the type
=> Prevent accidental usage of generic Add for live projections

docs/events/projections/aggregate-projections.md
Updates the documentation so that it says 'Multi-Stream Projections' instead of 'Cross-Stream Projections'. 
The page and document that the user is redirected when clicking on 'Cross-Stream Projections' is actually 'Multi-Stream Projections'. The same page is present in other redirects with the proper name.
=> Update 'Cross-Stream Projections' to 'Multi-Stream Projections'

Directory.Build.props, src/Marten.AspNetCore/Marten.AspNetCore.csproj, src/Marten.NodaTime/Marten.NodaTime.csproj, src/Marten.PLv8/Marten.PLv8.csproj, src/Marten/LinqParsing.cs
Update LinqParsing to use separate cache of resolved method parsers by module of the method to 6.x. Add the same fix in GH-3372
=> Update LinqParsing to use separate cache of resolved method parsers by module of the method to 6.x

src/Marten/Internal/Sessions/QuerySession.Execution.cs
This PR is related to this issue: https://github.com/JasperFx/marten/issues/3375. Please see my issue for a repro of the issue.
I was having issues that polly wasn't retrying, even though it appeared that the retry policy was being used. 
So I did some tracing. It turned out that the policy returned successfully. Which is weird, because my query was failing. 
I also noticed that the catch block in the linq provider (https://github.com/JasperFx/marten/blob/master/src/Marten/Linq/MartenLinqQueryProvider.cs#L131) wasn't being hit. 
this gave me the idea that we weren't awaiting in the right place. Turns out that was the case.
The resilience pipeline wasn't using async, which meant that it was successfully building a Task, not awaiting said task.
Could you point me to a good place where I can …
=> fix await with polly

src/DocumentDbTests/ForeignKeys/configuring_foreign_key_fields.cs, src/DocumentDbTests/ForeignKeys/foreign_keys.cs, src/Marten/Schema/DocumentMapping.cs
This only requires to NOT create a duplicate field, because there already is an id column.
I think this is very usable when having a 1:1 relationship between different document types.
=> Allow id to have a foreign key reference

docs/documents/identity.md, docs/events/projections/aggregate-projections.md, src/EventSourcingTests/Aggregation/aggregation_projection_validation_rules.cs, src/EventSourcingTests/Aggregation/strong_typed_identifiers_on_aggregates_must_be_nullable.cs, src/EventSourcingTests/Aggregation/using_guid_based_strong_typed_id_for_aggregate_identity.cs, src/EventSourcingTests/Aggregation/using_string_based_strong_typed_id_for_aggregate_identity.cs, src/EventSourcingTests/EventSourcingTests.csproj, src/Marten/Events/Aggregation/ByStreamId.cs, src/Marten/Events/Aggregation/ByStreamKey.cs, src/Marten/Events/Aggregation/GeneratedAggregateProjectionBase.cs, src/Marten/Events/Aggregation/SingleStreamProjection.cs, src/Marten/Events/Aggregation/TenantSliceGroup.cs, src/Marten/Internal/CodeGeneration/BulkLoaderBuilder.cs, src/Marten/Internal/CodeGeneration/DocumentStorageBuilder.cs, src/Marten/Internal/Storage/DocumentStorage.cs, src/Marten/StoreOptions.Identity.cs, src/Marten/StoreOptions.MemberFactory.cs, src/StressTests/ability_to_use_an_existing_connection_and_transaction.cs, src/ValueTypeTests/StrongTypedId/guid_based_document_operations.cs
Docs for strong typed identifiers and aggregates
Assertion that the aggregate id needs to be nullable for Marten
Can use string based strong typed identifiers with single stream aggregations
wip: past async single stream projections, had to add LoadManyAsync support to document storage
=> Supporting strong typed identifiers for aggregated projections

docs/events/projections/index.md, documentation/documentation/events/projections/index.md
This limitation no longer applies, according to https://github.com/JasperFx/marten/discussions/3431#discussioncomment-10726662
=> docs: Clarify warning about metadata in inline projections

src/Marten/Linq/Members/ChildCollectionMember.cs, src/Marten/Linq/Members/ValueCollections/SelectManyValueCollection.cs, src/Marten/Linq/Members/ValueCollections/SimpleElementMember.cs, src/Marten/Linq/Members/ValueCollections/ValueCollectionMember.cs
Changed accessibility of some IQueryableMember implementations to make it easier for users to create bespoke implementations by inheriting from them. Lays the ground work for F# DU linq querying support. 
When i'm done, i will first experiment my implementation on my side for a couple of weeks to ensure the workflow is convenient and battle-tested before upstreaming it back to Marten.
=> Changed accessibility of some IQueryableMember implementations

docs/events/projections/aggregate-projections.md
TLDR; expanded the comment in the code to remind devs to start the Asyn Daemon when using async projection.
In the code example for aggregate projections an example is given using an Asynchronous projection. The example given will not work out of the box as the Async Daemon is not started in the Marten bootstrap / config. 
I found this confusing and wasted an hour trying to debug when in fact I should have just read further to discover the Async Daemon is not enabled by default but ... DMMT (Don't make me think) . 
A simple additional comment to remind devs to read forward can fix this, unfortunately its not possible to add a hyperlink in a code block in GitHub markdown but the additional text in the comment should hopefully be enough to make a new Marten dev aware that something must be …
=> Extend comment for Aggregate projections async code example - remind devs to start async daemon 

src/Marten/Events/Operations/EstablishTombstoneStream.cs
Adds the `is_archived` column to the insert columns and sets it in the `ON CONFLICT` PK's if `UseArchivedStreamPartitioning`.
Ref #3514
=> Fix for #3514

src/EventSourcingTests/QuickAppend/quick_appending_events_workflow_specs.cs, src/EventSourcingTests/appending_events_workflow_specs.cs, src/Marten/Events/Projections/EventSlice.cs, src/Marten/Events/StreamAction.cs
I did a more detailed scan of where and when Event.Id might get assigned, and also stumbled upon `e.Id = Guid.NewGuid();` in `EventSlice.cs`.
I think this should use a CombGuid instead, just like all other cases, so I changed that as well.
This fixes issue #3533
=> Fix StreamAction.AddEvent not assigning an Event.Id

docs/documents/indexing/foreign-keys.md
`_.Schema.For<Issue>().ForeignKey(i => i.BugId, "bugtracker", "bugs", "id");` should not introduce a dash (I hope)
=> Fixed minor issue in Update foreign-keys.md

src/Marten/Linq/SqlGeneration/IScalarSelectClause.cs
Made IScalarSelectClause.cs public to allow to define custom IValueTypeMember implementations. Required to implement IValueTypeMember.BuildSelectClause(fromObject).
=> Made IScalarSelectClause public

src/EventSourcingTests/FetchForWriting/fetching_inline_aggregates_for_writing.cs, src/Marten/Events/Fetching/FetchInlinedPlan.cs
**Fixes #3597: InvalidCastException in FetchForWriting**
This PR resolves #3597, where the `FetchForWriting<T>` (the overload accepting an expected version) would throw an `InvalidCastException` under the following conditions:
- The aggregate is Inline.
- `UseIdentityMapForAggregates = true`.
- Fixed the bug in `FetchInlinedPlan.cs`.
- Added tests specifically for the bug.
- I only wrote tests for the `Guid` identifier case. Many of the existing tests target both `Guid` and `string` identifier aggregates. While my tests should cover the scenario effectively, I am happy to add tests for the `string` variants if needed. Let me know if this is required.
- I should note that many of the tests in the `StressTests` project failed, but they fail for me with or without my changes.
This is my …
=> Fixes #3597: InvalidCastException in FetchForWriting

docs/documents/execute-custom-sql.md, docs/documents/querying/advanced-sql.md, docs/documents/querying/linq/sql.md, docs/documents/querying/sql.md, src/CoreTests/executing_arbitrary_sql_as_part_of_transaction.cs, src/DocumentDbTests/Reading/advanced_sql_query.cs, src/DocumentDbTests/Reading/query_by_sql.cs, src/LinqTests/Bugs/Bug_3087_using_JsonPath_with_MatchesSql.cs, src/Marten.Testing/Examples/QueryBySql.cs, src/Marten/Events/Projections/Flattened/CallUpsertFunctionFrame.cs, src/Marten/Events/Projections/Flattened/DeleteRowFrame.cs, src/Marten/IAdvancedSql.cs, src/Marten/IDocumentOperations.cs, src/Marten/IQuerySession.cs, src/Marten/Internal/Operations/ExecuteSqlStorageOperation.cs, src/Marten/Internal/Sessions/DocumentSessionBase.cs, src/Marten/Internal/Sessions/QuerySession.AdvancedSql.cs, src/Marten/Internal/Sessions/QuerySession.Json.cs, src/Marten/Internal/Sessions/QuerySession.Querying.cs, src/Marten/Internal/Sessions/QuerySession.cs, src/Marten/Linq/MatchesSql/MatchesSqlExtensions.cs, src/Marten/Linq/MatchesSql/MatchesSqlParser.cs, src/Marten/Linq/QueryHandlers/AdvancedSqlQueryHandler.cs, src/Marten/Linq/QueryHandlers/UserSuppliedQueryHandler.cs, src/Marten/Services/BatchQuerying/BatchedQuery.cs, src/Marten/Services/BatchQuerying/IBatchedQuery.cs
The `char placeholder` param is always before the `string sql` param. This is to ensure that the overload is backwards compatible.,
Updated all methods that accept parameters except for:
- Sync methods that are marked obsolete
- `MatchesJsonPath` - This should probably be marked as obsolete as the placeholder overload does the same thing but better.
Todo:
=> Add overload that allows a custom parameter placeholder.

src/EventSourcingTests/Projections/SingleStreamProjectionTests.cs, src/Marten/Events/Projections/ProjectionOptions.cs
…confusion on Snapshot registrations
=> Input validation on projection registration to prevent invalid registrations of SingleStreamProjection

src/CoreTests/adding_custom_schema_objects.cs, src/DocumentDbTests/Indexes/UniqueIndexTests.cs, src/DocumentDbTests/MultiTenancy/UniqueIndexMultiTenantTests.cs, src/EventSourcingTests/EventStreamUnexpectedMaxEventIdExceptionTransformTest.cs, src/Marten/Events/EventStore.ConcurrentAppends.cs, src/Marten/Events/Fetching/FetchAsyncPlan.cs, src/Marten/Events/Fetching/FetchInlinedPlan.cs, src/Marten/Events/Fetching/FetchLivePlan.cs, src/Marten/Events/Operations/InsertStreamBase.cs, src/Marten/Internal/Operations/StorageOperation.cs, src/Marten/Internal/ProviderGraph.cs, src/Marten/Internal/Storage/DocumentStorage.cs, src/Marten/Schema/InsertExceptionTransform.cs, src/Marten/Services/EventStreamUnexpectedMaxEventIdExceptionTransform.cs
Instead of relying on exception messages, use SqlState, because exception messages might be language dependent.
=> Fix some issues with PostgreSQL not running with an english locale

src/Marten/StoreOptions.Registration.cs
Fixes null reference exception when `ApplicationAssembly` is not defined yet, #3644
=> Ignore `ApplicationAssembly` when scanning compiled types using `AutoRegister`

src/Marten/Exceptions/MartenNotSupportedException.cs, src/Marten/Linq/Parsing/JsonPathCreator.cs, src/Marten/Patching/IPatchExpression.cs, src/Marten/Patching/PatchExpression.cs, src/Marten/Schema/SQL/mt_jsonb_append.sql, src/Marten/Schema/SQL/mt_jsonb_insert.sql, src/Marten/Schema/SQL/mt_jsonb_patch.sql, src/Marten/Schema/SQL/mt_jsonb_remove.sql, src/PatchingTests/Patching/patching_api.cs
Proposed new patching functionality for a personal need that could be useful to other MartenDb users.
- Possibility of deleting one or more elements according to a predicate.
- Possibility of adding an element according to a predicate.
- Possibility of inserting an element according to a predicate.
=> Add predicate for patching

docs/documents/multi-tenancy.md
Just fixed an incorrect reference to `DefaultTenantUsageEnabled` property - it is now on the `Advanced` StoreOptions.  Might save someone 5 mins of searching for it
=> Minor fix to documentation on `DefaultTenantUsageEnabled`

src/EventSourcingTests/Bugs/Bug_3643_using_struct_in_map_flattableprojection.cs, src/Marten/Events/Projections/Flattened/MemberMap.cs
Fixes https://github.com/JasperFx/marten/issues/3643
=> Allow structs to be used in FlatTableProjection Map statements

src/Marten.Testing/Documents/Target.cs, src/Marten/Schema/SQL/mt_jsonb_patch.sql, src/PatchingTests/Patching/patching_api.cs
As raised on discord https://discord.com/channels/1074998995086225460/1074999076896112661/1345187448241782885
=> Nested patch path issue when using predicate

src/Marten/Linq/Parsing/JsonPathCreator.cs, src/PatchingTests/Patching/patching_api.cs
While fixing https://github.com/JasperFx/marten/pull/3696 i discovered this bug where we generate an invalid JsonPath if doing a predicate like
`x => x > 10` OR `x => x == "foo"`
since the visitor only vists MemberExpressions and hence skips the ParameterExpression of x.
=> Patch predicates with no member access

src/LinqTests/ChildCollections/query_against_child_collections.cs, src/Marten/Linq/SqlGeneration/SelectorStatement.cs
Minimal code added, only modifying the fix already made for #3025 to be 
1. Before so we process any subqueries in CompoundWhereFragments before the top level Subqueries
2. Doing it recursively do discover subqueries on deeper levels.
Fixes https://github.com/JasperFx/marten/issues/3710 and #3392
=> Make sure to process compound parts depth first and do it recursively

docs/documents/full-text.md, src/DocumentDbTests/Indexes/NgramSearchTests.cs, src/Marten/Schema/SQL/mt_grams_array.sql
This will give less surprises for people trying to search in non english texts.
=> Applying unaccent to ngram searches for better multilingual experience

src/Marten/Storage/Encryption/AesConnectionStringEncryptor.cs, src/Marten/Storage/Encryption/EncryptionOptions.cs, src/Marten/Storage/Encryption/IConnectionStringEncryptor.cs, src/Marten/Storage/Encryption/KeyGenerator.cs, src/Marten/Storage/Encryption/NoopConnectionStringEncryptor.cs, src/Marten/Storage/Encryption/PgCryptoConnectionStringEncryptor.cs, src/Marten/Storage/MasterTableTenancy.cs, src/MultiTenancyTests/using_master_table_multi_tenancy_with_encryption.cs
Encryption of connection string pertaining to Master Table Tenancy Model 
- Add AES encryption of connection string
- Add PgCrypto encryption of connection string
- Default plain text connection string logic is kept for production compatibility
- Add KeyGenerator
Todo:
=> AES and PgCrypto encryption of connection strings for Master Table Tenancy Model 

src/Marten/Schema/SQL/mt_grams_array.sql
This slipped because the marten test suite ([here](https://github.com/JasperFx/marten/blob/b12473a7f6b5954831e25d41a8fa7dfe26b4fa4e/src/CoreTests/adding_custom_schema_objects.cs#L84)) enables the extension and doesn't tidy up I had run the tests previously on the database i tested against 🤦
=> Make sure unaccent is enabled. 

src/Marten/Schema/SQL/mt_jsonb_fix_null_parent.sql
Fixing null check in the `mt_jsonb_fix_null_parent.sql` function as described in #3722 , which will allow to create full hierarchy of nested keys.
=> Fix null check in mt_jsonb_fix_null_parent.sql

docs/documents/sessions.md
I was reading through https://martendb.io/documents/sessions.html#opening-sessions and was confused when I couldn't find any mention of `LightWeightDocumentSession` anywhere, and doubly so since it was listed as the recommended session type for read/write operations. Not sure if the name changed from a previous version, or maybe it's about to change; just couldn't find it right now :) 
(I did find `LightweightDocumentStorage` so maybe this is just a temporary thing)
=> Replaced term LightWeightDocumentSession in Session documentation with LightweightSession

docs/documents/full-text.md
Based on the lovely feedback I had in the Discord regarding Ngram search, I have added an example in the documentation.
=> docs(Ngram search): Added doc on how to search on multiple properties

src/Marten/Events/Aggregation/AggregationRuntime.cs, src/Marten/Events/Aggregation/Rebuilds/AggregatePageHandler.cs, src/Marten/Events/Aggregation/SideEffectCode.cs, src/Marten/Events/Daemon/Internals/GroupedProjectionExecution.cs, src/Marten/Events/Daemon/Internals/ProjectionUpdateBatch.cs, src/Marten/Events/EventGraph.cs, src/Marten/Events/IEventStoreOptions.cs, src/Marten/Events/IReadOnlyEventStoreOptions.cs, src/Marten/Events/Projections/ProjectionOptions.cs, src/Marten/Internal/Sessions/DocumentSessionBase.SaveChanges.cs, src/Marten/Internal/Sessions/DocumentSessionBase.cs, src/Marten/Subscriptions/SubscriptionExecution.cs
=> Inline side effects & better side effects under concurrency

src/DocumentDbTests/DocumentDbTests.csproj, src/DocumentDbTests/MultiTenancy/conjoined_multi_tenancy.cs, src/Marten.Testing/Documents/SingleTenantedDocument.cs, src/Marten/Schema/SingleTenantedAttribute.cs
The [SingleTenanted] document attribute was incorrectly setting documents to `TenancyStyle.Conjoined`.
This pull request fixes the attribute and also adds a test to verify the fix.
=> Make SingleTenanted attribute work properly

docs/schema/cleaning.md, docs/testing/integration.md
Store.Advanced.ResetAllData() is part of what you need to do for test initialization, but if you use the AsyncDaemon in your setup, all tests after the first one will timeout on Store.WaitForNonStaleProjectionDataAsync().
Quick couple line change to the documentation. Happy to iterate if this should be added to more places.
=> Update docs to use ResetAllMartenDataAsync()

src/DocumentDbTests/ForeignKeys/configuring_foreign_key_fields.cs, src/Marten/Schema/DocumentMapping.cs
Until v7.35.1 it was possible to define FK indexes between multi tenanted document and single tenanted document in single server configuration. Starting from that version Marten included `tenant_id` in FK reference to single tenanted document which ended up in PSQL exception:
`Npgsql.PostgresException: 42703: column "tenant_id" referenced in foreign key constraint does not exist`
SQL that includes invalid FK REFERENCE:
```
DROP TABLE IF EXISTS public.mt_doc_single_tenanted_doc CASCADE;
CREATE TABLE public.mt_doc_single_tenanted_doc (
id                  uuid                        NOT NULL,
data                jsonb                       NOT NULL,
mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
mt_version          uuid                        NOT …
```
=> fix FK reference from multi tenanted doc to single tenanted doc

docs/events/protection.md, src/EventSourcingTests/removing_protected_information.cs, src/Marten/Events/EventGraph.Masking.cs
Add support to mask records by introducing a FuncMasker.
=> feat: #3823 add support for masking rules using Func delegates

src/DocumentDbTests/Bugs/Bug_3778_schema_name_issue.cs, src/Marten/Linq/Members/DateTimeMember.cs, src/Marten/Linq/Members/DateTimeOffsetMember.cs, src/Marten/Schema/ComputedIndex.cs, src/Marten/Schema/NgramIndex.cs
- Fix blind replace of d.in TypedLocator causing issues when schema name ends with d
- Fixes GH-3778
=> Fix blind replace of `d.` in TypedLocator causing issues when schema name ends with `d`

src/DaemonTests/Internals/HighWaterAgentTests.cs, src/EventSourcingTests/Bugs/Bug_3874_able_to_read_archived_and_tombstone_from_older_names.cs, src/EventSourcingTests/EventGraphTests.cs, src/Marten/Events/Daemon/Internals/ResilientEventLoader.cs, src/Marten/Events/EventGraph.cs, src/Marten/Internal/Sessions/EventTracingConnectionLifetime.cs, src/Marten/Marten.csproj
Had to upgrade to at least System.Diagnostics.DiagnosticSource v9
wip: Archived changes
Ability to read old Archived & Tombstone events. Closes GH-3874
=> V8 Fixes for Archived & Tombstone event usage

src/DocumentDbTests/Indexes/full_text_index.cs, src/DocumentDbTests/Reading/BatchedQuerying/batched_querying_acceptance_Tests.cs, src/DocumentDbTests/Reading/Json/streaming_json_results.cs, src/DocumentDbTests/SessionMechanics/DocumentSession_change_set_tracking_Tests.cs, src/DocumentDbTests/Writing/Identity/using_int_identity.cs, src/DocumentDbTests/Writing/Identity/using_long_identity.cs, src/DocumentDbTests/Writing/Identity/using_string_identity.cs, src/DocumentDbTests/Writing/document_inserts.cs, src/DocumentDbTests/Writing/storing_documents.cs, src/EventSourcingTests/QuickAppend/quick_append_event_capture_and_fetching_the_stream.cs, src/EventSourcingTests/QuickAppend/quick_append_event_capture_and_fetching_the_stream_with_string_identifiers.cs, src/EventSourcingTests/end_to_end_event_capture_and_fetching_the_stream.cs, src/EventSourcingTests/end_to_end_event_capture_and_fetching_the_stream_with_string_identifiers.cs, src/LinqTests/Acceptance/query_with_inheritance.cs, src/LinqTests/Acceptance/select_many.cs, src/LinqTests/Compiled/compiled_queries.cs, src/LinqTests/Operators/is_subset_of_operator.cs, src/LinqTests/Operators/is_super_set_of_operator.cs, src/Marten/Events/TestSupport/ProjectionScenario.EventOperations.cs, src/Marten/Internal/CompiledQueries/CompiledQueryPlan.cs, src/Marten/Linq/Members/ChildCollectionMember.cs, src/Marten/Pagination/PagedList.cs
Replace Count() with Count and length, Performance improvement
=> Replace `Count()` method with `Count` and `Length` properties

src/DaemonTests/Internals/basic_functionality.cs, src/DaemonTests/TestingSupport/TripStream.cs, src/EventSourcingTests/ScenarioCopyAndReplaceStream.cs, src/LinqTests/Bugs/Bug_1884_multi_tenancy_and_Any_query.cs, src/LinqTests/Bugs/Bug_2563_sub_collection_queries_and_OR.cs, src/LinqTests/ChildCollections/query_against_child_collections.cs, src/LinqTests/Includes/end_to_end_query_with_include.cs, src/Marten.Testing/Examples/Searching_Within_Child_Collections.cs
Avoid unnecessary zero-length array allocations. Use Array.Empty() instead.
CA1825
=> Avoid unnecessary zero-length array allocations

src/CoreTests/DocumentCleanerTests.cs, src/CoreTests/adding_custom_schema_objects.cs, src/DaemonTests/Aggregations/build_aggregate_multiple_projections.cs, src/DocumentDbTests/Configuration/DocumentMappingTests.cs, src/EventSourcingTests/Aggregation/stream_compacting.cs, src/EventSourcingTests/event_store_with_string_identifiers_for_stream.cs, src/EventSourcingTests/removing_protected_information.cs, src/EventSourcingTests/replacing_events.cs, src/Marten.NodaTime.Testing/Bug_2307_JObject_in_dictionary_duplicated_field.cs, src/Marten/Events/EventStore.StreamCompacting.cs, src/Marten/Events/QueryEventStore.cs
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1826
Performance Improvements for the testing projects.
=> CA1826: Use property instead of Linq Enumerable method

src/ContainerScopedProjectionTests/projections_with_IoC_services.cs, src/Marten/Marten.csproj
Getting the following error when trying to rebuild a projection that has been add via AddProjectionWithServices, and a MultiStreamProjection.
To Reproduce run the "use_multistream_projection_as_scoped_and_inline_on_martenStore" test.
```at Marten.Generated.DocumentStorage.LightweightLocationDocumentStorage705746301.Overwrite(Location document, IMartenSession session, String tenant) in /home/micah/novil-next/src/WebApp/Novil.Web/Internal/Generated/DocumentStorage/LocationProvider705746301.cs:line 562
at Marten.Internal.Sessions.ProjectionStorage`2.StoreProjection(TDoc aggregate, IEvent lastEvent, AggregationScope scope) in /_/src/Marten/Internal/Sessions/DocumentSessionBase.ProjectionStorage.cs:line 114
at JasperFx.Events.Daemon.AggregationRunner`4.ApplyChangesAsync(ShardExecutionMode …
```
=> Adding rebuild projection bug on MultiStreamProjections with Services.

src/DaemonTests/HealthChecks/AsyncDaemonHealthCheckExtensionsTests.cs, src/Marten.AspNetCore/Daemon/AsyncDaemonHealthCheckExtensions.cs
Introduce ProjectionStateTracker to track projection states across health check invocations. Update AsyncDaemonHealthCheck to utilize this new tracker and modify its constructor accordingly. Add a test to ensure the tracker is registered in the service collection. Enhance CheckHealthAsync logic to improve robustness in health check implementation.
=> Fixes #3462 Add ProjectionStateTracker for health check improvements

src/Marten/Internal/Sessions/QuerySession.Disposal.cs
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1513
It seems that the second parameter needs to the instance of the object (by passing `this` keyword or the Type of the containing class), and the message of the exception can not be changed. But I did not want to make a breaking change, even if it was very small, so I passed the string as it is without any change
=> Use ObjectDisposedException throw helper
