paket.dependencies
paket.lock

Use Roslyn packages from stable NuGet feed instead of nightly MyGet feed

---

src/Marten.Testing/DevelopmentModeRegistry.cs
src/Marten.Testing/DocumentSessionFixture.cs
src/Marten/Marten.csproj
src/Marten/MartenRegistry.cs
src/Marten/Schema/DocumentSchema.cs
src/Marten/Schema/IDocumentSchema.cs
src/Marten/Schema/PostgresUpsertType.cs
src/Marten/Schema/SchemaBuilder.cs
src/Marten/Util/CommandExtensions.cs

@jeremydmiller almost there, we just need to discuss how to configure the tests to run in standard mode and fallback mode.

closes JasperFx/Marten#65 postgresql 9.4 fallback

---

src/Marten.Testing/Linq/invoking_queryable_through_last_Tests.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Linq/MartenQueryExecutor.cs

Basically ensure first tests pass when switched to last but am setting flag property and checking for this to ensure it really does return last one
Hope this is okay.

Support Last() and LastOrDefault() queries (closes #41)

---

src/Marten.Testing/CustomConventions.cs
src/Marten.Testing/Linq/invoking_queryable_through_to_list_async_Tests.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/document_session_persist_and_load_single_documents_Tests.cs
src/Marten.Testing/persisting_document_with_string_id_Tests.cs
src/Marten/DocumentSession.cs
src/Marten/IDocumentSession.cs
src/Marten/Linq/IMartenQueryExecutor.cs
src/Marten/Linq/IMartenQueryProvider.cs
src/Marten/Linq/IMartenQueryable.cs
src/Marten/Linq/MartenQueryExecutor.cs
src/Marten/Linq/MartenQueryProvider.cs
src/Marten/Linq/MartenQueryable.cs
src/Marten/Marten.csproj
src/Marten/QuerySession.cs
src/Marten/Services/CommandRunner.cs
src/Marten/Services/DirtyTrackingIdentityMap.cs
src/Marten/Services/ICommandRunner.cs
src/Marten/Services/IIdentityMap.cs
src/Marten/Services/IdentityMap.cs
src/Marten/Services/NulloIdentityMap.cs
src/Marten/Services/UnitOfWork.cs
src/Marten/Services/UpdateBatch.cs
src/Marten/Util/QueryableExtensions.cs

Base async\await support
Closes #16

Asynchronous versions of everything in the IDocumentSession API

---

src/Marten.Testing.OtherAssembly/DeeperNamespace/BaseDocumentWithId.cs
src/Marten.Testing.OtherAssembly/Marten.Testing.OtherAssembly.csproj
src/Marten.Testing.OtherAssembly/Properties/AssemblyInfo.cs
src/Marten.Testing/Documents/UserWithInheritedId.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/document_session_storing_from_another_assembly_Tests.cs
src/Marten.sln
src/Marten/Codegen/AssemblyGenerator.cs
src/Marten/Schema/DocumentStorageBuilder.cs

Reference assemblies of document's base types recursively in code generation 

---

src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/Session/document_session_find_json_Tests.cs
src/Marten.Testing/Session/document_session_find_json_async_Tests.cs
src/Marten/IDocumentSession.cs
src/Marten/QuerySession.cs

@jeremydmiller look please. Is it enough?
Closes #33

Helpers to retrieve the raw JSON

---

src/Marten.Testing/Linq/invoking_queryable_through_to_list_async_Tests.cs
src/Marten/Linq/MartenQueryExecutor.cs

Ensure that storage exists before command creation

---

src/Marten.Testing/Schema/IndexDefinitionTests.cs
src/Marten/Generation/TableDefinition.cs
src/Marten/Schema/IndexDefinition.cs
src/Marten/Schema/SchemaBuilder.cs

Fix for #114 
I'm not sure if I've missed any other places where columns are used, let me know if I have and I'll fix those up too.

wrapped columns in quotes to prevent reserved words throwing

---

src/Marten.Testing/Session/RequestCounter/document_session_with_request_counter_threshold_Tests.cs

The code samples at http://jasperfx.github.io/marten/documentation/documents/request-throttling/ didn't match the text in the documentation

Changed the code sample for the request counter to match the documentation

---

src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/MartenRegistryTests.cs
src/Marten.Testing/Schema/DocumentMappingTests.cs
src/Marten.Testing/Schema/will_name_nested_class_documents_appropriately.cs
src/Marten/Schema/DocumentMapping.cs

@jeremydmiller ready for your review

closes JasperFX/marten#125 nested document naming

---

src/Marten.Testing/Linq/query_with_modulo_Tests.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Linq/MartenExpressionParser.cs

I am *a lot* happier with this implementation :-P
btw- I think MartenExpressionParser starts to look like a class in need for refactoring maybe..?

added support for modulo where queries

---

src/Marten.Testing/Linq/query_beginning_with_constant_Tests.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Linq/MartenExpressionParser.cs

added support for queries where equal-to value is on the left

---

src/Marten.Testing/Fixtures/Target.cs
src/Marten.Testing/Linq/query_with_nullable_types_Tests.cs
src/Marten/Linq/MartenExpressionParser.cs

added ability to query where nullable is null

---

src/Marten/Services/IdentityMap.cs

instead of the HashCode of the id object. Should fix #179

Changed the IdentityMap ConcurrentDictionary to use an object as key

---

src/Marten.Testing/Linq/invoking_queryable_count_async_Tests.cs
src/Marten.Testing/Linq/query_for_sum_Tests.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Linq/DocumentQuery.cs
src/Marten/Linq/MartenQueryExecutor.cs
src/Marten/Linq/ScalarQueryExecution.cs
src/Marten/Marten.csproj
src/Marten/Util/QueryableExtensions.cs

Fixes #157 
I refactored some code in MartenQueryExecutor- feel free to let me know if this could be done better :-)

added sum queries

---

src/Marten/Codegen/AssemblyGenerator.cs

Do you mind pulling this too? It is the temp workaround for .net core code generation. I have no dnx tests in this solution but it works in a dnx app I'm working on.

Temp workaround for .net core code generation

---

src/Marten.Testing/Linq/invoking_queryable_count_Tests.cs
src/Marten/Linq/MartenQueryExecutor.cs
src/Marten/Linq/ScalarQueryExecution.cs

added support for synchronous long count

---

src/Marten/DocumentSession.cs
src/Marten/IDocumentSession.cs
src/Marten/Services/IManagedConnection.cs

Expose the request count off of IDocumentSession 

---

src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/Util/EnumerableExtensionsTests.cs
src/Marten.Testing/foreign_key_persisting_Tests.cs
src/Marten/Marten.csproj
src/Marten/Schema/DocumentSchema.cs
src/Marten/Schema/ForeignKeyDefinition.cs
src/Marten/Services/UnitOfWork.cs
src/Marten/Util/EnumerableExtensions.cs

Use foreign key relationships to order the document types in unit of work commits

---

src/Marten.Testing/Linq/query_for_json_format.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Linq/IMartenQueryExecutor.cs
src/Marten/Linq/MartenQueryExecutor.cs
src/Marten/Linq/MartenQueryable.cs
src/Marten/Linq/QueryableExtensions.cs
src/Marten/Marten.csproj

implemented
ToListJson
ToListJsonAsync
FirstOrDefaultJson
FirstOrDefaultJsonAsync
FirstJson
FirstJsonAsync
As discussed in #219
I made FirstOrDefault return null as default; let me know if you prefer something else.
Let me know if there's anything that could be done differently/better.

added support for ToListJson & FirstOrDefaultJson sync/async

---

src/Marten.Testing/Linq/query_for_json_format.cs
src/Marten.Testing/Linq/query_for_single_json.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Linq/IMartenQueryExecutor.cs
src/Marten/Linq/MartenQueryExecutor.cs
src/Marten/Linq/MartenQueryable.cs
src/Marten/Linq/QueryableExtensions.cs

added support for SingleJson & SingleOrDefaultJson (a/sync)

---

src/Marten.Testing/Linq/explain_query.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Linq/IMartenQueryable.cs
src/Marten/Linq/MartenQueryExecutor.cs
src/Marten/Linq/MartenQueryable.cs
src/Marten/Linq/QueryPlan.cs
src/Marten/Marten.csproj
src/Marten/Services/CommandRunnerExtensions.cs
src/Marten/Util/QueryableExtensions.cs

added explain query feature

---

documentation/documentation/documents/query_json.md
src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/Session/get_raw_json_Tests.cs

Though this wasn't in the pipeline, I thought I might as well get this done.
Take your time with this, no pressure :smile:

added documentation for all raw json querying methods

---

src/Marten.Testing/Linq/query_for_sum_Tests.cs
src/Marten.Testing/Linq/query_with_aggregate_functions.cs
src/Marten/Linq/QueryHandlers/AggregateQueryHandler.cs
src/Marten/Linq/QueryHandlers/QueryHandlerFactory.cs

First batch for #283 
Average test wasn't decorated with [Fact]

Fixed sum of empty table and average functionality

---

src/Marten.Testing/Linq/query_with_aggregate_functions.cs
src/Marten/Linq/ScalarSelector.cs

Fixes #283 (Min, Max & Average)

Made scalar queries on empty table throw InvalidOperationException

---

src/Marten.Testing/Documents/User.cs
src/Marten.Testing/Linq/compiled_query_Tests.cs
src/Marten.Testing/Linq/query_for_json_format.cs
src/Marten.Testing/Session/get_raw_json_Tests.cs
src/Marten/JsonExtensions.cs
src/Marten/Linq/AsJsonExpressionNode.cs
src/Marten/Linq/AsJsonResultOperator.cs
src/Marten/Linq/MartenQueryParser.cs
src/Marten/Linq/QueryHandlers/JsonQueryHandler.cs
src/Marten/Linq/QueryHandlers/QueryHandlerFactory.cs
src/Marten/Linq/ToJsonArrayExpressionNode.cs
src/Marten/Linq/ToJsonArrayResultOperator.cs
src/Marten/Marten.csproj

fixes #312 
Pleas code review thoroughly; it works, but if feels quite convoluted.

Added support for Asjson / ToJsonArray compiled queries

---

src/Marten.Testing/Events/using_the_schema_objects_Tests.cs
src/Marten/Events/EventGraph.cs

Fix '327 Reusing the Event Store always resets the Event Store'

---

src/Marten.Testing/Bugs/Bug_339_async_cache_problem.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Services/IdentityMap.cs

fix 339 async cache issue

---

src/Marten/Events/EventQueryHandler.cs
src/Marten/Events/EventStore.cs
src/Marten/Events/Projections/AggregateFinder.cs
src/Marten/Events/Projections/AggregationProjection.cs
src/Marten/Events/SingleEventQueryHandler.cs
src/Marten/Events/StreamStateHandler.cs
src/Marten/JsonExtensions.cs
src/Marten/Linq/JsonSelector.cs
src/Marten/Linq/QueryHandlers/JsonQueryHandler.cs
src/Marten/Linq/QueryHandlers/ListQueryHandler.cs
src/Marten/Linq/QueryHandlers/OneResultHandler.cs
src/Marten/Linq/QueryHandlers/UserSuppliedQueryHandler.cs
src/Marten/Linq/ScalarSelector.cs
src/Marten/Linq/SingleFieldSelector.cs
src/Marten/Linq/StringSelector.cs
src/Marten/Linq/WholeDocumentSelector.cs
src/Marten/Services/CommandRunnerExtensions.cs

Removed unnecessary awaits and added `ConfigureAwait(false)`

---

src/Marten.Testing/Documents/Issue.cs
src/Marten.Testing/Documents/User.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/Services/Includes/end_to_end_query_with_compiled_include_Tests.cs
src/Marten.Testing/Services/Includes/end_to_end_query_with_include_Tests.cs
src/Marten/CompiledQueryExtensions.cs
src/Marten/Linq/AsJsonExpressionNode.cs
src/Marten/Linq/CompiledQueryMemberExpressionVisitor.cs
src/Marten/Linq/IncludeExpressionNode.cs
src/Marten/Linq/IncludeResultOperator.cs
src/Marten/Linq/MartenQueryParser.cs
src/Marten/Linq/QueryHandlers/CompiledIncludeJoinBuilder.cs
src/Marten/Linq/QueryHandlers/QueryHandlerFactory.cs
src/Marten/Linq/SelectorParser.cs
src/Marten/Linq/ToJsonArrayExpressionNode.cs
src/Marten/Marten.csproj

currently support one or multiple includes. For #309

Added support for compiled query with include/s

---

documentation/documentation/documents/compiled_queries.md
src/Marten.Testing/Linq/invoking_query_with_statistics.cs
src/Marten/CompiledQueryExtensions.cs
src/Marten/Linq/CompiledQueryMemberExpressionVisitor.cs
src/Marten/Linq/MartenQueryParser.cs
src/Marten/Linq/QueryHandlers/QueryHandlerFactory.cs
src/Marten/Linq/StatsExpressionNode.cs
src/Marten/Linq/StatsResultOperator.cs
src/Marten/Marten.csproj

Added support for compiled query stats

---

src/Marten/Generation/TableDiff.cs
src/Marten/Schema/JsonLocatorField.cs
src/Marten/Schema/SchemaDiff.cs

Just added some missing `;` from end of sql statements, and a line break between a drop/create index in the schema patching.

Added line breaks & terminators to sql statements

---

src/Marten/Schema/DatabaseSchemaGenerator.cs

Added trailing line breaks to schema generation DDL

---

src/Marten.Testing/Acceptance/optimistic_concurrency_with_subclass_hierarchies.cs
src/Marten.Testing/Acceptance/soft_deletes.cs
src/Marten.Testing/Bugs/Bug_276_Query_by_abstract_type_in_hierarchy.cs
src/Marten.Testing/Bugs/Bug_431_not_patching_with_the_doc_type_column.cs
src/Marten.Testing/Linq/query_with_inheritance.cs
src/Marten.Testing/Schema/DocumentSchemaTests.cs
src/Marten.Testing/Schema/Hierarchies/end_to_end_document_hierarchy_usage_Tests.cs
src/Marten.Testing/Services/BatchedQuerying/batched_querying_acceptance_Tests.cs
src/Marten/MartenRegistry.cs

Changed Subclass to SubClass in all methods for consistent casing

---

documentation/documentation/documents/querying/linq.md

Fix duplicate child collection query sections

Query Documentationn update

---

src/Marten.Testing/Acceptance/computed_indexes.cs

Just added the `.Where` option to the calculated index docs.

Updated doc for calculated index

---

src/Marten.Testing/TypeMappingsTests.cs
src/Marten/Util/TypeMappings.cs

Updated CanonicizeSql to change tabs into spaces

---

src/Marten.Testing/AsyncDaemon/async_daemon_end_to_end.cs
src/Marten/Events/EventSelector.cs
src/Marten/Events/Projections/Async/Fetcher.cs
src/Marten/Events/Projections/ProjectionCollection.cs

I started to play around with the async daemon and noticed that events on another schema were not yet supported properly.

Daemon: Fix support for other schema

---

src/Marten.Testing/Services/Includes/end_to_end_query_with_include_Tests.cs
src/Marten/Linq/MartenQueryable.cs

A lot of testing lines for one simple oversight in `MartenQueryable.cs`

fixes GH-506 left join include for collection

---

src/Marten.Testing/Bugs/Bug_503_query_on_null_complex_object.cs

Added failing test to prove error with query on null complex object

---

src/Marten.Testing/Schema/configuring_schema_name_Tests.cs
src/Marten.Testing/Schema/configuring_searchable_fields_Tests.cs
src/Marten/Schema/DatabaseSchemaNameAttribute.cs
src/Marten/Schema/DuplicateFieldAttribute.cs

As per earlier conversation, this aligns the attribute (closer) to the fluent method
I've also added a DatabaseSchemaNameAttribute

Create duplicate field index

---

src/Marten/IQuerySession.cs
src/Marten/QuerySession.cs
src/Marten/Services/DirtyTrackingIdentityMap.cs
src/Marten/Services/IIdentityMap.cs
src/Marten/Services/IdentityMap.cs
src/Marten/Services/NulloIdentityMap.cs

Removed the constraint `T Load<T>(string id) where T : class;` as it didn't seemed to be needed.

Removed the constraint for T to be a class from the IQuerySession

---

src/Marten.Testing/Linq/invoking_query_with_select_Tests.cs
src/Marten.Testing/Linq/query_with_distinct_Tests.cs
src/Marten.Testing/Services/SelectTransformerTests.cs
src/Marten/Linq/ISelector.cs
src/Marten/Linq/SelectTransformer.cs
src/Marten/Linq/SelectorParser.cs
src/Marten/Linq/SingleFieldSelector.cs
src/Marten/Linq/TargetObject.cs

Added support for Distinct for single field and anonymous object queries

Support for Distinct() in Queries

---

src/Marten.Testing/Documents/User.cs
src/Marten.Testing/Services/Includes/end_to_end_query_with_include_Tests.cs
src/Marten/Events/EventMapping.cs
src/Marten/Linq/IMartenQueryable.cs
src/Marten/Linq/MartenQueryable.cs
src/Marten/Schema/DocumentMapping.cs
src/Marten/Schema/IQueryableDocument.cs
src/Marten/Schema/SubClassMapping.cs
src/Marten/Services/Includes/IncludeJoin.cs
src/Marten/Services/Includes/IncludeSelector.cs

Removed the class constraint on Includes as well. Related to #531

---

documentation/documentation/documents/advanced/patch_api.md
javascript/mt_patching.js
src/Marten.Testing/Acceptance/patching_api.cs
src/Marten.Testing/Patching/PatchExpressionTests.cs
src/Marten/DocumentSession.cs
src/Marten/IDocumentSession.cs
src/Marten/IQuerySession.cs
src/Marten/Patching/IPatchExpression.cs
src/Marten/Patching/PatchExpression.cs
src/Marten/Patching/PatchOperation.cs
test/test_mt_patching.js

See docs for functionality, I've updated to state available from v1.2.
This should close #434, @mattzink can you want to take a look and confirm if this covers what you were requesting.

Add Delete and Duplicate to Patch API

---

documentation/documentation/admin/index.md
documentation/documentation/admin/installing-plv8-windows.md
documentation/documentation/order.txt

I created a new section called 'Admin' (i donno what else to name it for now) where we can start putting things related to managing a postgresql install.

Added documentation for windows users to install plv8

---

documentation/documentation/admin/installing-plv8-windows.md

The tabbing was wrong and it wasn't highlighted so I wrapped the sql with
```sql
```
Now it looks like:

Updated markdown for plv8 install on Windows

---

src/Marten.Testing/Acceptance/last_modified_queries.cs
src/Marten.Testing/Acceptance/soft_deletes.cs
src/Marten.Testing/Linq/SoftDeletes/DeletedBeforeParserTests.cs
src/Marten.Testing/Linq/SoftDeletes/DeletedSinceParserTests.cs
src/Marten.Testing/MartenRegistryTests.cs
src/Marten.Testing/Schema/DocumentMappingTests.cs
src/Marten.Testing/Schema/configuring_mapping_deletion_style.cs
src/Marten/Linq/MartenExpressionParser.cs
src/Marten/Linq/SoftDeletes/DeletedBeforeParser.cs
src/Marten/Linq/SoftDeletes/DeletedSinceParser.cs
src/Marten/Linq/SoftDeletes/SoftDeletedExtensions.cs
src/Marten/MartenRegistry.cs
src/Marten/Schema/DocumentMapping.cs
src/Marten/Schema/SoftDeletedAttribute.cs

DateTimeOffset.DateTime yields a DateTime with Unspecified kind, I think this could be the issue but I've failed to repro, tried changing the timezone of my postgres instance forward and backward and changing timezone of OS forward and backward.
This test was never supposed to have a DateTime passed, I think I only did it to verify the implicit cast would work and left it in by mistake.
See if TeamCity can passes this build.

Deleted At Extensions

---

documentation/documentation/documents/advanced/soft_deletes.md
documentation/documentation/documents/configuration/metadata_index.md
documentation/documentation/documents/index.md
documentation/documentation/documents/querying/metadata_queries.md
documentation/documentation/documents/querying/order.txt
documentation/documentation/schema/metadata.md
src/Marten.Testing/Acceptance/fetching_entity_metadata.cs
src/Marten.Testing/Acceptance/last_modified_queries.cs
src/Marten.Testing/Acceptance/soft_deletes.cs
src/Marten.Testing/Examples/MartenRegistryExamples.cs
src/Marten.Testing/Schema/DocumentMappingTests.cs
src/Marten.Testing/Schema/configuring_last_modified_index_Tests.cs
src/Marten.Testing/Schema/configuring_mapping_deletion_style.cs
src/Marten/AdvancedOptions.cs
src/Marten/Schema/SubClassMapping.cs

Updated the `DocumentMetadata` to include missing columns.
Added the documentation for querying and indexing metadata columns.
Hopefully implemented a fix for the brittle tests.

Additional Metadata fields

---

src/Marten/Schema/IndexDefinition.cs

Fix actual index script column replacement to prevent index re-creation each time

Prevent index re-creation

---

src/Marten/Events/Projections/Async/Fetcher.cs

Fix problem where sometimes the asyncprojectiondaemon might "miss" an event

---

.travis.yml
appveyor.yml
build.sh
src/Marten.Testing/ConnectionSource.cs

- Set version as 2.0.0.{build}
- Configure Postgres 9.5 including plv8 extension
- Setup of test database and plv8 extension installation
- Assembly version patching on CommonAssemblyInfo
- npm install for mocha js tests
- restore, build and pack
- tests including mocha js tests
- creation of nupkg artifacts (only issue being that nupkg file name has
wrong version number)

Add appveyor config for CI build

---

src/Marten.Testing/Linq/query_by_different_id_member.cs

Added tests for spoting wrong mapping on IdMember in linq queries

Query by different id member

---

README.md

Adds Travis  CI badge to readme file. Closes GH-775
@jeremydmiller  This PR can be merged after enabling the project in Travis CI.

Add Travis CI build badge to readme

---

documentation/documentation/documents/configuration/document_policies.md
documentation/documentation/order.txt
documentation/documentation/troubleshoot/index.md
src/Marten.Testing/Examples/CamelCasing.cs
src/Marten.Testing/Examples/Policies.cs
src/Marten/StoreOptions.cs

and allow configuring CamelCasing through StoreOptions

Docs on policies, CamelCase serialization, disabling plv8

---

documentation/documentation/postgres/naming.md
documentation/documentation/postgres/types.md

Fixed the image path for the documentation of postgres naming and types.

Fixed image path

---

src/Marten.Testing/Bugs/Bug_837_missing_func_mt_immutable_timestamp_when_initializing_with_new_Schema.cs
src/Marten/Schema/JsonLocatorField.cs

Issue #837 failing test and fix

Issue #837 failing test and fix

---

src/Marten.Testing/Bugs/Bug_854_multiple_or_expressions_softdelete_tenancy_filters_appended_incorrectly.cs
src/Marten/Schema/DocumentMapping.cs

- Fix issue
- Add failing tests

Fix issue GH-854

---

.gitignore
Gemfile.lock
documentation/content/theme.css
documentation/splash.htm
src/Marten.Testing/Examples/Searching_Within_Child_Collections.cs

* Fix breadcrumb background
* Update CI link to AppVeyor

Add child collection linq example

---

src/Marten.Testing/query_by_sql_where_clause_Tests.cs
src/Marten/Linq/QueryHandlers/UserSuppliedQueryHandler.cs

Ignore case when processing 'where' in sql query.

---

src/Marten.Testing/Linq/query_with_is_one_of_Tests.cs
src/Marten/Linq/NotVisitor.cs
src/Marten/Linq/Parsing/IsNotOneOf.cs
src/Marten/Linq/WhereClauseVisitor.cs

- Add logic to handle combination of not operator with IsOneOf
- Add a unit test for ISOneOf with negation

Bug fix 898 isoneof negation

---

src/Marten.Testing/Patching/PatchingTests.cs
src/Marten/DocumentSession.cs
src/Marten/IDocumentSession.cs
src/Marten/Services/IIdentityMap.cs
src/Marten/Services/IdentityMap.cs
src/Marten/Services/NulloIdentityMap.cs
src/Marten/Services/UnitOfWork.cs

after patching, eject all documents of patched types

---

src/Marten.Testing/Bugs/Bug_931_duplicate_field_att_not_working_for_array_or_list.cs
src/Marten/Schema/DocumentMapping.cs

#931 repro and fix for DuplicateField attribute does not create duplicate column in table for any array or list

Bug 931 repro and fix for DuplicateField attribute does not create duplicate column in table for any array or list

---

documentation/documentation/events/appending.md

Saw it while reading, figured I'd do a quick PR.

Minor nitpick to docs: is --> are

---

src/Marten/Events/Projections/ViewProjection.cs

Makes it possible to get a hold of `IDocumentSession` in the handlers.
Makes it possible to inspect event/projection state before deleting projection with `DeleteEvent`.
Purely additive changes, so shouldnt break backwards compatability. Although I had to go in and mess with some private methods to pass things on.

Solves #946 and #947, ViewProjection additive changes

---

documentation/documentation/documents/querying/linq.md
src/Marten.Testing/Documents/User.cs
src/Marten.Testing/Examples/IsOneOfArray.cs

Added documentation for a way to use IsOneOf on arrays.

IsOneOf for arrays

---

docs.csproj

Update stdocs version from v1.0.0-alpha-442 to v1.1.0

Update stdocs version from v1.0.0-alpha-442 to v1.1.0

---

src/Marten.Testing/Events/Projections/Async/MultidocumentProjectionTests.cs

Lines 96-97 (patching `Order` Company name) from https://github.com/JasperFx/marten/pull/989/files#diff-03bd81b70044908191dfe50f8014a05dR96
Brought back missing lines

Fixed MultidocumentProjectionTests

---

src/Marten/Schema/JsonLocatorField.cs

Fixed JsonLocatorField for array properties.
Fixed failing tests on pipeline.

Fixed Json Locator For Arrays

---

src/Marten.Testing/Bugs/Bug_960_drop_index_concurrently_pg_error.cs
src/Marten/Storage/TableDelta.cs

Includes fix and test for bug #960

Fix for bug #960

---

src/Marten.Testing/Schema/create_database_Tests.cs
src/Marten/Schema/DatabaseGenerator.cs
src/Marten/Schema/ITenantDatabaseCreationExpressions.cs

Allow to automatically create PLV8 extension when new database created

Added PLV8 extension creation option

---

src/Marten.Testing/Acceptance/computed_indexes.cs
src/Marten/MartenRegistry.cs
src/Marten/Schema/DocumentMapping.cs

Close https://github.com/JasperFx/marten/issues/733

Added multi-property indexing support (close #733)

---

documentation/documentation/documents/configuration/computed_index.md
src/Marten.Testing/Examples/MultiPropertyCalculatedIndexExamples.cs

My english is not very good for writing documentation, so  I enable "Allow edits from maintainers" option for this PR

Added documentation for multi-property index (relates to #1040)

---

src/Marten.Testing/Linq/Bug_1061_string_enum_serialization_does_not_work_with_ginindexjsondata.cs
src/Marten/Linq/Parsing/SimpleBinaryComparisonExpressionParser.cs

- [1061](https://github.com/JasperFx/marten/issues/1061) to fix query generation for string enums

Fix 1061 query generation for enums

---

README.md

Add a note regarding Marten Npgsql 3.x and 4.x support.  With reference to a comment on #1044, adding this note for clarity to Marten users.

Update readme with a note on Npgsql4 support

---

src/Marten/Linq/QueryHandlers/CachedQuery.cs
src/Marten/Linq/QueryHandlers/CachedQueryHandler.cs
src/Marten/Linq/QueryHandlers/QueryHandlerFactory.cs
src/Marten/Marten.csproj
src/Marten/Schema/Arguments/UpsertArgument.cs
src/Marten/Schema/DocumentMapping.cs
src/Marten/Schema/DuplicatedField.cs
src/Marten/Schema/Field.cs
src/Marten/Schema/JsonLocatorField.cs
src/Marten/Services/SprocCall.cs
src/Marten/Storage/DocumentTable.cs
src/Marten/Storage/UpsertFunction.cs
src/Marten/Util/LambdaBuilder.cs
src/Marten/Util/TypeMappings.cs

Improved and unified usage of EnumStorage through code base. 
Fixed hacks and uncertainities in this area found in https://github.com/JasperFx/marten/pull/1045

Marten 3.0 improvements

---

.travis.yml
src/Marten.Testing/Services/CharArrayTextWriterTests.cs
src/Marten/DocumentStore.cs
src/Marten/Events/EventStreamAppender.cs
src/Marten/Marten.csproj
src/Marten/QuerySession.cs
src/Marten/Schema/Arguments/DocJsonBodyArgument.cs
src/Marten/Schema/Arguments/UpsertArgument.cs
src/Marten/Services/AllocatingMemoryPool.cs
src/Marten/Services/CharArrayTextWriter.cs
src/Marten/Services/DirtyTrackingIdentityMap.cs
src/Marten/Services/SprocCall.cs
src/Marten/Services/UpdateBatch.cs
src/Marten/Storage/BulkInsertion.cs

An experimental PR that changes `CharArrayTextWriter` pooling behavior from the custom one to one based on `MemoryPool<char>` from `System.Memory` package

[WIP] Introduction of MemoryPool based CharTextWriter

---

src/Marten/Events/EventStream.cs
src/Marten/Events/ExistingStreamIdCollisionException.cs
src/Marten/Services/EventStreamUnexpectedMaxEventIdException.cs

See more: https://github.com/JasperFx/marten/pull/1093

Re-fix for EventStream exceptions

---

martenbuild.cs

I find it's usually better to isolate targets to one significant operation, so that you get more specific success/failure messages and timings.

split targets up a little

---

documentation/documentation/documents/index.md
documentation/documentation/documents/querying/paging.md
src/Marten.Testing/Pagination/pagedlist_queryable_extension_Tests.cs

- Add documentation for `ToPagedList` and `ToPagedListAsync`
- Update unit test to tag samples for documentation
- Update documents index to include all pages relating to querying

Add documentation for ToPagedList

---

src/Marten.Testing/Util/update_batch_Tests.cs
src/Marten/Services/UpdateBatch.cs

- async batch updates sent fifo #1109
-  failing test for #1109 
Note: cherry picked fix from master branch

async batch updates sent fifo

---

src/Marten.Testing/Using_Global_DocumentSessionListener_Tests.cs
src/Marten/DocumentStore.cs
src/Marten/Services/NulloIdentityMap.cs

- Fix DocumentLoaded event not firing for LightweightSession - fixes #1100

Fix DocumentLoaded event not firing for LightweightSession - fixes #1100

---

package-lock.json
package.json

Ran `npm audit fix` on packages and then ran the build. The
audit issues are gone and the build succeeded with all
tests passing.

Fix NPM audit issues

---

src/Marten.Testing/Linq/query_with_IsSuperSetOf_Tests.cs
src/Marten.Testing/Target.cs
src/Marten/Linq/Parsing/IsSupersetOf.cs

Added IsSupersetOf linq support for ISet<> types

---

.travis.yml
appveyor.yml

- Update both Appveyor and TravisCI to use PG10
- Remove Ruby and Rake related config

Update CI configs to use PG10

---

src/Marten/Linq/MartenQueryable.cs

Fix https://github.com/JasperFx/marten/issues/1141

Use JoinType parameter in Join with dictionary

---

martenbuild.cs

30 less lines, FWIW. Take it or leave it. 🙂

remove a bunch of lines from martenbuild.cs

---

martenbuild.csproj

I hope you don't mind me using Marten as a test for the RC.
If you prefer not to to merge this, please go ahead and close it. I can send another PR when RTM is released. Note that if no bugs are found in this RC, then RTM will be built from the same commit.
Changes in 4.0.0:
- [Switch to optional parameters](https://github.com/adamralph/simple-exec/issues/63)
- [Echo to stderr instead of stdout](https://github.com/adamralph/simple-exec/issues/64)
- [Add API documentation](https://github.com/adamralph/simple-exec/issues/57)

upgrade SimpleExec to 4.0.0-rc.1

---

src/Marten.Testing/Linq/query_against_child_collections_integrated_Tests.cs
src/Marten.Testing/Util/LambdaBuilderTester.cs
src/Marten/Linq/CollectionAnyContainmentWhereFragment.cs
src/Marten/Linq/ContainmentWhereFragment.cs
src/Marten/Linq/Parsing/SimpleEqualsParser.cs
src/Marten/Schema/Arguments/UpsertArgument.cs
src/Marten/Util/LambdaBuilder.cs

Follow up of https://github.com/JasperFx/marten/pull/1137. Fixed test case but added other failing integration test

WIP: Fix enum querying

---

src/Marten.Testing/Bugs/Bug_1173_patch_typenamehandling_bug.cs
src/Marten/Patching/PatchOperation.cs

This is a quick hack to demonstrate the issue and provide a possible solution to https://github.com/JasperFx/marten/issues/1173.

Fix patch api to support TypeNameHandling.Object

---

src/Marten.Testing/Storage/UpsertFunctionTester.cs
src/Marten/Storage/Function.cs
src/Marten/Storage/FunctionDelta.cs

Reinstate previous function versions in patch rollback DDL

---

src/Marten.Testing/Acceptance/computed_indexes.cs
src/Marten.Testing/Examples/MartenRegistryExamples.cs
src/Marten/Schema/ComputedIndex.cs

Example for changes made in #1199 / #1213

Example showing customising the sort order of a duplicated index

---

src/Marten.Testing/Services/Includes/end_to_end_query_with_include_Tests.cs
src/Marten/Linq/CollectionAnyContainmentWhereFragment.cs

IsOneOf for array using include fails

---

src/Marten.Testing/Services/Includes/end_to_end_query_with_include_Tests.cs
src/Marten/Linq/MartenQueryable.cs

`Include` with JoinType.LeftOuter and dictionary fails

---

src/Marten.Testing/Acceptance/using_natural_identity_keys.cs
src/Marten/Schema/DocumentMapping.cs

- Update logic to find Id member with IdentityAttribute followed by Id property or field

Fix logic to find Id member with Identity attribute as priority - fixes GH-1191

---

src/Marten.Testing/Schema/Hierarchies/end_to_end_document_hierarchy_with_interface_tests.cs
src/Marten/Util/LambdaBuilder.cs
src/Marten/Util/ReflectionExtensions.cs

Fixes https://github.com/JasperFx/marten/issues/1207
Fixed lambda builder to properly generate type hierarchy for the document with hierarchy setup on interfaces
See more details: https://stackoverflow.com/a/2444090/10966454

#1207 - Fix for documents hierarchy lambda generation

---

.travis.yml
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.NodaTime/Marten.NodaTime.csproj
src/Marten/Marten.csproj

- Bump up version in proj files to 3.5.0
- Supress warnings for missing XML documentation 1591 in Release config
- Update Travis CI to config Release in env vars

Bump version to 3.5.0

---

documentation/getting_started.md

Added .Net CLI example

---

src/Marten.NodaTime/NodaTimeExtensions.cs
src/Marten/Events/EventSelector.cs
src/Marten/Events/Projections/Async/Fetcher.cs
src/Marten/Events/StringIdentifiedEventSelector.cs
src/Marten/Util/TypeMappings.cs

Based on PR #1246 with a few more fixes. Only lightly tested.
TypeMappings.cs seems to have inconsistent line endings in the repo so this fixes that too.

#1242 - (more) fixes for EventStore NodaTime support 

---

src/Marten.Testing/Schema/Hierarchies/end_to_end_document_hierarchy_usage_Tests.cs
src/Marten/Schema/SubClassMapping.cs

- Fix SubclassMappings to handle AnyTenant query filter
fixes GH-1181

Fix AnyTenant query logic on tenanted document hierarchy

---

src/Marten.Testing/Schema/ForeignKeyDefinitionTests.cs
src/Marten/Schema/DocumentMapping.cs
src/Marten/Schema/ForeignKeyDefinition.cs

Rewrote #1202 per @jeremydmiller suggestion.

Create a foreign key reference from a marten document to an external table.

---

src/Marten.Testing/ability_to_fetch_postgres_server_version.cs
src/Marten/DocumentStore.cs
src/Marten/IDiagnostics.cs
src/Marten/IDocumentStore.cs
src/Marten/Services/Diagnostics.cs

- Implement `GetPostgresVersion` method in `DocumentStore`

Add functionality to get pg version using document store

---

documentation/documentation/documents/advanced/retrypolicy.md
src/Marten.Testing/Examples/RetryPolicyTests.cs
src/Marten/IRetryPolicy.cs

Remove typo (git command) from interface XML comments.
Docs for #1254 if all this makes sense.

Add unit test for retry policy.

---

src/Marten.Testing/Acceptance/full_text_index.cs
src/Marten.Testing/Bugs/Bug_1245_include_plus_full_text_search.cs
src/Marten.Testing/Harness/PgVersionTargetedFact.cs
src/Marten.Testing/Marten.Testing.csproj

Allows for less setup than SkippableFact & PG version looked up only once / test run.

Test attribute for targeting min and/or max versions of PG.

---

documentation/documentation/events/projections/custom.md
src/Marten.Testing/Events/Projections/custom_async_transformation_of_events.cs
src/Marten.Testing/Events/Projections/custom_transformation_of_events.cs

Updated Custom Projection Documentation.
Added sample for ProjectEventAsync with loading related document with documentSession and using event meta data.
Fixes #1249
@tetious fyi

Updated Custom Projection Documentation. 

---

src/Marten.Testing/Schema/DocumentMapping_schema_patch_foreign_key_writing.cs
src/Marten/MartenRegistry.cs

Looks like parameters got mixed up.

Fixed parameter order for ForeignKey

---

src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj
src/Marten.NodaTime/Marten.NodaTime.csproj
src/Marten.Testing/Bugs/Bug_849_not_node_not_correctly_evaluated.cs
src/Marten.Testing/Events/end_to_end_event_capture_and_fetching_the_stream_Tests.cs
src/Marten.Testing/Events/end_to_end_event_capture_and_fetching_the_stream_with_non_typed_streams_Tests.cs
src/Marten.Testing/Events/multi_tenancy_and_event_capture.cs
src/Marten.Testing/Linq/StringNotVisitorTests.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/Schema/auto_create_schema_should_ensure_storage_only_once.cs
src/Marten.Testing/Storage/DocumentTableTester.cs
src/Marten/Marten.csproj

- Fix System.Transactions related warning in Marten
- Fix xunit related warnings in Marten.Testing
- Suppress warnings for CS0618 in Marten
- Suppress warnings for xUnit1013 and CS0618 in Marten.Testing and Marten.NodaTime.Testing
fixes #1313

Fix warnings in projects

---

src/Marten.Testing/StoreOptionsTests.cs
src/Marten/Storage/StorageFeatures.cs
src/Marten/Storage/SystemFunctions.cs
src/Marten/Transforms/ITransforms.cs

- Fix to ensure transforms functions, system functions, storage features
are added only once to the dictionary
Fixes #1306

Fix to ensure functions and storage features are added only once - fixes #1306

---

src/Marten.Testing/Schema/configuring_foreign_key_fields_Tests.cs
src/Marten/Schema/DocumentMapping.cs

Fixes #1311 - Unable to create a self referencing foreign key

---

src/Marten.Testing/Bugs/Bug_1325_Any_with_contains_on_IList_of_string.cs
src/Marten/Linq/CollectionAnyContainmentWhereFragment.cs

- Fix Any with Contains subquery fails with CamelCase serialization
- Unit tests
- Fixes GH-1325

Fix Any with Contains subquery fails with CamelCase serialization

---

src/Marten.Testing/Schema/configuring_foreign_key_fields_Tests.cs

Add unit test for ForeignKey on the same member as Identity - unit test for #1226.

Add unit test for ForeignKey on same member as Identity

---

src/Marten.Testing/Schema/ForeignKeyDefinitionTests.cs
src/Marten/Schema/ForeignKeyDefinition.cs

- Fix schema generation for Foreign key with tenancy conjoined
- Fixes GH-1297

Fix schema generation for Foreign key with tenancy conjoined

---

documentation/documentation/documents/tenancy/basicoperations.md
src/Marten.Testing/MultiTenancy/using_mix_of_tenanted_and_not_tenanted_documents.cs

- Update docs wording and sample for tenancy basic operations
- Fixes GH-1253

Update docs wording and sample for tenancy basic operations

---

src/Marten.Testing/Events/Projections/custom_async_transformation_of_events.cs
src/Marten/Events/Projections/ViewProjection.cs

When Delete and Store events on the same stream were on the same page of the ViewProjection, Delete would always happen after calling Store, causing the events to potentially be processed out of order

Fixes an issue where the `ViewProjection` class can process events out of order

---

documentation/documentation/documents/tenancy/configuring.md

change 'fine-graned' to 'fine-grained'

fix (typo): fix typo in configuring.md

---

README.md
martenbuild.cs
src/DinnerParty/DinnerParty.csproj
src/DinnerParty/DinnerParty.project.json
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj
src/Marten.NodaTime/Marten.NodaTime.csproj
src/Marten.Testing.OtherAssembly/Marten.Testing.OtherAssembly.csproj
src/Marten.Testing/App.config
src/Marten.Testing/Bugs/Bug_949_connection_closing_issue_with_transaction_scope.cs
src/Marten.Testing/IntegratedFixture.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/ability_to_use_an_existing_connection_and_transaction.cs
src/Marten.Testing/performance_tuning.cs
src/Marten/Events/Projections/Async/ProjectionTrack.cs
src/Marten/Exceptions/MartenCommandNotSupportedException.cs
src/Marten/Linq/Parsing/StringEndsWith.cs
src/Marten/Linq/Parsing/StringStartsWith.cs
src/Marten/Marten.csproj
src/Marten/Services/ManagedConnection.cs
src/NuGet.Config

Updated also:
- `System.Threading.Tasks.Dataflow` to `4.10.0`
- `System.Reflection.Emit.Lightweight`  to `4.6.0`
and internal dependency:
- `Microsoft.NET.Test.Sdk` to `16.3.0`

Upgraded Npgsql to 4.1.1 and updated to .NET 4.6.1 from .NET 4.6

---

martenbuild.csproj

update Bullseye and SimpleExce to latest RTM

---

src/Marten.Testing/Linq/Compatibility/simple_where_clauses.cs
src/Marten/Linq/WhereFragment.cs
src/Marten/Util/TypeMappings.cs

#1380 - NullReferenceException when IQueryable converting String.Equals 

---

src/Marten.Testing/Linq/query_for_sum_Tests.cs
src/Marten.Testing/Target.cs
src/Marten/Schema/JsonLocatorField.cs

Fixes #1376 - check for null value with nullable enum type in Linq query

---

src/Marten.Testing/Bugs/Bug_337_certain_boolean_searches_are_not_using_searchable_field.cs
src/Marten.Testing/Linq/BoolNotVisitorTests.cs
src/Marten/Linq/NotVisitor.cs

Fix GH-1374

---

martenbuild.cs
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.NodaTime/Marten.NodaTime.csproj
src/Marten/Marten.csproj

Bump up version of csproj files and martenbuild file to 3.10.0

Release 3.10.0

---

src/Marten.Testing/Examples/ConfiguringDocumentStore.cs

Fixes a spelling error in the documentation.

performas -> performs spelling error fix

---

src/Marten.Testing/Acceptance/computed_indexes.cs
src/Marten/Schema/ComputedIndex.cs

While trying to enforce a business rule of uniqueness for certain set of columns regardless the content casing I ran into a DDL generation bug. The code was generating something like 
```
CREATE UNIQUE INDEX mt_doc_measurand_uidx_departmentname ON public.mt_doc_measurand (lower(  (data ->> 'Department'), (data ->> 'Name')));
```
The problem was that the column part was determined in the ComputedIndex constructor where there is no way to know any custom casing. The generated DDL had thus lower call for all fields where it should have had lower/upper call for each individual column.
Fixed this by moving column generation as part of DDL generation where casing could be used with desired value.

Fix ComputedIndex DDL generation when non-default casing is present

---

documentation/documentation/events/projections/custom.md
src/Marten.Testing/Events/Projections/custom_transformation_of_events.cs

Added missing documentation for updateOnly view projection

---

documentation/content/stylish-portfolio.css
documentation/splash.htm

Link to video: https://channel9.msdn.com/Events/dotnetConf/2018/S315
Fixes #1394

Added Marten introduction to main page from .NET Conf 2018

---

src/Marten.Testing/Bugs/Bug_1495_initial_data_populate_with_query_causing_null_ref_ex.cs
src/Marten/DocumentStore.cs

Initial Data: Query in Populate method

---

src/Marten.Schema.Testing/Bug_1484_store_overloads_Tests.cs
src/Marten.Schema.Testing/Hierarchies/end_to_end_document_hierarchy_usage_Tests.cs
src/Marten.Testing/Bugs/Bug_571_defensive_check_for_IEnumerable_of_T_in_Store.cs
src/Marten.Testing/MultiTenancy/can_upsert_to_explicitly_overridden_tenant_as_enumerable.cs
src/Marten/DocumentSession.cs
src/Marten/Events/EventStore.cs
src/Marten/Events/IEventStore.cs
src/Marten/IDocumentSession.cs
src/Marten/IQuerySession.cs
src/Marten/QuerySession.cs

Add overrides for LoadMany to support List<T> as opposed to T[].

---

src/Marten.CommandLine/Commands/Dump/DumpCommand.cs
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.Testing/Commands/DumpCommandSmokeTests.cs
src/Marten.Testing/Marten.Testing.csproj

Tightens up the behavior that cleans off existing files in the dump command

---

documentation/documentation/integration.md
documentation/documentation/order.txt
documentation/getting_started.md
src/AspNetCoreWithMarten/AspNetCoreWithMarten.csproj
src/AspNetCoreWithMarten/IssueController.cs
src/AspNetCoreWithMarten/Program.cs
src/AspNetCoreWithMarten/Properties/launchSettings.json
src/AspNetCoreWithMarten/Samples/ByConnectionString/Startup.cs
src/AspNetCoreWithMarten/Samples/ByNestedClosure/Startup.cs
src/AspNetCoreWithMarten/Samples/ByStoreOptions/Startup.cs
src/AspNetCoreWithMarten/Samples/ConfiguringSessionCreation/Startup.cs
src/AspNetCoreWithMarten/Samples/EagerInitialization/Startup.cs
src/AspNetCoreWithMarten/Samples/PerScopeSessionCreation/Startup.cs
src/AspNetCoreWithMarten/Startup.cs
src/AspNetCoreWithMarten/appsettings.Development.json
src/AspNetCoreWithMarten/appsettings.json
src/Marten.Testing/DevelopmentModeRegistry.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/MartenServiceCollectionExtensionsTests.cs
src/Marten.Testing/MultiTenancy/with_batched_queries.cs
src/Marten.Testing/MultiTenancy/with_optimistic_concurrency.cs
src/Marten.sln
src/Marten/Marten.csproj
src/Marten/MartenServiceCollectionExtensions.cs

The new `AddMarten()` service registrations we've been talking about for v3.12. I have not finished the documentation yet, but the code is ready to look at.
I'm punting on the async daemon to v4 if that's okay. 
I'll be adding more docs in my tomorrow. Sorry, but that was just a bit too much tonight.

DI registrations

---

martenbuild.cs
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.NodaTime/Marten.NodaTime.csproj
src/Marten/Marten.csproj

Bump up csproj and martenbuild files for 3.12.0

Release 3.12.0

---

planning/MartenV4-WastazComments.md
planning/MartenV4.md
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.Testing.OtherAssembly/Marten.Testing.OtherAssembly.csproj
src/Marten/Marten.csproj
src/Marten/V4/EventStoreSpike.cs

Hey all, there'll be more content from me on the event store at a minimum. I'm fine with moving this to another venue, but this was one of the suggestions for how to capture this and start a conversation about Marten v4

v4 Planning Document

---

src/Marten.Schema.Testing/DuplicatedFieldTests.cs
src/Marten/Schema/DuplicatedField.cs

- Fix the duplicate field schema generation to respect casing
- fixes GH-1519

Fix duplicate field schema generation to respect casing

---

src/Marten.Testing/Acceptance/computed_indexes.cs

Enriched index configuration sample to document possible index scopes (Global|PerTenant).

Update computed_indexes.cs sample

---

src/Marten.NodaTime/Marten.NodaTime.csproj
src/Marten/Marten.csproj

- Update min. version of npgsql and npgsql.* libs to 4.1.4
- fixes #1529

Update min. version of npgsql and npgsql.* libs to 4.1.4 - closes #1529

---

package-lock.json
package.json

- Update mocha and chai to latest versions
- Remove lodash from dev dependencies since it not a direct dependency
(dependabot is messing up the dependencies)

Update js dev build dependencies

---

src/Marten.Testing/Marten.Testing.csproj
src/Marten.Testing/performance_tuning.cs

Did a litte refresh in the samples, to reflect changes in the ISerializer interface. 
Also added `_options ` to all methods, because it leads to Jil.DeserializationExceptions when options for serializing and deserialzing differ.
Also removed the #ifdefs for the JilSerializer.

Cleaned up sample for using JIL.

---

src/Marten.Testing/Linq/negating_predicate_with_binary_operator_tests.cs
src/Marten.Testing/Linq/query_negating_predicate_with_binary_operator_tests.cs
src/Marten/Linq/WhereClauseVisitor.cs

- Fix handling of negating predicate with binary operator
- fixes GH-1568

Fix handling of negating predicate with binary operator

---

src/Marten.Testing/Bugs/Bug_962_initial_data_populate_causing_null_ref_ex.cs
src/Marten.Testing/Documents/Company.cs

Without the Static ID, Initial Data creates the data every time we run the application.
I have added a static GUID to make that obvious

Added Static ID for initial data Documentation

---

src/Marten/Internal/CodeGeneration/BulkLoaderBuilder.cs

Fix for issue https://github.com/JasperFx/marten/issues/1594

Add limit 0 to create a temp table with schema only

---

src/Marten/Schema/SQL/mt_get_next_hi.sql
src/Marten/Schema/SQL/mt_immutable_timestamp.sql
src/Marten/Schema/SQL/mt_immutable_timestamptz.sql
src/Marten/Schema/SQL/mt_mark_event_progression.sql
src/Marten/Schema/SQL/mt_stream.sql

- Fix mixed tab spaces and formatting in sql files
- Fixes #1216

Fix mixed tab spaces and formatting in sql files

---

src/Marten.Testing/CoreFunctionality/document_session_sort_large_operation_bundle_Tests.cs
src/Marten/Internal/UnitOfWork.cs

I have a problem with some changes in one session. 
**System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'Marten.Services.UnitOfWork+StorageOperationWithDeletionsComparer'.**

Sorting Problem

---

src/Marten.Testing/CoreFunctionality/document_session_sort_large_operation_bundle_Tests.cs
src/Marten/Services/UnitOfWork.cs

- Fix sorting when only one operation is a deletion - retrofit the fix on master #1588 into 3.x
* Add failing test

Sorting problem with one operation being delete on 3.x

---

src/Marten/Events/Projections/Aggregator.cs
src/Marten/Events/Projections/Async/Daemon.cs
src/Marten/Internal/Storage/IdentityMapDocumentStorage.cs
src/Marten/Patching/PatchOperation.cs
src/Marten/Services/VersionTracker.cs
src/Marten/Storage/StorageFeatures.cs
src/Marten/Storage/TableDelta.cs
src/Marten/Transforms/ITransforms.cs

@jeremydmiller  u mentioned trying to eke out perf in marten. in that context is this type of PR useful?

remove some duplicate dictionary lookups

---

src/AspNetCoreWithMarten/Startup.cs
src/Marten/Events/Projections/AggregateFinder.cs
src/Marten/Events/Projections/StringIdentifiedAggregateFinder.cs
src/Marten/Events/Projections/ViewProjection.cs
src/Marten/Internal/Storage/IdentityMapDocumentStorage.cs
src/Marten/Services/ManagedConnection.cs

https://blog.stephencleary.com/2016/12/eliding-async-await.html

remove some redundant state machines

---

src/Marten.NodaTime.Testing/Acceptance/noda_time_acceptance.cs
src/Marten.Schema.Testing/SpecificationExtensions.cs
src/Marten.Testing/Events/Projections/custom_async_transformation_of_events.cs
src/Marten.Testing/Harness/SpecificationExtensions.cs
src/Marten/Schema/DbObjects.cs
src/Marten/Util/LambdaBuilder.cs

BTW please let me know if these PRs are getting annoying

use static locals to avoid some alloc

---

src/Marten.Schema.Testing/DocumentMappingTests.cs
src/Marten/Schema/GinIndexedAttribute.cs

Fix for using wrong overload in GinIndexedAttribute and test

---

src/Marten.Testing/Bugs/equality_not_symmetric.cs
src/Marten/Linq/Parsing/Methods/StringComparisonParser.cs

This PR fixes:
https://github.com/JasperFx/marten/issues/1703
Also includes several tests to test for this issue

Fix issue 1703: symmetric equality

---

src/Marten.AsyncDaemon.Testing/Marten.AsyncDaemon.Testing.csproj
src/Marten.CommandLine.Testing/Marten.CommandLine.Testing.csproj
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj
src/Marten.NodaTime/Marten.NodaTime.csproj
src/Marten.Schema.Testing/Marten.Schema.Testing.csproj
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Events/Daemon/AsyncProjectionHostedService.cs
src/Marten/Events/Daemon/AsyncProjectionShardBase.cs
src/Marten/Events/Daemon/HighWater/HighWaterAgent.cs
src/Marten/Events/Daemon/ProjectionAgent.cs
src/Marten/Marten.csproj

Closes #1716 
I also noticed some churn across the npgsql and JasperFx ecosystem so bumped everything to latest while I'm here. Seems to all be working fine.

Structured Logging + Dependency Pass

---

src/Marten.Schema.Testing/UniqueIndexTests.cs
src/Marten/Services/EventStreamUnexpectedMaxEventIdExceptionTransform.cs
src/Marten/Services/ManagedConnection.cs

Added transformation of the unique constraint exception into EventStreamUnexpectedMaxEventIdException when the streamid with version unique constraint were hit
Closes #1465

Added transformation of the unique constraint exception into EventStreamUnexpectedMaxEventIdException

---

src/Marten.Testing/Linq/MatchesSql/MatchesSqlExtensionsTests.cs
src/Marten.Testing/LinqExtensionsTests.cs
src/Marten/Linq/MatchesSql/MatchesSqlExtensions.cs
src/Marten/LinqExtensions.cs

Throw NotSupportedException in Marten only linq extensions

---

src/Marten.Testing/Events/flexible_event_metadata.cs
src/Marten/Events/Event.cs
src/Marten/Events/EventGraph.cs
src/Marten/Events/IEventStoreOptions.cs
src/Marten/Events/IReadOnlyEventStoreOptions.cs
src/Marten/Events/MetadataConfig.cs
src/Marten/Events/Schema/EventMetadataCollection.cs
src/Marten/Events/Schema/EventsTable.cs
src/Marten/Events/StreamAction.cs
src/Marten/Storage/Metadata/CausationIdColumn.cs
src/Marten/Storage/Metadata/CorrelationIdColumn.cs
src/Marten/Storage/Metadata/HeadersColumn.cs

* Implement flexible event metadata
* Add unit tests
* Add nullable ref. annotations
fixes https://github.com/JasperFx/marten/issues/780
PS: I will send a separate PR for the docs including both document and event meta data.

Implement flexible event metadata

---

src/Marten.Testing/Events/Projections/multiple_streams_projections.cs
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Events/Projections/ViewProjection.cs

@DariuszFirek, could you confirm that it covers your cases?

Added sample showing multiple streams projections.

---

docs/.vitepress/config.js
docs/guide/events/projections/view-projections.md
src/Marten.Testing/Events/Projections/ViewProjections/CustomGroupers/custom_grouper_with_document_session.cs
src/Marten.Testing/Events/Projections/ViewProjections/CustomGroupers/custom_slicer.cs
src/Marten.Testing/Events/Projections/ViewProjections/TestClasses.cs
src/Marten.Testing/Events/Projections/ViewProjections/simple_multi_stream_projection.cs
src/Marten.Testing/Events/Projections/ViewProjections/simple_multi_stream_projection_wih_one_to_many.cs

Added view projections samples and included them in the docs. Not yet written description. It will come with one of the next PRs. I want to gradually add content starting with samples to have them at least before getting the final docs.

Split, refactored and extended view projection samples

---

src/Marten.Testing/MartenServiceCollectionExtensionsTests.cs
src/Marten/MartenServiceCollectionExtensions.cs

Fix for GH-1888 to ensure the passed logger gets used

---

docs/guide/documents/tenancy/basic-operations.md
src/Marten.Testing/Bugs/Bug_1884_multi_tenancy_and_Any_query.cs
src/Marten.Testing/Linq/query_against_child_collections_integrated_Tests.cs
src/Marten.Testing/Linq/query_with_inner_query_with_CollectionToArrayJsonConverter_onProperty.cs
src/Marten/Linq/Parsing/WhereClauseParser.cs
src/Marten/Linq/SqlGeneration/ContainsIdSelectorStatement.cs
src/Marten/Linq/SqlGeneration/CountComparisonStatement.cs
src/Marten/Linq/SqlGeneration/DocumentStatement.cs
src/Marten/Linq/SqlGeneration/FlattenerStatement.cs
src/Marten/Linq/SqlGeneration/IdSelectorStatement.cs
src/Marten/Linq/SqlGeneration/SqlFragmentExtensions.cs
src/Marten/Linq/SqlGeneration/Statement.cs

Last minute Linq improvements for v4

---

src/Marten/Events/AppendEventFunction.cs
src/Marten/Events/EventsTable.cs
src/Marten/Events/Projections/Async/Fetcher.cs
src/Marten/Schema/SQL/mt_stream.sql

Fix for [Events loss in Marten.Events.Projections.Async.Fetcher under load #1879 ](https://github.com/JasperFx/marten/issues/1879)

Events loss in Fetcher under load

---

src/Marten.Schema.Testing/Bugs/Bug_1903_index_change_detection_with_predicate.cs
src/Marten.Testing/Acceptance/computed_indexes.cs
src/Marten.Testing/Logging/DefaultMartenLoggerTests.cs
src/Marten/Marten.csproj

Upgrade to Weasel 1.0. 

---

src/Marten.Testing/Events/Projections/ViewProjections/CustomGroupers/custom_grouper_with_events_transformation.cs
src/Marten.Testing/Events/Projections/ViewProjections/CustomGroupers/custom_grouper_with_multiple_result_records.cs
src/Marten/Events/Aggregation/AggregateProjection.CodeGen.cs
src/Marten/Events/Aggregation/AggregateProjection.cs
src/Marten/Events/Aggregation/FanOutOperator.cs
src/Marten/Events/Event.cs
src/Marten/Events/Projections/ViewProjection.cs

@jeremydmiller, do you think we could add some syntactic sugar to enable such a scenario when you need both grouper and fan out?

Added sample Event Grouper that transforms events (Grouping + FanOut)

---

docs/documents/full-text.md
src/AspNetCoreWithMarten/AspNetCoreWithMarten.csproj
src/CommandLineRunner/CommandLineRunner.csproj
src/IssueService/IssueService.csproj
src/Marten.AspNetCore.Testing/Marten.AspNetCore.Testing.csproj
src/Marten.AsyncDaemon.Testing/Marten.AsyncDaemon.Testing.csproj
src/Marten.CommandLine.Testing/Marten.CommandLine.Testing.csproj
src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj
src/Marten.PLv8.Testing/Marten.PLv8.Testing.csproj
src/Marten.Schema.Testing/Marten.Schema.Testing.csproj
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Marten.csproj
src/MartenBenchmarks/MartenBenchmarks.csproj
src/StorytellerRunner/StorytellerRunner.csproj

Did a patch bump of the dependencies for the release packages and a general bump for non-release packages.

Bumped dependencies - the most important Weasel to 1.0.6

---

docs/events/projections/index.md
docs/events/projections/rebuilding.md
src/Marten.AsyncDaemon.Testing/event_projections_end_to_end.cs

- Add docs sample for rebuild projection
- Fix #1979

Add docs sample for rebuild projection

---

src/Marten.Schema.Testing/Storage/DocumentTableTester.cs
src/Marten.Testing/Bugs/Bug_1982_custom_index_with_include.cs
src/Marten/Marten.csproj

- Update Marten to use Weasel v1.2.0
- Add unit test for #1982
- Add unit test for #1983
- Fix #1982
- Fix #1983

Update Marten to use Weasel v1.2.0

---

src/Marten.Testing/Bugs/Bug_1994_insert_update_on_same_object_in_transaction.cs
src/Marten.Testing/CoreFunctionality/UnitOfWork_PendingChanges_Functionality_Tests.cs
src/Marten/Internal/Operations/StorageOperation.cs

I seriously don't think we need more than this.

Better exception message for edge case. Closes GH-1994

---

src/Marten.Testing/CoreFunctionality/ejecting_a_document_type.cs
src/Marten/Events/Daemon/ProjectionUpdateBatch.cs
src/Marten/Internal/Sessions/DocumentSessionBase.cs
src/Marten/Internal/Sessions/LightweightSession.cs
src/Marten/Internal/UnitOfWork.cs
src/Marten/Services/ISessionWorkTracker.cs

Fixes https://github.com/JasperFx/marten/issues/2005

EjectAllOfType also clears WorkTracker (same as Eject does)

---

docs/documents/plv8.md

Old link is broken, Included link to their documentation

Xtuple binary download link is broken

---

documentation/documentation/admin/installing-plv8-windows.md

Found while perusing the docs.

(docs) Fix tiny typo

---

src/Marten.Testing/Services/BatchedQuerying/batched_querying_acceptance_Tests.cs
src/Marten/Services/BatchQuerying/BatchedOrderedQueryable.cs
src/Marten/Services/BatchQuerying/BatchedQueryable.cs
src/Marten/Services/BatchQuerying/IBatchedOrderedQueryable.cs
src/Marten/Services/BatchQuerying/IBatchedQueryable.cs

As per issue https://github.com/JasperFx/marten/issues/2026
Added basic unit test scenarios and made sure all existing batch query tests pass since OrderBy/OrderByDescending has been modified.

Added IBatchedOrderedQueryable and BatchedOrderedQueryable.

---

docs/configuration/json.md
src/CoreTests/Bugs/Bug_2099_json_serializer_should_handle_nulls.cs
src/CoreTests/CoreTests.csproj
src/DocumentDbTests/Metadata/getting_and_setting_headers.cs
src/EventSourcingTests/flexible_event_metadata.cs
src/Marten.Testing/performance_tuning.cs
src/Marten/Events/Event.cs
src/Marten/ISerializer.cs
src/Marten/Internal/Sessions/DocumentSessionBase.cs
src/Marten/Services/JsonNetSerializer.cs
src/Marten/Services/SystemTextJsonSerializer.cs

Includes regression tests.
Fixes #2099 
Fixes #2100

Bugs serializing json and getting headers

---

src/DocumentDbTests/Bugs/Bug_2018_fts_string_list.cs
src/Marten/Schema/FullTextIndex.cs

Fix GH-2018

---

src/DocumentDbTests/Reading/Linq/InvariantCultureIgnoreCase_filtering.cs
src/Marten/Linq/Parsing/Methods/StringComparisonParser.cs

- Fix to not escape backslash when using case insensitive string search
fixes GH-1802

Fix GH-1802

---

src/DocumentDbTests/Indexes/computed_indexes.cs
src/Marten.Testing/Documents/Target.cs
src/Marten/Schema/ComputedIndex.cs

Fix GH-2028

---

docs/documents/querying/linq/operators.md
src/DocumentDbTests/Reading/Linq/query_with_order_by_dynamic_props_tests.cs
src/Marten.Testing/Examples/LinqExamples.cs
src/Marten/QueryableExtensions.cs

- Add functionality to order results by dynamic properties
- Add docs
fixes GH-2035

LINQ ordering by dynamic properties

---

docs/documents/querying/linq/booleans.md
docs/documents/querying/linq/nulls.md
src/CoreTests/Bugs/Bug_2103_able_to_add_metadata_tables_in_migrations_to_events_table.cs
src/EventStoreMigrations/EventStoreMigrations.csproj
src/EventStoreMigrations/Program.cs
src/EventStoreMigrations/TestCommand.cs
src/Marten.sln
src/Marten/Events/QueryEventStore.cs

Test harness to prove GH-2103 works, extra storage checks in event storage

---

src/Marten.CommandLine/Commands/Projection/ProjectionCommand.cs
src/Marten.CommandLine/Commands/Projection/ProjectionInput.cs

Filter out Live projections in command line rebuild

---

src/Marten.AsyncDaemon.Testing/Bugs/Bug_2177_query_session_tenancy_in_daemon.cs
src/Marten/Events/Aggregation/TenantSliceGroup.cs
src/Marten/Internal/Sessions/DocumentSessionBase.SaveChanges.cs
src/Marten/Internal/Sessions/QuerySession.cs
src/Marten/Internal/UpdateBatch.cs

Couple regression problems from > v5.1 fixes. Another day in the life of supporting a really complicated library.

Fixes for Async Daemon

---

docs/configuration/json.md

Added documentation to note how to do private setters in System.Text.Json

Updated docs to include private setter usage in System.Text.Json

---

src/DocumentDbTests/Bugs/BigIntergerTests.cs
src/DocumentDbTests/Reading/Linq/query_with_biginteger_tests.cs
src/Marten/Services/Json/SystemTextJsonBigIntegerConverter.cs
src/Marten/Services/SystemTextJsonSerializer.cs

- Test to verify it's working with Newtonsoft.Json
- Test to verify failure with System.Text.Json
- New converter for System.Text.Json
- Test to Serialize with Newtonsoft and Deserialize with STJ
- Test to Serialize with STJ and Deserialize with Newtonsoft
Labeled as Bug and Enhancement cos it enchances the usage of STJ and fixes the fact it was broken. (broken cos STJ is a bit turdy)
Fixes #2194

Big integer support in System.Text.Json

---

src/CoreTests/Bugs/Bug_2210_ambient_transactions_plus_passing_in_a_connection.cs
src/Marten/Internal/Sessions/AmbientTransactionLifetime.cs
src/Marten/Internal/Sessions/DirtyCheckingDocumentSession.cs
src/Marten/Services/SessionOptions.cs

Ability to pass a connection into a session *and* enlist in ambient transaction

---

docs/events/projections/view-projections.md
src/EventSourcingTests/EventSourcingTests.csproj
src/EventSourcingTests/Examples/TeleHealth/Board.cs
src/EventSourcingTests/Examples/TeleHealth/BoardViewProjection.cs
src/EventSourcingTests/Examples/TeleHealth/TeleHealthSample.cs
src/Marten.AsyncDaemon.Testing/Marten.AsyncDaemon.Testing.csproj
src/Marten.AsyncDaemon.Testing/TestingSupport/Movement.cs
src/Marten.AsyncDaemon.Testing/ViewProjectionTests.cs
src/Marten.AsyncDaemon.Testing/cross_stream_aggregation.cs
src/Marten/Events/Aggregation/EventListExtensions.cs
src/Marten/Events/Aggregation/EventSlice.cs
src/Marten/Events/Aggregation/FanOutOperator.cs
src/Marten/Events/Aggregation/IEventGrouping.cs
src/Marten/Events/Aggregation/TenantSliceGroup.cs
src/Marten/Events/Projections/CrossStreamAggregateProjection.cs

New CrossStreamAggregateProjection recipe. 

---

src/Marten/Linq/Filters/FullTextWhereFragment.cs

Static values in the sql query perform much faster

Don't use parameters with to_tsvector to greatly improve performance

---

src/CoreTests/Bugs/Bug_2274_not_equals_canonicalization.cs
src/DocumentDbTests/Bugs/Bug_2283_problems_with_duplicated_DateTime_fields.cs
src/DocumentDbTests/HierarchicalStorage/Bug_2282_SOE_on_hiearchical_usage.cs
src/EventSourcingTests/Bugs/Bug_2281_fetch_for_writing_with_no_events_returned.cs
src/Marten/Events/EventGraph.Processing.cs
src/Marten/Exceptions/InvalidUtcDateTimeUsageException.cs
src/Marten/Exceptions/MartenExceptionTransformer.cs
src/Marten/Linq/MartenLinqQueryProvider.cs
src/Marten/Marten.csproj
src/Marten/Schema/SubClasses.cs

* Better exception message when users get problems with DateTime duplicated fields. Closes GH-2283

Bug fixes on top of 5.6

---

src/CoreTests/adding_custom_schema_objects.cs

Added 3 more tests that I hope are easy to understand to verify the functionality and provide a test we can pull into some documentation.
For the extension, i picked unaccent, it ships with PostgreSQL so it should work for everyone.

Added some additional unit tests to verify Function/Sequence/Extension on ExtendedSchemaObjects

---

Directory.Build.props
docs/events/versioning.md
src/EventSourcingTests/Bugs/Bug_2025_event_inheritance_in_projection.cs
src/EventSourcingTests/SchemaChange/MultipleVersions/Classes/ClrUpcastConfiguration.cs
src/EventSourcingTests/SchemaChange/MultipleVersions/Classes/JsonNetUpcastConfiguration.cs
src/EventSourcingTests/SchemaChange/MultipleVersions/Classes/SystemTextJsonUpcastConfiguration.cs
src/EventSourcingTests/SchemaChange/MultipleVersions/Lambdas/ClrUpcastConfiguration.cs
src/EventSourcingTests/SchemaChange/MultipleVersions/Lambdas/JsonNetUpcastConfiguration.cs
src/EventSourcingTests/SchemaChange/MultipleVersions/Lambdas/SystemTextJsonUpcastConfiguration.cs
src/EventSourcingTests/SchemaChange/MultipleVersions/MultipleSchemaVersions.cs
src/EventSourcingTests/SchemaChange/MultipleVersions/ShoppingCart.cs
src/EventSourcingTests/SchemaChange/SimpleMappings.cs
src/EventSourcingTests/SchemaChange/Upcasters.cs
src/Marten.AsyncDaemon.Testing/Bugs/Bug_2073_tenancy_problems.cs
src/Marten.AsyncDaemon.Testing/Bugs/Bug_2074_recovering_from_errors.cs
src/Marten.AsyncDaemon.Testing/Bugs/Bug_2245_async_daemon_getting_stuck.cs

Thanks go to @alexeyzimarev for a hint. 😀

Enabled C# 10 features and removed conditional pragmas for records

---

src/DocumentDbTests/Reading/Linq/query_with_enums_Tests.cs
src/Marten/Marten.csproj

This includes the following items from `Weasal.Postgresql`:
- https://github.com/JasperFx/weasel/pull/69
- https://github.com/JasperFx/weasel/pull/70

Reference latest version of `Weasal.Postgresql`

---

src/Marten.CommandLine.Tests/ProjectionControllerTests.cs
src/Marten.CommandLine/Commands/Projection/IProjectionHost.cs
src/Marten.CommandLine/Commands/Projection/ProjectionController.cs
src/Marten.CommandLine/Commands/Projection/ProjectionHost.cs
src/Marten.CommandLine/Commands/Projection/ProjectionInput.cs

Provide an option to specify projection rebuild command timeout for Marten.CommandLine

---

docs/documents/identity.md
src/DocumentDbTests/Bugs/Bug_2327_using_identity_extension_on_class_with_invalid_type_id_field.cs
src/Marten/Schema/DocumentMapping.cs

Gh issue 2327 fix identity extension

---

src/DocumentDbTests/Bugs/identity_map_with_records.cs
src/Marten/Internal/Storage/IdentityMapDocumentStorage.cs

Fixes IdentityMap to not throw when records are loaded & modified.

---

docs/configuration/json.md
src/EventSourcingTests/Json/SystemTextJsonRecordSerializationTests.cs
src/Marten.Testing/Examples/UsingSystemTextJsonSerializer.cs

Updated sample to not use redundant doubled customization.

Added test for SystemTextJson serialization and projections handling with records

---

src/EventSourcingTests/Aggregation/fetching_live_aggregates_for_writing.cs
src/Marten/Events/EventStore.FetchForWriting.cs
src/Marten/IDocumentOperations.cs
src/Marten/Internal/Sessions/DocumentSessionBase.cs

Fixes for v6

---

docs/documents/querying/batched-queries.md
src/EventSourcingTests/Bugs/Bug_2465_make_event_serialization_strategy_be_lazy.cs
src/Marten/DocumentStore.cs
src/Marten/Events/EventDocumentStorage.cs
src/Marten/Events/EventGraph.cs
src/Marten/Events/EventMapping.cs

Lazy serializer resolution in event data reading

---

docs/events/projections/multi-stream-projections.md

Docs: using MultiStreamAggregation requires the Async Daemon

---

Analysis.Build.props
src/CommandLineRunner/CommandLineRunner.csproj
src/CoreTests/CoreTests.csproj
src/DocumentDbTests/DocumentDbTests.csproj
src/EventPublisher/EventPublisher.csproj
src/EventSourceWorker/EventSourceWorker.csproj
src/EventSourcingTests/EventSourcingTests.csproj
src/Marten.AspNetCore.Testing/Marten.AspNetCore.Testing.csproj
src/Marten.AsyncDaemon.Testing/Marten.AsyncDaemon.Testing.csproj
src/Marten.CommandLine.Tests/Marten.CommandLine.Tests.csproj
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj
src/Marten.NodaTime/Marten.NodaTime.csproj
src/Marten.PLv8.Testing/Marten.PLv8.Testing.csproj
src/Marten.Testing/Marten.Testing.csproj
src/Marten/DocumentStore.IMartenStorage.cs
src/Marten/Marten.csproj
src/MartenBenchmarks/MartenBenchmarks.csproj

Updated also all the rest of packages

Bumped code generation packages to 2.0

---

src/Marten/Events/Daemon/HotColdCoordinator.cs

This was causing a deadlock in my test pipeline as the lock was being retried forever.

Ensure hot-cold coordinator exits if host cancellation occurs

---

.github/workflows/docs.yml
docs/configuration/hostbuilder.md
docs/documents/sessions.md
docs/migration-guide.md
docs/schema/extensions.md
src/CoreTests/BootstrappingExamples.cs
src/Marten.Testing/Examples/SagaStorageExample.cs

Adds a hint for the `IConfigureMarten<T>` interface when using `AddMartenStore<T>` method to bootstrap Marten.

docs: add hint for IConfigureMarten<T>

---

src/DocumentDbTests/Reading/Linq/Compatibility/Support/LinqTestContext.cs
src/DocumentDbTests/Reading/Linq/Compatibility/casing_support.cs
src/DocumentDbTests/Reading/Linq/Compatibility/select_transforms.cs
src/Marten/Linq/Parsing/SelectTransformBuilder.cs
src/Marten/Services/JsonNetSerializer.cs
src/Marten/Util/StringExtensions.cs

Fixed JSON casing support in Linq selects

---

docs/events/versioning.md
src/EventSourcingTests/SchemaChange/Upcasters.cs
src/Marten.AsyncDaemon.Testing/basic_async_daemon_tests.cs
src/Marten/Events/Daemon/EventTypeFilter.cs
src/Marten/Events/EventGraph.cs
src/Marten/Events/Projections/ProjectionBase.cs

Support upcasters within async projections

---

src/EventSourcingTests/Bugs/nulls_in_event_name_cache.cs
src/Marten/Events/EventGraph.cs

Fix null ref in event alias lookup.
Fixes #2650.

Fixes event types aliases resolution for not mapped explicitly event types

---

docs/configuration/cli.md
docs/configuration/hostbuilder.md
docs/configuration/multitenancy.md
docs/schema/extensions.md
src/CoreTests/DatabaseMultiTenancy/SingleServerMultiTenancyTests.cs
src/CoreTests/adding_custom_schema_objects.cs

Expecting the extension to be automatically enabled in new tenants.

Automatically enable extensions for tenants

---

Analysis.Build.props
src/CoreTests/CoreTests.csproj
src/DocumentDbTests/DocumentDbTests.csproj
src/DocumentDbTests/Indexes/full_text_index.cs
src/EventPublisher/EventPublisher.csproj
src/EventSourcingTests/EventSourcingTests.csproj
src/Marten.AspNetCore.Testing/Marten.AspNetCore.Testing.csproj
src/Marten.AsyncDaemon.Testing/Marten.AsyncDaemon.Testing.csproj
src/Marten.CommandLine.Tests/Marten.CommandLine.Tests.csproj
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj
src/Marten.PLv8.Testing/Marten.PLv8.Testing.csproj
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Marten.csproj
src/MartenBenchmarks/MartenBenchmarks.csproj

Bumped Weasel to 6.0.2 to include a fix for full-text index delta calculation from JasperFx/weasel#94.
Added tests to prove that it works now, fixing false-positive ones we had before.
Bumped other packages.
@michaldog, @elexisvenator FYI

Fixed calculating delta for Full Text Index with multiple columns

---

Analysis.Build.props
docs/events/projections/live-aggregates.md
src/AspNetCoreWithMarten/AspNetCoreWithMarten.csproj
src/CoreTests/CoreTests.csproj
src/DocumentDbTests/DocumentDbTests.csproj
src/EventSourcingTests/EventSourcingTests.csproj
src/Marten.AspNetCore.Testing/Marten.AspNetCore.Testing.csproj
src/Marten.AsyncDaemon.Testing/Marten.AsyncDaemon.Testing.csproj
src/Marten.CommandLine.Tests/Marten.CommandLine.Tests.csproj
src/Marten.CommandLine/Marten.CommandLine.csproj
src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj
src/Marten.PLv8.Testing/Marten.PLv8.Testing.csproj
src/Marten.Testing/Marten.Testing.csproj
src/Marten/Marten.csproj
src/MartenBenchmarks/MartenBenchmarks.csproj

Fixes #2663
This will cause to have next Milestone as 6.1.0 as Weasel is bumped by a minor version.

Updated Weasel to 6.1.0 and other dependencies

---

docs/configuration/storeoptions.md
src/EventSourcingTests/EventStreamUnexpectedMaxEventIdExceptionTransformTest.cs
src/EventSourcingTests/appending_events_workflow_specs.cs
src/EventSourcingTests/event_statistics.cs
src/EventSourcingTests/fetching_stream_state.cs
src/Marten/DefaultMartenLogger.cs
src/Marten/DocumentStore.cs
src/Marten/Events/CodeGeneration/AggregateEventProcessingFrame.cs
src/Marten/Events/Daemon/ProjectionDaemon.cs
src/Marten/Events/Daemon/Resiliency/RetryBlock.cs
src/Marten/Events/EventGraph.Processing.cs
src/Marten/Events/EventGraph.cs
src/Marten/Internal/Sessions/DocumentSessionBase.SaveChanges.cs
src/Marten/Marten.csproj

Projection error handling improvements

---

src/Marten/StoreOptions.cs

XML comment was different to the actual default value

StoreOptions.AutoCreateSchemaObjects xml doc fix

---

docs/events/projections/healthchecks.md

Added info about async health check installation

AsyncHealthCheck docs updated

---

docs/devops/devops.md

Initial documentation for Dev-Ops around Marten. One way to achieve it, but can be improved on later. Given as starting point

#2762 Include documentation on DevOps including database migrations

---

docs/schema/index.md

https://github.com/JasperFx/marten/issues/2879

Add warning about schema changes

---

src/Marten/Events/Aggregation/GeneratedAggregateProjectionBase.CodeGen.cs
src/Marten/Events/Projections/ProjectionOptions.cs
src/Marten/Events/Schema/EventsTable.cs
src/Marten/Events/Schema/StreamsTable.cs
src/Marten/Internal/Sessions/DocumentSessionBase.cs
src/Marten/Storage/DocumentTable.cs

Odds and ends. Last couple bug fixes, assorted changes driven by "Critter Stack Pro" usage. Not ready to be pulled in, just wanted CI to run on it for now.

Fixes and improvements for Critter Stack Pro rollout

---

README.md

Assuming you want to keep this text reachable.

Use archive.org version of dead link

---

docs/events/projections/rebuilding.md
src/Marten.AsyncDaemon.Testing/event_projections_end_to_end.cs
src/Marten/Events/AsyncProjectionTestingExtensions.cs

Correction for `WaitForNonStaleProjectionDataAsync` method

---

src/Marten/Internal/Sessions/DocumentSessionBase.SaveChanges.cs

Ensures transaction is initialized when executing a batch avoiding unnecessary errors and churn.

---

src/EventSourcingTests/Bugs/Bug_3184_Projection_named_Projection.cs
src/Marten/Marten.csproj

Ability to do codegen for a projection named "Projection"

---

src/Marten/Events/Projections/IProjection.cs
src/Marten/Events/Projections/IProjectionSource.cs

Based on [this](https://discord.com/channels/1074998995086225460/1074999076896112661/1241458767032356915) Discord conversation

Explain intend of IProjection and IProjectionSource

---

docs/scenarios/command_handler_workflow.md
src/EventSourcingTests/Aggregation/fetching_inline_aggregates_for_writing.cs
src/EventSourcingTests/EventGraphTests.cs
src/Marten/Events/EventGraph.cs
src/Marten/Events/Fetching/FetchInlinedPlan.cs
src/Marten/Events/IEventStoreOptions.cs

Revert "Opt out for identity map optimizations of inline aggregates"

---

src/DocumentDbTests/SessionMechanics/identity_map_mechanics.cs
src/DocumentDbTests/Writing/document_inserts.cs
src/EventSourcingTests/Aggregation/fetching_inline_aggregates_for_writing.cs
src/EventSourcingTests/Aggregation/fetching_live_aggregates_for_writing.cs
src/Marten/Events/Aggregation/AggregationRuntime.cs
src/Marten/Events/Fetching/FetchInlinedPlan.cs
src/Marten/IDocumentOperations.cs
src/Marten/Internal/Sessions/DocumentSessionBase.cs
src/Marten/Internal/Sessions/LightweightSession.cs
src/Marten/Internal/Sessions/QuerySession.Load.cs
src/Marten/Internal/Sessions/QuerySession.Storage.cs
src/Marten/Internal/Sessions/QuerySession.cs

Revert "Fetch for writing optimization for Inline projections"

---

docs/.vitepress/config.mts
docs/community/tools-and-libraries.md

- Add community section with tools and libraries page
- Collapse all the top level section in sidebar by default for better discoverability

Add community section to docs

---

src/Marten/Events/Operations/AppendEventOperationBase.cs
src/Marten/Events/Operations/InsertStreamBase.cs
src/Marten/Linq/Parsing/WhereClauseParser.cs
src/Marten/StoreOptions.MemberFactory.cs

Stuff that came up for a JasperFx client

Hardening LINQ against some unusual dynamic Expressions

---

src/Marten/LinqParsing.cs

Update LinqParsing to use separate cache of resolved method parsers by module of the method

---

src/EventSourcingTests/Bugs/Bug_fetch_for_writing_cache.cs
src/Marten/Events/Fetching/FetchInlinedPlan.cs
src/Marten/Events/Fetching/InlineFetchPlanner.cs

Identity map and FetchForWriting

---

.github/workflows/on-push-do-ci-build-pg12-plv8-jsonnet.yml
.github/workflows/on-push-do-ci-build-pg12-plv8-systemtextjson.yml
.github/workflows/on-push-do-ci-build-pg15-jsonnet.yml
.github/workflows/on-push-do-ci-build-pgLatest-systemtextjson.yml
azure-pipelines.yml
src/ValueTypeTests/linq_querying_with_value_types.cs

The error is inside postgres containers. (marten pipeline logs)
The reason is some commands are called with "root" role (default container user) which doesn't exist

dealing with FATAL:  role "root" does not exist

---

src/DaemonTests/event_fetcher_tests.cs
src/Marten/Events/EventGraph.cs

Adds support for generic aggregates, particularly in the ``type``  column of the ``mt_streams`` table.

consider generic aggregates

---

docs/documents/multi-tenancy.md
src/CoreTests/Partitioning/partitioning_configuration.cs
src/Marten/AdvancedOperations.cs
src/Marten/Events/Daemon/DeadLetterEvent.cs
src/Marten/Internal/Sessions/QuerySession.Execution.cs
src/Marten/Marten.csproj
src/Marten/Schema/MartenManagedTenantListPartitions.cs
src/Marten/Schema/SingleTenantedAttribute.cs
src/Marten/StoreOptions.cs
src/Marten/Util/ResilientPipelineBuilderExtensions.cs
src/MultiTenancyTests/marten_managed_tenant_id_partitioning.cs

Docs on martne managed tenant id partitioning

Marten managed tenant id partitioning. Closes GH-3407

---

src/Marten/Events/Operations/EstablishTombstoneStream.cs
src/Marten/Services/EventStreamUnexpectedMaxEventIdExceptionTransform.cs

Fix `EventStreamUnexpectedMaxEventIdExceptionTransform` for archived stream partitioning

---

src/EventSourcingTests/Projections/using_explicit_code_for_live_aggregation.cs
src/Marten.Testing/hiearchy_projection.cs
src/Marten/Events/Projections/ProjectionOptions.cs

3547 Explicit live aggregation should not create tables

---

src/Marten/Linq/Members/StringValueTypeMember.cs
src/Marten/Linq/Parsing/LinqQueryParser.Handlers.cs

Fix for value type Select(x => x.ValueTypeWrappingString) errors

---

src/Marten/Events/Projections/ProjectionOptions.cs

Show a hint in the duplicate projection exception  how to resolve duplicates

Show a hint in the duplicate projection exception

---

src/Marten/Events/Aggregation/Rebuilds/QueryForTenantIds.cs

Fixes #3688 Fix rebuild querryforteantids using discrepancy in streamalias

---

src/DocumentDbTests/MultiTenancy/mixed_single_and_conjoined_tenancy.cs

…nanted session or nested session

Additional test coverage on using single tenanted documents from tenanted sessions

---

src/EventSourcingTests/removing_protected_information.cs
src/Marten/Events/EventGraph.Masking.cs
src/Marten/Events/IEventStoreOptions.cs

* Fix Test since we need to check the actual data instead of the reference now.
* Expose new functionality via Interface.

fix: #3823 fix tests fix interface

---

src/EventSourcingTests/delete_single_event_stream.cs
src/Marten/Storage/MartenDatabase.DocumentCleaner.cs

also clean-up unused synchronous version of DeleteSingleEventStreamAsync

Check if tenant id is not empty before adding parameter to query

---

docs/events/metadata.md
src/CommandLineRunner/Program.cs
src/EventSourcingTests/EventGraphTests.cs
src/EventSourcingTests/Examples/MetadataExamples.cs
src/EventSourcingTests/Metadata/overriding_metadata_on_appends.cs
src/EventSourcingTests/QuickAppend/quick_append_with_server_timestamps_end_to_end.cs
src/Marten/Events/CodeGeneration/EventDocumentStorageGenerator.cs
src/Marten/Events/EventGraph.Processing.cs
src/Marten/Events/EventGraph.cs
src/Marten/Events/Operations/QuickAppendEventsOperationBase.cs
src/Marten/Events/Schema/QuickAppendEventFunction.cs
src/Marten/Marten.csproj

upgraded JasperV X.Events
Docs on overriding event metadata
more tests and code for being able to override event metadata

Ability to override event metadata by event. Closes GH-3882

---

docs/events/metadata.md
src/EventSourcingTests/Metadata/overriding_metadata_on_appends.cs
src/Marten.Testing/Examples/MetadataUsage.cs
src/Marten/Events/CodeGeneration/EventDocumentStorageGenerator.cs
src/Marten/Events/EventQueryMapping.cs
src/Marten/Events/MetadataConfig.cs
src/Marten/Events/Operations/QuickAppendEventsOperationBase.cs
src/Marten/Events/Protected/ReplaceEventOperation.cs
src/Marten/Events/Schema/EventMetadataCollection.cs
src/Marten/Events/Schema/EventsTable.cs
src/Marten/Events/Schema/QuickAppendEventFunction.cs
src/Marten/Internal/Sessions/QuerySession.Metadata.cs
src/Marten/Internal/Sessions/QuerySession.cs
src/Marten/Marten.csproj
src/Marten/Storage/Metadata/UserNameColumn.cs

Documentation for LastModifiedBy/UserName tracking on events

Ability to track user name information in events. Closes GH-3265

---

src/Marten/Linq/Parsing/JsonPathCreator.cs
src/Marten/Schema/Arguments/UpsertArgument.cs

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1834
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1847

Replace string with char (Performance Improvmenets)

---

src/DaemonTests/Bugs/Bug_projection_base_settings_must_be_used_by_deamon.cs
src/LinqTests/Acceptance/select_many.cs
src/Marten.AspNetCore/Daemon/AsyncDaemonHealthCheckExtensions.cs
src/Marten/DocumentStore.EventStore.cs
src/Marten/Events/AsyncProjectionTestingExtensions.cs
src/Marten/Events/Daemon/Internals/ProjectionUpdateBatch.cs
src/Marten/Events/Projections/Flattened/EventDeleter.cs
src/Marten/Events/Projections/Flattened/FlatTableProjection.Validation.cs
src/Marten/Events/Projections/Flattened/StatementMap.cs
src/Marten/Internal/CompiledQueries/CompiledQueryPlan.cs
src/Marten/Internal/CompiledQueries/EnumParameterFinder.cs
src/Marten/Internal/CompiledQueries/SimpleParameterFinder.cs
src/Marten/Linq/Parsing/LinqInternalExtensions.cs
src/Marten/Linq/Parsing/LinqQueryParser.Handlers.cs
src/Marten/Services/Json/JsonNetObjectContractProvider.cs
src/Marten/Storage/StorageFeatures.cs

Performance improvement
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1860

Avoid using 'Enumerable.Any()' extension method

---

src/DaemonTests/Coordination/HotCold_leadership_election.cs
src/DaemonTests/EventProjections/event_projections_end_to_end.cs
src/DaemonTests/EventProjections/event_projections_end_to_end_ihost.cs
src/DaemonTests/Internals/HighWaterAgentTests.cs

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254

CA2254: Template should be a static expression
